### ISSUE TITLE
How to increase the quality of VideoPreviewer?

### ISSUE THREAD

**Issue by YunSun** [dji-sdk/Mobile-SDK-iOS#10]
Hello, I am using VideoPreviewer to display the camera feed.
It works, but the quality is bad. I have compared with DJI GO app.
Is there any way to increase it similar as DJI GO?
Regards,
Yun.

**Comment by oliverou** [comment]
Thanks for your feedback. Could you provide the following details to us:
1. Which DJI Product are you using for development? Like Phantom 2 vision+, Inspire 1, etc
2. Do you use our latest Mobile SDK 2.4.1 version?
3. What's your iOS device? like iPhone 6, and which iOS version of your device?

**Comment by YunSun** [comment]
Thanks for your reply.
Followings are the answers for the questions.
1. I use Inspire1
2. Yes, I am using the latest one.
3. I am working on iPad 4

**Comment by oliverou** [comment]
Hi, I have tested the SDK 2.4.1 version sample code on Inspire 1, the video quality seems ok. Maybe you can try the hardware decoding. Please use
~~~objc
-(void) setDecoderDataSource:(int)type;
~~~
method of VideoPreviewer to enable hardware decoding. You can check the camera view of sample code for example too. Hope this help.

**Comment by YunSun** [comment]
Thanks! I think that it's helpful for me.
Now, I found that the video preview isn't synchronized well.
So, it keeps delay.

Any idea to fix it?

**Comment by dji-dev** [comment]
Hi, from our demo, you could see how we use to decode the video feed. You could call our demo and compare it to your sdk based app. I think the delay problem could be solved. Besides, the decoding code is also open-sourced. You could modify them as you wish. Hope you could solve your problem.

**Comment by wenqianqiao** [comment]
Hi, from our demo, you could see how we use to decode the video feed. You could call our demo and compare it to your sdk based app. I think the delay problem could be solved. Besides, the decoding code is also open-sourced. You could modify them as you wish. Hope you could solve your problem.

**Comment by YunSun** [comment]
Hi, I have tested the demo app, and found that it has delay when I switch to hardware decode.

**Comment by oliverou** [comment]
Hi, you can try to change the image transmission speed lower or switch different channels to try in DJI Go app.

**Comment by rhoulay** [comment]
Hi, I'm testing on:
1. OSMO Firmware V 1.4.1.80;
2. iOS SDK 3.0.1;
3. iPhone 5c;

and I find that:
1. low image size - log at MovieGLView.m that show: _width:1280 and _height:717
can I increase the income preview size?

2. hard aliased board problem
![osmo-ios-sdk](https://cloud.githubusercontent.com/assets/962517/13801162/5019b256-eb6a-11e5-9424-ae6674fdcc05.jpg)
Like the screen shot, Mobile-SDK-iOS FPV Preview show hard aliased... 
How can anti-alias preview?

**Comment by XietongLU** [comment]
@rhoulay 
The stream size is 720p. That's the upper bound for our products currently. 
We will update the video previewer soon. Could you try again after the update? Your feedback will be important to us!

**Comment by rhoulay** [comment]
@XietongLU 
Yes, I update SDK and aliased problem solved!

![osmo-ios-sdk-2](https://cloud.githubusercontent.com/assets/962517/13808408/eeddc806-eba0-11e5-94ee-6d095f572416.jpg)

And you said "... stream size is 720p. That's the upper bound for our products currently", stream size will increase later?

**Comment by InguzXX** [comment]
Glad that your issue was solved, close the issue now.
