### ISSUE TITLE
fetchMediaDataWithCompletion consistently fails if the video file is large

### ISSUE THREAD

**Issue by jrichau** [dji-sdk/Mobile-SDK-iOS#102]
Hi - I am trying to download several video files from the drone to the iOS device.

fetchMediaDataWithCompletion consistently fails if the video file is larger than 1GB (and it is quite slow) I understand that one of the main reasons is that these files are large and the transfer is going over the lightbridge connection.

I also tried directly connecting to the drone's microUSB port and while I can obtain model information that way - I can't seem to access the SD card. Is it possible to make it so the SDK can be used to access the SD card by directly connecting to the drone?

-  DJI iOS SDK version: iOS SDK 4.0.1
-  DJI Product: Phantom 4 Pro
-  iOS system version: iOS 10.3.1
-  iOS device type: iPhone6, iPhone7
-  Xcode version: 8.3.2

**Comment by JunL90s** [comment]
Hi,I got a problem with  downloading several video files.How do u use fetchMediaDataWithCompletion to download several files in a time?Do u use GCD？

**Comment by XietongLU** [comment]
@jrichau we improved fetchMediaDataWithCompletion in the past versions. Now, you can continue the download if it is interrupted previously. Also, it is not recommended to download a large file through SDK. Mobile SDK cannot be used to access the SD card directly.

**Comment by XietongLU** [comment]
@JunL90s file data should be fetched one by one.
