### ISSUE TITLE
DJIAircraftYawAction in iOS Swift SDK not working

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-SDK-iOS#104]
We are experiencing an issue where the DJIAircraftYawAction doesn't work at all in our Swift app using the mission control API. The code looks like this:

        let yawAction: DJIAircraftYawAction = DJIAircraftYawAction(relativeAngle: 30, andAngularVelocity: 30)!
        
        let error = DJISDKManager.missionControl()?.scheduleElement(yawAction)
        
        if error != nil {
            print("Error scheduling elements \(String(describing: error))")
            return;
        }
        
        DJISDKManager.missionControl()?.startTimeline()

We have a listener enabled and it always shows "Start Error". Gimbal pitching and waypoints work fine, but the yaw action doesn't. We have tested on P4 and Mavic Pro w/ SDK 4.1.

**Comment by dbaldwin** [comment]
As another data point when scheduling two elements where aircraft yaw is the second, the gimbal will pitch and the yaw will be ignored:

       var elements = [DJIMissionControlTimelineElement]()
        
        let attitude = DJIGimbalAttitude(pitch: -45, roll: 0.0, yaw: 0.0)
        let pitchAction: DJIGimbalAttitudeAction = DJIGimbalAttitudeAction(attitude: attitude)!
        elements.append(pitchAction)
        
        let yawAction: DJIAircraftYawAction = DJIAircraftYawAction(relativeAngle: 30, andAngularVelocity: 30)!
        elements.append(yawAction)
        
        let error = DJISDKManager.missionControl()?.scheduleElements(elements)
        
        if error != nil {
            print("Error scheduling elements \(String(describing: error))")
            return;
        }
        
        DJISDKManager.missionControl()?.startTimeline()

**Comment by aksh1t** [comment]
@dbaldwin When you run the Yaw action, is the aircraft in the air? Yaw action will not work if the aircraft has not taken off yet. Also, could you please confirm if virtual stick mode is enabled? (The key is `DJIFlightControllerParamVirtualStickControlModeEnabled`, it is a `DJIFlightControllerKey`). If not try enabling the virtual stick mode and then performing the yaw action.

**Comment by dbaldwin** [comment]
@aksh1t you have saved the day again! Thank you so much. Now let me mention that we are enabling virtual stick mode using the old method (I guess). We are setting it directly on the flight controller like this:

     fc?.setVirtualStickModeEnabled(true, withCompletion: nil)

We are new to the SDK keys so weren't entirely sure how to set it. This is what we tried but it kept throwing an error:

       guard let virtualStickKey = DJIFlightControllerKey(param: DJIFlightControllerParamVirtualStickAdvancedControlModeEnabled) else {
            return;
        }
        
        DJISDKManager.keyManager()?.setValue(true, for: virtualStickKey, withCompletion: { (error: Error?) in
            
            if error != nil {
                
                print("Error setting virtual stick mode")
                
            }
            
        })

**Comment by dbaldwin** [comment]
BTW it's likely that trying to setValue of true is incorrect. We couldn't find an example of how to enable this using keys.

**Comment by aksh1t** [comment]
> BTW it's likely that trying to setValue of true is incorrect. We couldn't find an example of how to enable this using keys.

You are very close. Instead of just directly setting the value to `true`, you just need to wrap it in a `NSNumber`.

**Comment by dbaldwin** [comment]
Thanks so much @aksh1t we will give this a try. I will close this issue since you've addressed our main concern.

**Comment by amenoni** [comment]
Hi, im getting the same error trying to enable virtual sticks, i´m sending the true parameter like this
`let nstrue: NSNumber = true
        DJISDKManager.keyManager()?.setValue(nstrue, for: enableVirtualStickModeKey!, withCompletion: { (error) in
            if error != nil{
                NSLog("Error setting Virtual Sticks on")
            }else{
                NSLog("Virtual stick mode activated")
            }
        })`

It´s that correct?

Thanks
