### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by zjn13500651999** [dji-sdk/Mobile-SDK-iOS#107]
when pod install like this
![4f885ab9-8c7f-47d9-8c60-4f99c7feca5a](https://user-images.githubusercontent.com/9205538/26866797-62094a12-4b95-11e7-9841-3d6054f0de5f.png)
An error occurred ：
Could not resolve host: dh7g4ai1w5iq6.cloudfront.net。
why?

**Comment by oliverou** [comment]
Hi @zjn13500651999 , that's weird. It works on my side. Could you help to check your corporate network isn't filtering out cloudfront? Or you can try to use this link: <http://dh7g4ai1w5iq6.cloudfront.net/ios_sdk/iOS_Mobile_SDK_4.1.1_170606.zip> to download the SDK directly on web browser, and see if it works.

**Comment by zjn13500651999** [comment]
No matter which way can not be downloaded on my side. I’m in harbin of china. My network not filtering out cloudfront.

**Comment by oliverou** [comment]
Hi @zjn13500651999 , is the issue still exist? We have tested it using Chinese network in Shenzhen here. It works well. Could you try to use your 4G network to do pod install and download the SDK directly using this link: <http://dh7g4ai1w5iq6.cloudfront.net/ios_sdk/iOS_Mobile_SDK_4.1.1_170606.zip> ?

**Comment by zjn13500651999** [comment]
It works well now. Thank you!

**Comment by oliverou** [comment]
Cool! Close the issue now.
