### ISSUE TITLE
Enabling Bitcode for Xcode 7 fails to build

### ISSUE THREAD

**Issue by ckizer** [dji-sdk/Mobile-SDK-iOS#11]
If you enabled bitcode as the documentation says the project will fail to build with a linker error

**Comment by dji-dev** [comment]
Hi, since we use some third party libraries like FFMPEG, which doesn't support bitcode yet,  in our sample code project, we suggest you to disable the bitcode. As the documentation says, you should set the enabled bitcode to NO. Hope it helps.

**Comment by dji-dev** [comment]
Currently, the iOS SDK Sample Code project doesn't support bitcode due to FFmpeg's libavcodec.a issue, we have marked down this problem

**Comment by XietongLU** [comment]
Hi ckizer, we figure out a temporary way to enable bitcode. 
1. Enable bitcode for both demo project and VideoPreviewer project. 
2. Remove "Other Linker Flags" in VideoPreviewer. 
Then you can compile demo with bitcode enabled to your mobile device. However, there will be error when compiling demo with this setting to simulator. So if you want to debug your application on simulator, please use the original setting. 
We will keep looking for a better way to do this. Tell me if the suggestion can solve your problem. Then I can close this issue.

**Comment by dji-dev** [comment]
Hi, since this issue is solved, close it now.

**Comment by EonKid** [comment]
@oliverou I still unable to build Archive
