### ISSUE TITLE
Help needed - How to get DJI Telemetry (Position + 3Axis) with MobileSDK?

### ISSUE THREAD

**Issue by Solimaster** [dji-sdk/Mobile-SDK-iOS#111]
Hi there,
I'm looking for a way to run DJI go App and simultaneity read the drone postion + 3 axis gimbal telemtry in order to draw a footprint on the map. 
I'm thinking about a solution such as dronepan but i was unable to figureout how do they get the gimbal telemetry.

Thanks in advance.

**Comment by aksh1t** [comment]
@Solimaster To get the position of the aircraft, use the key `DJIFlightControllerParamAircraftLocation ` and the key `DJIFlightControllerParamAttitude` for the 3 axis orientation. Also, you will not be able to run the DJI Go app and simultaneously connect a SDK based app to your drone; only one will work at the same time.

**Comment by Solimaster** [comment]
@aksh1t Thanks for your answer. Are you sure about the fact that SDK based app can't work in the background? dronepan for example? droneblocks?

**Comment by aksh1t** [comment]
@Solimaster If you want to create an app which uses the DJI SDK and reads the aircraft positioning and telemetry data and plot it on to a map, you sure can; but the app will need to be active for it to get updates from the DJI SDK. As soon as the app goes into background, it will stop receiving SDK updates. I'm not sure what Dronepan or Droneblocks does in the background that you are trying to do. Could you please give some more detail on what you are trying to do in the background? Thanks.

**Comment by mcelhennyi** [comment]
Was this solved? Is it possible to have an app in the background running connected to the controller as well as DJI Go?

**Comment by aksh1t** [comment]
@mcelhennyi 

> Is it possible to have an app in the background running connected to the controller 
Yes. You need to call [closeConnectionWhenEnteringBackground](http://developer.dji.com/api-reference/ios-api/Components/SDKManager/DJISDKManager.html#djisdkmanager_closeconnectionwhenenterbackground_inline) with `NO`, and that will cause the SDK to NOT close the connection with the controller when the SDK based app goes to background.

> Is it possible to have an app in the background running connected to the controller as well as DJI Go?
No. Only one app can can get updates from the controller at a time. If switching between SDK based app and DJI Go, only the app which is currently running will be connected to the controller (receiving updates from the controller). @XietongLU please confirm.

**Comment by mcelhennyi** [comment]
@aksh1t I think it would be a great addition for DJI to allow for other apps to remain connected in a passive way. Essentially only allowing getter functions to be called, while also leaving the DJIGo App enabled for active control. Someone could write an app that takes the data of the UAV and manipulates it in real time, possibly for external uses. I feel like this may not be possible with AOA (I dont know much about that protocol), but maybe a shared memory, loopback, or something could be used?

**Comment by aksh1t** [comment]
@mcelhennyi I believe that two applications (one foreground, one background) sharing the data stream from a connected external accessory simultaneously is something that is not supported on either platform. However, an easy workaround for the situation you describe would be to just make a custom app which does the UAV data crunching and also has a UI similar to DJI Go for active control (better still, because it can be customized to whatever the requirements are). Do check out our [UILibrary](https://github.com/dji-sdk/Mobile-UILibrary-iOS) project, it has custom UI elements similar to DJI Go which a developer can simply use in a custom app to get a UI similar to DJI Go with minimal effort.

**Comment by bhaveshaks** [comment]
@Solimaster @mcelhennyi @aksh1t Is it possible to have an DJI enabled app in the background running connected and only receive telemetry data update, while also leaving the DJIGo App remains in foreground for active control?

**Comment by mcelhennyi** [comment]
@bhaveshaks
I haven’t  kept up with the api since my last post here. But I would assume it is still not possible, and I tried everything.
