### ISSUE TITLE
Can't play video from Osmo. DJI Go is able to play. Help?

### ISSUE THREAD

**Issue by kibermaks** [dji-sdk/Mobile-SDK-iOS#112]
Hi guys, we are stuck in trying all options to play video previews when connected to any Osmo.

Please give us any help towards this issue as we aim to have media application tied close with managing device library.

Best regards, Maks.

**Comment by XietongLU** [comment]
@kibermaks SDK doesn't support video playback for Osmo yet.

**Comment by kibermaks** [comment]
Thanks XietongLU. I see you fixed ability to play videos from Mavic Pro recently. Can you help us with this feature? Is it easy to add? can we expect to see this functionality in next SDK release?

**Comment by XietongLU** [comment]
@kibermaks by plan, it will be supported in the next SDK version (version after 4.2).
