### ISSUE TITLE
Login to DJI Account using SDK: System is busy, please retry later.(code:-1004)

### ISSUE THREAD

**Issue by ayush-webonise** [dji-sdk/Mobile-SDK-iOS#113]
Hello Guys, I'm trying to use the login functionality provided by DJI.
First time when the user launches the app, it works fine and user gets a DJI Account login page but in case the user closes the page without logging into the account, i try to call the **logIntoDJIUserAccountWithAuthorizationRequired** method again but this time i get the error as **"System is busy, please retry later.(code:-1004)"** and i have to terminate and launch the app again to get the login page.

Please, can you guys help me out with this?

**Comment by oliverou** [comment]
Hi @ayush-webonise, we tried the SDK 4.1.1 version but couldn't reproduce the problem. I canceled the login in page, which would show ERROR: the operation is cancelled. 

But with or without the Internet, I couldn't reproduce the error "System is busy, please retry later.(code:-1004)" Could you please provide more scenario on how to reproduce that? Or a piece of video is much appreciated.

Thanks!

**Comment by XietongLU** [comment]
Logic related to login is improved since 4.2. Please try the latest version of SDK.
