### ISSUE TITLE
Crash in DJI SDK 4.1

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#115]
We are getting a crash reported that is inside the DJISDK, and appears to be happening as part of a callback.  I have the crash report that you can symbolicate to get what is actually happening. It is attached.

Please let me know if you have questions, I can provide a bunch more crash reports if needed.

DJI iOS SDK version = 4.1 (or perhaps 4.1.1, I'm not sure which one it is)
DJI Product = Phantom 4 Pro
iOS system version = 10.3.2
iOS Device = iPad mini 2
Xcode version = 8.3.3

[2017-06-21_09-54-16.9388_-0500-ba00a5f4797c965afc1cabbc45dfc16527b638ec.crash.zip](https://github.com/dji-sdk/Mobile-SDK-iOS/files/1098822/2017-06-21_09-54-16.9388_-0500-ba00a5f4797c965afc1cabbc45dfc16527b638ec.crash.zip)

**Comment by zoemcateedji** [comment]
We just released 4.2 http://developer.dji.com/mobile-sdk/downloads/ today - you might want to look at that while we take a look at your crash

**Comment by XietongLU** [comment]
This is fixed in 4.2.
