### ISSUE TITLE
Mobile-SDK-iOS/Sample Code/SwiftSampleCode/DJISDKSwiftDemo/Missions/TimelineMissionViewController.swift has an misspelled constant

### ISSUE THREAD

**Issue by UdonDa** [dji-sdk/Mobile-SDK-iOS#117]
[TimelineMissionViewController.swift](https://github.com/dji-sdk/Mobile-SDK-iOS/blob/master/Sample%20Code/SwiftSampleCode/DJISDKSwiftDemo/Missions/TimelineMissionViewController.swift) 
line 105 and 106

> if let aircarftLocationKey = DJIFlightControllerKey(param: DJIFlightControllerParamAircraftLocation)  {

I think "aircarftLocationKey" is missspelled.
So, you should have to correct it to "aircraftLocationKey"

**Comment by athiercelin** [comment]
Thank you for reporting this, we'll get it fixed.

**Comment by UdonDa** [comment]
you are welcome
