### ISSUE TITLE
The property durationInSeconds of DJIMediaFile obj(video type) is 0?

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#119]
## Description of the issues

I found that the property `durationInSeconds` of DJIMediaFile obj of video type equals to 0.0

## Steps to reproduce the bug

I got the `DJIMediaFile` obj in a delegate method, then logged the file infos out, where I found the 0.0 duration:

```Swift
func camera(_ camera: DJICamera, didGenerateNewMediaFile newMedia: DJIMediaFile) {
    NSlog("Generate new media file: \(newMedia.fileName), duration: \(newMedia.durationInSeconds)")
}
```

##  DJI iOS SDK version

I am using DJI iOS SDK **4.2**.

##  DJI Product

I am using Phantom4.

##  iOS system version

I am using iPhone6 with iOS 10.3.2 .

##  Xcode version

I am using Xcode 9.0 beta

**Comment by oliverou** [comment]
Hi @PandaraWen, please check the documentation of the `didGenerateNewMediaFile` method: 

<http://developer.dji.com/api-reference/ios-api/Components/Camera/DJICamera.html?search=didgenerat&i=0&#djicamera_didgeneratenewmediafile_inline>

**Additionally, for this instance of DJIMediaFile, the `durationInSeconds` property is 0 and the `videoOrientation` property is DJICameraOrientationLandscape.**

**Comment by PandaraWen** [comment]
Thanks for replying @oliverou , but I am wondering when would this property be valid? Because I found this statement in document for `durationInSeconds`:

> If the media file is a video, this property returns the duration of the video in seconds. Will be 0s if the media file is a photo.

**Comment by XietongLU** [comment]
It is valid if the DJIMediaFile instance is from fileListSnapshot of DJIMediaManager.
