### ISSUE TITLE
Can't find associated class/methods while upgrading SDK to v3.0 from v2.4

### ISSUE THREAD

**Issue by YunSun** [dji-sdk/Mobile-SDK-iOS#12]
Hello, thanks for updating the SDK. Great job!

I have some questions about the new SDK.
- How to enter/exit the navigation mode?
[self.navigationManager enterNavigationModeWithResult: ^(DJIError *error) {}];

Regards,
Yun.

**Comment by dji-dev** [comment]
Hi, thanks for your support!  We have deleted the enterNavigationModeWithResult method in SDK v3.0. The SDK 3.0 will do it automatically for you. For more, please check our iOS Sample Code on this Github page. Hope it helps!

**Comment by YunSun** [comment]
Thanks for your answer.

I have another question.
In the past, I could get the Video Signal Quality and RC Signal Quality separately in the following callback
- (void)imageTransmitter:(DJIImageTransmitter *)transmitter didUpdateRadioSignalQuality:(DJIImageTransmitterRadioSignalQuality)quality
{
if (quality.mUpLink) {quality.mPercent // RC Signal}
else {quality.mPercent // Video Signal}
}

Now I can get the signal quality in the callback
- (void)wifiLink:(DJIWiFiLink *_Nonnull)link didUpdatesWiFiSignalQuality:(DJIWiFiSignalQuality)quality
But now sure whether it's for Video Signal or RC Signal.

**Comment by dji-dev** [comment]
Please check the DJILBAirLink.h file, we provide two new delegate methods as shown below for you to access the RC signal and video signal.

~~~objc
/**
 *  Signal quality and strength information for current downlink channel on each Remote Controller antenna.
 *
 *  @param lbAirLink     LBAirLink Instance.
 *  @param antennas    DJISignalInformation object.
 */
- (void)lbAirLink:(DJILBAirLink *_Nonnull)lbAirLink didUpdateRemoteControllerSignalInformation:(NSArray *_Nonnull)antennas;

/**
 *  Signal quality and strength information for current uplink channel on each air link module antenna.
 *
 *  @param lbAirLink lbAirLink Instance.
 *  @param antennas    DJISignalInformation object.
 */
- (void)lbAirLink:(DJILBAirLink *_Nonnull)lbAirLink didUpdateLBAirLinkModuleSignalInformation:(NSArray *_Nonnull)antennas;
~~~

The above wifiLink method is for WiFi devices, like Phantom 3 Standard and OSMO.

Hope it helps!

**Comment by YunSun** [comment]
Thank you
