### ISSUE TITLE
multiply view controller application

### ISSUE THREAD

**Issue by sqhuang** [dji-sdk/Mobile-SDK-iOS#121]
-  
I am raising this issue because I am confused.
If I use multiply view controller application like 
use waypointVC.m to implement the waypoint mission,
use tapflyVC.m to implement the tapfly function and so on
and using storyboard to navigate all this views,
should I call register app method in every VC?
-  iOS UILibrary 4.2
-  Phantom 4 Pro
-  iOS 10.3
-  iPad mini 4 wifi
-  Xcode 8.0

**Comment by oliverou** [comment]
Hi @sqhuang, you only need to register your application once, you can check the API Doc of the `registerAppWithDelegate:` method for details: <http://developer.dji.com/api-reference/ios-api/Components/SDKManager/DJISDKManager.html?search=registerappwithdelegate&i=0&#djisdkmanager_registerapp_inline>. Also, you can check this [tutorial](http://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html#register-application) to learn how to register your application.

**Comment by sqhuang** [comment]
thanks.
