### ISSUE TITLE
Can not assign AdvancedGestureControlEnabled via DJIKeyManager

### ISSUE THREAD

**Issue by Sunnyyoung** [dji-sdk/Mobile-SDK-iOS#122]
## Description

According to the DJI documents [DJIFlightAssistant](http://developer.dji.com/api-reference/ios-api/Components/IntelligentFlightAssistant/DJIIntelligentFlightAssistant.html), the list of class members can be assigned via `DJIKeyManager` except `AdvancedGestureControlEnabled`, so whether it can be added into `DJIKeyManager` so that we can assigned the `AdvancedGestureControlEnabled` property easily?

## Environment

- SDK Version: 4.2.2
- Xcode Version: 8.3.3 (8E3004b)
- macOS Version: 10.12.5 (16F73)

**Comment by XietongLU** [comment]
Yes. Sorry for missing it from the existing SDK. Will be added in the coming version.
