### ISSUE TITLE
Completion blocks for way point action

### ISSUE THREAD

**Issue by hy9be** [dji-sdk/Mobile-SDK-iOS#125]
Hi, is it possible to have a completion block like this for DJIWayPointAction?
``` objective-c
[camera startShootPhotoWithCompletion:^(NSError * _Nullable error) {
    ....
}];
```
I found sometimes my photo taking action is not executed. But not sure about the reason and thus there is no way I can handle the error.
``` objective-c
[waypoint addAction:[[DJIWaypointAction alloc] initWithActionType:DJIWaypointActionTypeShootPhoto param:0]];
```
Thanks!

**Comment by XietongLU** [comment]
No. It is a firmware limitation. A workaround will be to observe the state from camera to check if the action is executed successfully.

**Comment by hy9be** [comment]
@XietongLU Thanks! Do you know why the shoot photo actions fail sometimes? Anyway to prevent it from happening?
