### ISSUE TITLE
DJIGoToAction in SDK 4.2.2 does not work with Spark

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-SDK-iOS#126]
We have been extensively beta testing SDK 4.2.2 with DroneBlocks and Spark. Simple actions like taking photos, pitching gimbal, yawing, and takeoff all work fine. But any DJIGoToAction seems to fail with the following error:

![img_0227](https://user-images.githubusercontent.com/38339/28300435-0cb2200a-6b45-11e7-86ae-096bde9ec13a.PNG)

Is this a known issue? We're trying to get a release out the door for Spark and are uncertain about this. If this is a known issue is there any rough estimate on when we can expect this to work?

Thanks.

**Comment by XietongLU** [comment]
Waypoint mission is not supported by Spark for now (may be available in the future). GoToAction is actually using waypoint mission. Therefore, GoToAction is not supported by Spark either.
