### ISSUE TITLE
Wrong RC firmware version being reported

### ISSUE THREAD

**Issue by dnc253** [dji-sdk/Mobile-SDK-iOS#127]
The SDK is reporting the wrong version of the RC firmware with the following code:

```
+(DJIRemoteController*) fetchRemoteController {
    if (![DJISDKManager product]) {
        return nil;
    }
    
   if ([[DJISDKManager product] isKindOfClass:[DJIAircraft class]]) {
     return ((DJIAircraft*)[DJISDKManager product]).remoteController;
   }
			    
    return nil;
}

DJIRemoteController *rc = [ComponentHelper fetchRemoteController];
if (rc) {
	[rc getFirmwareVersionWithCompletion:^(NSString * _Nullable version, NSError * _Nullable error) {
		if (error) {
			resolve(error);
			rcVersionPromise = nil;
		}
		else {
			resolve(version);
		}
	}];
}
else {
	resolve([NSError errorWithDomain:@"DJIWrapperDomain" code:-1 userInfo:@{NSLocalizedDescriptionKey : @"could not fetch remote controller"}]);
}
```
This is a screenshot from DJI GO:
![db066dad-d4ad-4682-a098-e440c3341cdc](https://user-images.githubusercontent.com/18408070/28381755-18fa85f2-6c79-11e7-8066-8a4bb15615b4.PNG)

And a screenshot from our app showing the firmware version:
![img_0016](https://user-images.githubusercontent.com/18408070/28381840-5f846524-6c79-11e7-8eec-b6dd330c351c.PNG)

This is iOS SDK version 4.2.2 and earlier 4.x versions.
This is on the Phantom 4 Pro (haven't checked others)
This is on iOS 10.3.x
This is on various iPads
This is on Xcode version 8.3.3

**Comment by XietongLU** [comment]
@dnc253 we've reproduced it and the fix will be included in 4.3.

**Comment by dallinski** [comment]
Using SDK v4.5.3, this bug is still present

**Comment by XietongLU** [comment]
@dallinski are you still seeing different versions from GO and SDK?

**Comment by dallinski** [comment]
I was mistaken. I had a build of our app that I thought was using SDK v4.5.3, but it wasn't. Once I updated the SDK, it reported the correct RC firmware version. So this bug can be closed.

**Comment by XietongLU** [comment]
@dallinski thx
