### ISSUE TITLE
Why SDK always download the same file after launch the app?

### ISSUE THREAD

**Issue by Sunnyyoung** [dji-sdk/Mobile-SDK-iOS#128]
## Description

The SDK will download a file `flysafe_areas_djisdk.db` to the `/tmp/xxxx` folder every time after launch the application.

![image](https://user-images.githubusercontent.com/5926284/28488332-e3d8fcec-6ed9-11e7-8480-7a9420aab8d8.png)
![image](https://user-images.githubusercontent.com/5926284/28488340-f7a234dc-6ed9-11e7-896e-bc88d95d0354.png)

## Environment

- SDK Version: 4.2.2
- Xcode Version: 8.3.3 (8E3004b)
- macOS Version: 10.12.5 (16F73)

**Comment by oliverou** [comment]
Hi @Sunnyyoung, the `flysafe_areas_djisdk.db` is not downloaded by the SDK and the size is just several MBs. 1.25GB of your app's tmp folder is not caused by the SDK. Please check again.

**Comment by Sunnyyoung** [comment]
@oliverou Yes! I'm pretty sure that it is caused by the SDK, because the result is tested by the official demo project, which just has `DJI-SDK-iOS` in the pod file.

And the list of folders `XXXXXXXX-XX......` all of them contains the `flysafe_areas_djisdk.db` file.
![image](https://user-images.githubusercontent.com/5926284/28507442-5709b184-7065-11e7-8f6e-7120c734dbd1.png)

**Comment by PandaraWen** [comment]
Yeah, I found the same problem, it's so weird

**Comment by oliverou** [comment]
Hi @Sunnyyoung @PandaraWen, thanks for the feedbacks. We have addressed this issue, and will fix it in the upcoming SDK release. To clarify the issue, the .db file is not downloaded by the SDK, for the workaround, please remove the .db file manually.

**Comment by XietongLU** [comment]
To explain more, the file is generated by SDK with local resource. Not internet data is consumed.

**Comment by Sunnyyoung** [comment]
@oliverou @XietongLU 

😐  Still tested by the official demo project.

![untitled](https://user-images.githubusercontent.com/5926284/28607810-1bdd8c3c-7210-11e7-86ba-116ee157a6f3.png)

**Comment by XietongLU** [comment]
@Sunnyyoung that's unexpected. We will investigate more about this issue. Thanks for your information.

**Comment by oliverou** [comment]
Hi @Sunnyyoung, could you help to check the [databaseVersion](http://developer.dji.com/api-reference/ios-api/Components/FlyZoneManager/DJIFlyZoneManager.html?search=database&i=0&#djiflyzonemanager_databaseversion_inline) value of `DJIFlyZoneManager` class and tell us? It would be helpful for us to investigate the issue. Thanks!

**Comment by Sunnyyoung** [comment]
@oliverou Sure, the databaseVersion is `01.00.01.04`.

**Comment by XietongLU** [comment]
@Sunnyyoung we've fixed the issue from the server side. Please check if you can still reproduce the issue.

**Comment by Sunnyyoung** [comment]
@XietongLU The downloading issue gone, but still creates duplicate files: `flysafe_areas_djisdk.db`, hope that will be fixed in 4.3.
