### ISSUE TITLE
getRCSwitchFlightModeMappingWithCompletion - Getting parameters operation failed.(code:-1006)

### ISSUE THREAD

**Issue by dallinski** [dji-sdk/Mobile-SDK-iOS#129]
Whenever I try to call getRCSwitchFlightModeMappingWithCompletion, I get an error: "Getting parameters operation failed.(code:-1006)". The DJIFlightController is always valid and other calls on the object seem to work just fine. 

I realize that the call probably works for DJI's developers, or else they wouldn't have released it as part of the SDK. But I cannot get it to work, no matter what I try. At the very least, can someone give some direction on why I am getting the -1006 error code.

DJI iOS SDK: 4.2.2
Phantom 4 Pro
iOS 10.3.2
iPad (the one released March 2017)
Xcode 8.3.3

**Comment by XietongLU** [comment]
@dallinski we tested P4P with the latest firmware but we cannot reproduce the issue. 
Please check: 
1. If you enable the bridge mode while the remote controller is connected to SDK directly. 
2. Use DJI GO to check if the aircraft is in normal state. 
3. If you have other DJI products, check if the same interface works on the other products.

**Comment by dallinski** [comment]
1. Yes, I am have tried this with an iPad connected directly to the rc, and I have also tried with bridge mode (running my app on iPad simulator, DJI bridge linking a real iPad that is connected to the rc)
2. Yes, the aircraft is in a normal state
3. I tried with a Mavic Pro and had the same error

Is there anything special I need to do in order for the getRCSwitchFlightModeMappingWithCompletion call to work properly?
Can you give me any more information than the error code -1006? It really doesn't help me diagnose the problem at all.

**Comment by dallinski** [comment]
I had been calling getRCSwitchFlightModeMappingWithCompletion as soon as the flightController was connected. I tried calling it a couple of seconds later, and it worked.

Is there any variable on the flightController that I can look at for an indication of when getRCSwitchFlightModeMappingWithCompletion can be successfully called?

**Comment by dallinski** [comment]
I modified our code so that it would only call getRCSwitchFlightModeMappingWithCompletion after we had fetched the remote controller and now it works consistently. Just me guessing here, but ((DJIAircraft*)[DJISDKManager product]).flightController is set before ((DJIAircraft*)[DJISDKManager product]).remoteController.

**Comment by XietongLU** [comment]
@dallinski the life cycle of the components are independent to each other. So do not have assumption of the order.
For this bug, it is reproduced and fixed internally. The fix will be included in the next release.
