### ISSUE TITLE
Swift Example Code [DJIBaseProductDelegate Bug?]

### ISSUE THREAD

**Issue by ZENUAV** [dji-sdk/Mobile-SDK-iOS#14]
In the example StartupViewController you have the following code for Product connection changes, but it never fired.

I'm testing on iOS 9, iPad Mini, iPhone 6s and Inspire 1 with latest FW.

`// DJIBaseProductDelegate
extension StartupViewController : DJIBaseProductDelegate {

```
// product
func product(product: DJIBaseProduct, connectivityChanged isConnected: Bool)
{
    if (isConnected)
    {
        productConnectionStatus.text = "Status: Product Connected"           
    }
    else
    {
        productConnectionStatus.text = "Status: No Product Connected"
    }
}
```

}`

**Comment by dji-dev** [comment]
Hi， we tested the baseProduct class. The isConnected Bool has the value change when the connection status changes. The corresponding screenshot has been sent to your email account.  Please double check and see if you are using it correctly.

**Comment by ZENUAV** [comment]
It does if it is used on it's own, but in your example it's used with DJISDKManagerDelegate.

It does not seem to fire, I think the sdkManagerProductDidChangeFrom is getting the event and not the DJIBaseProductDelegate > product method.

You have put log statements in your example, they don't get hit??

**Comment by dji-dev** [comment]
Hi, we will fix the problem in the next version update, currently please use the sdkManagerProductDidChangeFrom delegate method to check the product connection change status.

**Comment by XietongLU** [comment]
The interface has been refactored in SDK 4.0.
