### ISSUE TITLE
Can the ios simulator transfer video stream to PC? 

### ISSUE THREAD

**Issue by cornicione** [dji-sdk/Mobile-SDK-iOS#15]
I saw you connect simulator and PC with a url address. I wonder if they can share the video stream? At least from the simulator to PC?   
 

          THANK U

**Comment by XietongLU** [comment]
Yes. Using DJI Bridge App, you can see the video stream on the simulator.

**Comment by XietongLU** [comment]
Because there is no more feedback for this issue, I close it now. If there is more questions, please raise another issue.
