### ISSUE TITLE
EXC_BAD_ACCESS in VideoPreviewer with iOS 11 GM

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#156]
When I debug my app with VideoPreviewer(latest commit) in my iPhone with iOS11 GM, Xcode throw an error to me:

![2017-09-14 11 42 51](https://user-images.githubusercontent.com/3304493/30411294-a953d21a-98d5-11e7-8944-6420d123fa5e.png)

and the calling stack is:

![2017-09-14 11 45 35](https://user-images.githubusercontent.com/3304493/30411301-b094aa36-98d5-11e7-904b-a94ca58aa1af.png)

the assembly code:

![2017-09-14 11 46 03](https://user-images.githubusercontent.com/3304493/30411304-b4ed5880-98d5-11e7-9556-5a3e88e75ebf.png)

So now I can't run my app in my iPhone6 with iOS11 GM. But all things go well in my iPhone5s with iOS11 beta 3.

I am using Xcode 9.0 beta 3

**Comment by RussellFenenga-DJI** [comment]
Hi @PandaraWen If possible could you please provide us with a crashlog to help us investigate this?

**Comment by PandaraWen** [comment]
@RussellFenenga-DJI But there is no other log in my Xcode console.

**Comment by XietongLU** [comment]
@PandaraWen iOS 11 is released officially. Is the bug reproducible on it? Also, is the bug 100% reproducible? Are there any specific steps? I tried with an iPad Pro but it doesn't crash.

**Comment by PandaraWen** [comment]
After I updating my iPhone 6 to iOS 11b1, the bug gone.
