### ISSUE TITLE
Can't get the goHomeExecutionState with keyManager

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#158]
In the whole process when the aircraft is going home, whenever I call the follow code, I can only get the nil value:

```Swift
let key = DJIFlightControllerKey(param: DJIFlightControllerParamGoHomeExecutionState)!
if let value = DJISDKManager.keyManager()?.getValueFor(key) {
    NSLog("Go home stat: \(value.unsignedIntegerValue)")
} else {
    NSLog("No go home value")
}
```

-  DJI iOS SDK: 4.2.2
-  DJI Product: Mavic Pro
-  iOS system version: iOS 11 GM
-  iOS device type: iPhone 6
-  Xcode version: Xcode 9 GM

I ran my program in DJI-Assitant.

**Comment by PandaraWen** [comment]
And even I log the value of `state.goHomeExecutionState.rawValue` in `DJIFlightController`'s delegate implement, all I get is 0, which means `DJIGoHomeExecutionStateNotExecuting`. So is there some bug of SDK or Am I missing something?

**Comment by PandaraWen** [comment]
Now I have updated my project to DJISDK 4.3, and I can get valid `goHomeExecutionState` in `DJIFlightControllerState`, but I still can not get that value through `keyManager`.

**Comment by athiercelin** [comment]
That's because this key is not gettable.
You should start listening to it instead.

We need to do more work on documentation.

**Comment by PandaraWen** [comment]
Alright...So that's it
