### ISSUE TITLE
FPV 4:3 ratio

### ISSUE THREAD

**Issue by rhoulay** [dji-sdk/Mobile-SDK-iOS#16]
I want FPV Preview render as 4:3 ratio but it seem has problem:

Setting photo ratio at DJI GO APP:
![5 pic](https://cloud.githubusercontent.com/assets/962517/13835349/028c4abc-ec32-11e5-932d-f8b916cc3231.jpg)

![6 pic](https://cloud.githubusercontent.com/assets/962517/13835408/90a1a310-ec32-11e5-8845-f477671a4c96.jpg)

show 4:3 preview but left right has black border, I check MovieGLView.m find that input video stream 1280x717 px at 4:3 and 16:9 ratio.

It's bug? How can I adjust it?

**Comment by XietongLU** [comment]
The black border is also part of the video stream. So you need to trim the view. For some products (P3S), there is no black border. So, to optimize the UI, you need to do it case by case.

**Comment by rhoulay** [comment]
Ok, it's complicated, I can adjust that and wish camera out put standard later :)

**Comment by dji-dev** [comment]
Hi rhoulay, it seems that your problem is solved, let me close the issue, thanks!
