### ISSUE TITLE
What's new/different in 4.3?

### ISSUE THREAD

**Issue by nhantrivinh** [dji-sdk/Mobile-SDK-iOS#160]
Could we have documentation of what's new/different in DJI SDK iOS 4.3?

**Comment by oliverou** [comment]
Hi @nhantrivinh, please check this [4.2.0_4.3.0_diff.html](https://github.com/dji-sdk/Mobile-SDK-iOS/blob/master/docs/SDK%20Headers%20Diff/4.2.0_4.3.0_diff.html) file for the details.

**Comment by nhantrivinh** [comment]
Hi @oliverou , thanks for point me to where the changes are documented.

However, it is quite difficult to read the changes at the moment like this:

![](https://i.imgur.com/kM71ama.png)

Is there any way that you would recommend to make the above more readable? Thanks.

**Comment by oliverou** [comment]
Hi @nhantrivinh , please download the 4.2.0_4.3.0_diff.html file and double click to open it as a web page, you should have a nice looking layout.

**Comment by nhantrivinh** [comment]
Thanks @oliverou!
