### ISSUE TITLE
SDK 4.3.1 Missing Info.plist Keys

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-SDK-iOS#163]
We tried uploading DronePan to our beta users today with SDK 4.3.1 included. It appears there are some new plist keys that are necessary. We'll go ahead and add these descriptions to our plist file, but are they really necessary? 

**Missing Info.plist key** - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

**Missing Info.plist key** - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSAppleMusicUsageDescription key with a string value explaining to the user how the app uses this data.

If they are indeed necessary would you mind sharing with us the intent of these keys?

Thanks.

**Comment by athiercelin** [comment]
The mobile SDK has a convenience authorization class that makes it easier for us (and our apps) to request access to all sensitive systems (microphone, camera, photos, apple music).
Apple recently improved their scanning system and detect the call for these symbols prior to submission.
It's not being used in either the mobile SDK or the UILibrary so I would recommend to give an explanation to it in the line of "It's not being used by the app but part of a convenience method in the DJI SDK"

**Comment by dbaldwin** [comment]
Great @athiercelin thank you for the explanation. We've gone ahead and added the description "Not used..." for these keys and re-submitted the beta.

**Comment by dbaldwin** [comment]
@XietongLU yes we recently submitted an app without them and it works well. Thanks for following up.
