### ISSUE TITLE
CPU 99% with the Last Version DJI SDK and Video Previwer

### ISSUE THREAD

**Issue by guicolares** [dji-sdk/Mobile-SDK-iOS#165]
Hello Everyone!

I am using the last DJI SDK(4.3) and VideoPreviewer on iOS 10 or iOS 11. 
The VideoPreviewer's code is oscillating 1% to 100% CPU, even the aircraft is not connected. 
That is my code in "viewWillAppear" bellow: 
`VideoPreviewer.instance().setView(self.fpvView)
  DJISDKManager.videoFeeder()?.primaryVideoFeed.add(self, with: nil)
   VideoPreviewer.instance().start()`
And here is a Print when that is happening the 100% CPU.
<img width="1280" alt="screen shot 2017-09-21 at 01 48 13" src="https://user-images.githubusercontent.com/6391551/30679558-b8430f48-9e70-11e7-9637-8b9141e562fe.png">

Xcode Version 9.0

obs:
I have another App with DJI SDK 3.3 that works perfectly. 

Thanks.

**Comment by fontained** [comment]
Hi @guicolares, did you update the VideoPreviewer? There was a fix for IOS11. See here https://github.com/dji-sdk/Mobile-SDK-iOS/tree/master/Sample%20Code/VideoPreviewer
I didn't test yet but I will do it soon. Best regards.

**Comment by XietongLU** [comment]
@guicolares could you point out the steps to reproduce the issue? I use Osmo with iPhone 6 Plus (iOS 10.3.3). I modified the swift sample. Beside the code you provided, I also add: 
    func videoFeed(_ videoFeed: DJIVideoFeed, didUpdateVideoData videoData: Data) {
        let nsData = videoData as NSData
        VideoPreviewer.instance().push(UnsafeMutablePointer(mutating: nsData.bytes.assumingMemoryBound(to: UInt8.self)), length: Int32(nsData.length))
    }
Video displayed normally. Then I disconnected the Osmo. However, I didn't observe the CPU burst as your screenshot.

**Comment by justinmiller62** [comment]
I am running into the same issue, to the point that is making my app unable to upload waypoint missions because the video decoder and SDK are taking up so much CPU usage, the CPU usage does not appear to be different between hardware decoding or software decoding. testing with iOS 10 and 11. The cpu will backup so much that the video feed becomes significantly delayed.

**Comment by XietongLU** [comment]
@justinmiller62 which phone are you using? How do you enable the hardware decoding?

**Comment by justinmiller62** [comment]
Testing with an iPad mini 4.

`VideoPreviewer.instance().enableHardwareDecode = true`

Also tried this as false, with and without setting the encoder type to the appropriate model. 
 
Also tried the following with the hardware decoding and the other configurations. 

`VideoPreviewer.instance().enableFastUpload = true`

Code written in swift 4.0

**Comment by guicolares** [comment]
I did as said @XietongLU and @justinmiller62  and it is not happing any more. 

Thanks
