### ISSUE TITLE
我想自己用自己开发的app实现推流拉流远程直播，就像DJI GO可以在其他终端直播那样

### ISSUE THREAD

**Issue by zhouyian123** [dji-sdk/Mobile-SDK-iOS#166]
我想自己用自己开发的app实现推流拉流远程直播，就像DJI GO可以在其他终端直播那样，但是现在没有思路，有哪位做过吗？求指教？

**Comment by JunL90s** [comment]
你好，加个联系方式，我也在做这个需求。

**Comment by zhouyian123** [comment]
微信号，18565851613

**Comment by JunL90s** [comment]
加了，通过下，谢谢。

**Comment by oliverou** [comment]
Please use English when creating an issue.
