### ISSUE TITLE
DJISDKManager.registerApp() crashes app on some devices

### ISSUE THREAD

**Issue by geeee** [dji-sdk/Mobile-SDK-iOS#169]
-  Description of the issues. 
DJI SDK crashes while trying to register the app on older devices/iOS

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
Happens right after DJISDKSwiftDemo is started

-  Crash logs (If you can find it, it would be very helpful)
Full crash log: https://gist.github.com/geeee/9fb54f036512d283af39f3e2db14fe49

-  DJI iOS SDK version you are using (Like iOS SDK 3.4, etc)
iOS SDK 4.3.1

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Happens before DJI Product is connected

-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)
Tested and **crashes** on iPad 2 (iOS 9.3.5), iPhone 5 (iOS 10.3.1)
Tested and **works ok** on iPhone 6s, iPad mini 2 (iOS 10.3.3), iPhone 7 (iOS 11.0.1), iPhone 8 (11.0.1)

-  Xcode version you are using (Like Xcode 7.0)
Xcode Version 9.0

**Comment by MeteC** [comment]
Me too

Crash log: https://gist.github.com/MeteC/34dc0cbeceaa59328ec0b998fb960038

DJI iOS SDK: 4.3.2
XCode version 9.0.1

**Crashes** iPhone 5C running iOS 10.3.3 
**Fine** on iPhone 6 (iOS 11.0.3), iPad Mini (iOS 11.0.3)

**Comment by XietongLU** [comment]
@geeee did you test SDK 4.3.2? Could you provide more crash logs?

**Comment by MeteC** [comment]
I tested 4.3.2..

**Comment by XietongLU** [comment]
@MeteC I analyzed your crash log and the stack looks different from the one from @geeee . I want to confirm if they are the same issue.

**Comment by MeteC** [comment]
ok thanks 👍

**Comment by XietongLU** [comment]
@geeee @MeteC we found that it is an issue only existing in old iPhone devices with CPU architecture armv7 or armv7s. They are devices not supported by DJI SDK (https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-prerequisits.html). We found a solution to resolve this issue but I am afraid that the fix version will not be released very shortly. If you are blocked by this issue, please contact dev@dji.com.

**Comment by geeee** [comment]
Thanks for looking into this @XietongLU
