### ISSUE TITLE
SDK 4.3.1 Aircraft cannot execute virtual stick commands (code: -4003)

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-SDK-iOS#170]
We've been testing with SDK 4.3.1 for the last week and have run into the error:

"Aircraft cannot execute virtual stick commands (code: -4003)"

We are using the DJIAircraftYawAction in our code and based on the following ticket we opened a few months ago:

https://github.com/dji-sdk/Mobile-SDK-iOS/issues/104

We have implemented virtual stick mode as you can see here:

https://github.com/dbaldwin/DronePan-Swift/blob/master/DronePan-Swift/CameraViewController.swift#L240-L249

Never do we see an error enabling virtual stick mode. What happens is that the aircraft may yaw once or twice successfully and then the error shows up. This has happened to use during testing of Mavic Pro and Phantom 4. The Phantom 4 appears to be more stable and this happens more often than not on Mavic Pro. During the sequence of a DronePan mission the aircraft may yaw anywhere between 5 to 15 times. 

![img_0274](https://user-images.githubusercontent.com/38339/31253310-01df88d2-a9ea-11e7-8cb9-36eee68b989e.PNG)

Let me also mention that we did not see this error nearly as much in SDK 4.2.

Have you guys seen this error before?

**Comment by dbaldwin** [comment]
Hi, here is a report from one of our Mavic Pro users that is getting the same error. The aircraft yawed fine and then on the next yaw sequence they saw the error. 

![dronepan_error](https://user-images.githubusercontent.com/38339/31319818-4a695dca-ac2f-11e7-8579-2518e225a64b.jpg)

**Comment by PandaraWen** [comment]
I have the same error too, when my Phantom4 start a TimelineMission with the first element of aircraftYawAction, the `missionOperator` throw this error to me.

**Comment by PandaraWen** [comment]
I test again this morning, and try to execute a timeline mission of 8 aircraftYawActions, found that the mission sometimes can start successfully, then the aircraft would be stuck in some step, but the `DJISDKManager.missionControl()` keeps sending me the `proceed` event.

I am using `Phantom4A`, `DJISDK 4.3.1`,  `iPhone6` with `iOS 11.1 beta`, `Xcode 9.1 beta`

**Comment by PandaraWen** [comment]
Related issue [here](https://github.com/dji-sdk/Mobile-SDK-iOS/issues/184)

**Comment by dbaldwin** [comment]
We are still seeing this issue with SDK 4.3.2. It's causing several of our apps to become unusable. Is there a fix in the works for the next version of the SDK?

**Comment by oliverou** [comment]
Hi @dbaldwin , @PandaraWen , thanks for the feedbacks! @We are working on fixing this issue, will resolve it in our upcoming SDK release.

**Comment by dbaldwin** [comment]
@oliverou that would be great. I know you hate hearing this question, but any rough estimate when the next SDK will be available? Or is there still an option to get on the beta? We'd be happy to beta test if that's an option. Thank you.

**Comment by oliverou** [comment]
Hi @dbaldwin, we plan to release the next SDK in the early December, for beta test, please send me an email: oliver.ou@dji.com.

**Comment by dji-dev** [comment]
Hi @dbaldwin , have you resolved your issue with the latest DJI SDK version? If not, please help to report your issue to dev@dji.com, as it's our official channel for developers to request  DJI SDK support now.
