### ISSUE TITLE
Option to save files into specific folder or option to set the prefix file name

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-SDK-iOS#171]
Is there a way to specify (and create) a folder in the SD Card using the SDK?
Or is it possible to specify a custom prefix of the file instead of the default DJI_? 
I need to take a bunch of pictures of different areas and using the same SD Card is hard to know what pictures belong to what regions.
If I have this option, then from my App I can specify the prefix per region.

**Comment by zoemcateedji** [comment]
Perhaps you could set the XMP meta data information with the area

http://developer.dji.com/api-reference/ios-api/Components/Camera/DJICamera.html?search=mediafilecustom&i=0&#djicamera_camerasettings_setmediafilecustominformation_inline

**Comment by Daxito** [comment]
Sounds like an option! thanks!
