### ISSUE TITLE
more helpful description of DJISDKMissionErrorDomain

### ISSUE THREAD

**Issue by kaizensoze** [dji-sdk/Mobile-SDK-iOS#172]
When starting a timeline via mission control, all I'm doing is something simple like `DJIGimbalAttitudeAction(attitude: DJIGimbalAttitude(pitch: 15, roll: 0, yaw: 0))` and in the listener block I'm getting the following error:

> The operation couldn’t be completed. (DJISDKMissionErrorDomain error 10010.)

How would I get more info into what error 10010 is? I tried doing a switch on DJISDKMissionError to hopefully reveal more info as to the exact cause but that doesn't do the trick. Is the error object in the addListener method even of type DJISDKMissionError?

Using iOS 11 with Xcode 9.0. Testing on a Mavic Pro.

**Comment by aksh1t** [comment]
If you look at the DJIMissionControl.h file in the SDK headers, you will find the error enums with their codes. Just for reference, they are:

/**
 *  Default placeholder when no other code matches.
 */
DJIMissionControlErrorUnknown = -1,

/**
 *  Can't pause an element which is not pausbile.  This error doesn't is
 *  informational and doesn't impact Timeline.
 */
DJIMissionControlTimelineErrorCantPauseUnpausableElement = 10001,

/**
 *  Tried to schedule new element while the Timeline was running.
 */
DJIMissionControlTimelineErrorCantScheduleWhileRunning = 10002,

/**
 *  Can't start a timeline whose marker is already at the end.
 */
DJIMissionControlTimelineStartErrorAlreadyAtEnd = 10003,

/**
 *  Can't start a timeline which was already running.
 */
DJIMissionControlTimelineStartErrorAlreadyRunning = 10004,

/**
 *  Can't start a paused timeline. Need to call resume instead.
 */
DJIMissionControlTimelineStartErrorTimelineIsPaused = 10005,

/**
 *  Can't pause a timeline which is not running.
 */
DJIMissionControlTimelinePauseErrorNotRunning = 10006,

//Doc key: DJIMissionControlError_TimelinePauseErrorAlreadyPaused
/**
 *  Can't pause a timeline which is already paused.
 */
DJIMissionControlTimelinePauseErrorAlreadyPaused = 10007,

//Doc key: DJIMissionControlError_TimelineResumeErrorNotRunning
/**
 *  Can't resume a timeline which is not running.
 */
DJIMissionControlTimelineResumeErrorNotRunning = 10008,

/**
 *  Can't resume a timeline which is not paused.
 */
DJIMissionControlTimelineResumeErrorNotPaused = 10009,

/**
 *  Can't stop a timeline which is not running.
 */
DJIMissionControlTimelineStopErrorNotRunning = 10010,

/**
 *  Element passed does not conform to DJIMissionControlTimelineElement protocol
 */
DJIMissionControlElementErrorProtocolNotConform = 20001,

/**
 *  The element passed is a mission without a valid operator.
 */
DJIMissionControlElementErrorInvalidMissionOperator = 20002,

/**
 *  IsPausable was set to yes but the item doesn't implement pauseRun and/or
 *  resumeRun methods.
 */
DJIMissionControlElementErrorInvalidPauseImplementation = 20003

**Comment by kaizensoze** [comment]
Ok thanks for the info, that helps.
