### ISSUE TITLE
Execution of this process has timed out

### ISSUE THREAD

**Issue by kaizensoze** [dji-sdk/Mobile-SDK-iOS#175]
Connecting directly to a Mavic Pro and simply trying to do a single gimbal attitude action using the timeline, but getting the following error in the mission control listener:

`Execution of this process has timed out(code:-1003)`

I call `DJISDKManager.startConnectionToProduct()` so there shouldn't be any misconception about using a bridge app. 

Any ideas?

**Comment by dbaldwin** [comment]
Just to reiterate what @kaizensoze is seeing we are repeatedly seeing this in DronePan and DroneBlocks. This is from a user today who was shooting a pano. At the very start of the mission his Mavic Pro sent the gimbal to +30 and before any other actions could execute he received the error below:

![img_6326](https://user-images.githubusercontent.com/38339/31365793-0d62df46-ad33-11e7-92e1-4ec6d6d47e05.PNG)

This appears to be much worse in SDK 4.3.1 than 4.2.

**Comment by aayers-agrible** [comment]
Just to bump this issue. We are also seeing this issue in Pocket Drone Control. We've had several testers report this issue. We are still using SDK 4.2.2, and based on what @dbaldwin says I don't think I'll try updating. 

I only see / have bug reports for this error happening immediately at the beginning of our missions, when the drone should be taking off. We also set the camera's aspect ratio at this point.

**Comment by andrew-barinov-dji** [comment]
Thank you for reporting this issue, the details provided were very helpful. I'm able to reproduce this on my side, just want to confirm several pieces of information:

When you receive the error, can you try adjust the pitch to 1 or 2 degrees below 30 and see what happens? If the error happens again, keep adjusting downward, do you ever stop getting the error? I'm seeing ~22.6 to be the boundary on my side, let me know if you see something similar.

When the error occurs, can you log the value of the latest `DJIGimbalState` `isPitchAtStop` and see if it is true?

**Comment by lijia6745** [comment]
@kaizensoze  How about this issue state.
Did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
