### ISSUE TITLE
Swift sample code compiles but does not connect to Phantom 4

### ISSUE THREAD

**Issue by FarhadG** [dji-sdk/Mobile-SDK-iOS#176]
I've successfully compiled the Swift sample code onto my iPhone 6S, however, the `status` continues to remain in `Trying to connect`. I'm able to connect with the DJI app itself so it must be something to do with the code or some configuration. Any tips? Also, is there any way to connect to the Phantom with the iOS simulator or is it necessary to compile onto the device to be able to connect to the remote?

- OSX: El Capitan 10.11.6
- iPhone 6S with iOS 11.0.2
- XCode 8.2

**Comment by FarhadG** [comment]
So I followed the same steps for the ObjectiveC sample code and it works without an issue. So, I'm assuming that there's a step missing with the Swift sample code in the documentation or that the repo has an issue?

**Comment by PandaraWen** [comment]
Have you already set your `DJISDKAppKey` in the demo project's info.plist file? @FarhadG

**Comment by FarhadG** [comment]
Thanks for the response, @PandaraWen. Yes, I did. I followed the same exact steps for both versions (ObjectiveC and Swift) and only the Objective C one was able to connect.

**Comment by zoemcateedji** [comment]
The only time I had a connection issue was when I ran multiple DJI apps on a device, and was switching around.  I found that if I unplugged the lightening cable, and plugged it back in with the Swift app in focus, I could connect again with the Swift sample code for 3.4.1
(I do use xcode 9, btw... I can't see what we are doing differently otherwise)

**Comment by ericvelazquez** [comment]
Hi!

I am having the same problem using the DJI Spark. When I use the Objective C sample code the connection works but it doesn't work with the swift sample code. Did you find why?

Thank you!!

**Comment by dji-dev** [comment]
Hi @FarhadG , have you resolved your issue with the latest DJI SDK version? If not, please help to report your issue to dev@dji.com, as it's our official channel for developers to request  DJI SDK support now.
