### ISSUE TITLE
Virtual Stick controls on Mavic Pro

### ISSUE THREAD

**Issue by ericgouldbear** [dji-sdk/Mobile-SDK-iOS#177]
We're able to use Virtual Stick controls on Mavic Pro while iPhone is connected over USB via center connector of physical controller ... but not over WiFi connection to drone.  Over WiFi, we're able to control take-off, landing, RTH, and gimbal; but NOT virtual sticks.  DJI Go virtual sticks work over WiFi on Mavic Pro (and our app controls Spark fine over WiFi), so we must be missing something.  Please advise.  Thanks!

**Comment by XietongLU** [comment]
When using WiFi, please use Mobile Remote Controller (DJIMobileRemoteController) instead.
