### ISSUE TITLE
Mission activetrack and tapfly cannot stop!

### ISSUE THREAD

**Issue by Sunnyyoung** [dji-sdk/Mobile-SDK-iOS#178]
## Description

When start an active track mission or tap fly mission and then trying to stop them, the completionBlock returns `nil` but nothing happened, the mission still running.

## Reproduce

1. Clone the demo [iOS-Phantom4Missions](https://github.com/DJI-Mobile-SDK-Tutorials/iOS-Phantom4Missions)
2. Build and run, start the active track mission
3. Tap the stop button, completionBlock was called with `nil` error but nothing happened

BTW, I've tested on the old version SDK (4.1.1), which working properly.

## Environment

- SDK Version: 4.3.1 and 4.3.2
- Xcode Version: 9.0.1 (9A1004)
- iOS Version: 10.3.3
- macOS Version: 10.13 (17A405)
- Devices: iPad mini 4, iPhone 7, Phantom4A, Mavic Pro

**Comment by zoemcateedji** [comment]
Thanks for letting us know - we will definitely look into it.

**Comment by zoemcateedji** [comment]
This will be fixed in our next release.  Thanks again for letting us know.
