### ISSUE TITLE
Call registerAppWithDelegate crash on iOS 9.3.5

### ISSUE THREAD

**Issue by Sunnyyoung** [dji-sdk/Mobile-SDK-iOS#179]
## Description

After called `registerAppWithDelegate` will lead to crash on iOS 9.3.5, but iOS 11 not.

BTW, I've tested with old version SDK(4.1.1), it works fine.

## Screenshot

![image](https://user-images.githubusercontent.com/5926284/31752808-8c4acf7e-b4bf-11e7-8ff9-2b3702205e1b.png)

## Environment

- Project: Official demo, Personal project
- SDK Version: 4.3.2
- Xcode Version: Version 9.0.1 (9A1004)
- iOS Version: 9.3.5
- macOS Version: 10.13 (17A405)
- Devices: iPad mini 1

**Comment by MeteC** [comment]
Me too - also see #169

**Comment by XietongLU** [comment]
Contacted @Sunnyyoung and issue resloved.
