### ISSUE TITLE
The type of angularVelocity in DJIHotpointMission may be unreasonable

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#181]
## Description

Hi, I found some problem about the type of property `angularVelocity` in `DJIHotpointMission`  which is `Int`. And I think it is unreasonable, also would lead to some different behaviors compared with DJI Go4.

## Detail

Currently, I can get the maximum available radius through `DJIHotpointMaxRadius `, which is 500 meter.

Then I use `maxAngularVelocityForRadius:` of `DJIHotpointMissionOperator` and get the max angular velocity of radius `498`, which is **1** degree/s, whose corresponding linear velocity is **8.69** meter/s, different from DJI Go4, which is **10** meter/s:

![unadjustednonraw_thumb_a20](https://user-images.githubusercontent.com/3304493/31770848-474adad8-b49f-11e7-907b-ee67c75cf42a.jpg)

An according to the type of `angularVelocity`, is that mean I can only set the angular velocity to **0** or **1** with radius of `498` meters?

So how DJI Go4 deal with the linear velocity that user would continuously change in `Point of interest` (hotpoint mission) mode?

## Environment

* Platform: iOS
* SDK Version: 4.3.2
* iOS Device: iPhone6
* iOS Version: iOS 11.1 beta
* Xcode Version: 9.1 beta

**Comment by XietongLU** [comment]
We designed the interface as int to work around a minor defect in firmware. We will review the issue again and make a tradeoff.

**Comment by PandaraWen** [comment]
@XietongLU Thanks a lot~I would keep following this issue

**Comment by dji-dev** [comment]
Hi @PandaraWen , the type of the angularVelocity in DJIHotpointMission is float now. Please use the latest SDK version and try again. 

If you still have more issues related to DJI SDK, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.
