### ISSUE TITLE
Mac-mini:ObjcSampleCode qizhang$ pod install Analyzing dependencies Downloading dependencies Installing DJI-SDK-iOS (4.3.2) Generating Pods project Abort trap: 6

### ISSUE THREAD

**Issue by MaxwellQi** [dji-sdk/Mobile-SDK-iOS#183]
#### Is this issue about bugs or crash issues of DJI iOS SDK and Sample Code?

XCode 9.0 :  

Mac-mini:ObjcSampleCode qizhang$ pod install
Analyzing dependencies
Downloading dependencies
Installing DJI-SDK-iOS (4.3.2)
Generating Pods project
Abort trap: 6

#### Is this issue about DJI Android SDK and Sample Code?

Then this is the wrong place, please refer to the Mobile-SDK-Android Github: <https://github.com/dji-sdk/Mobile-SDK-Android/issues>

**Comment by XietongLU** [comment]
Please refer to http://www.jianshu.com/p/f8e7a0d5a2d8.
