### ISSUE TITLE
ActiveTrack - Get distance from object to Drone

### ISSUE THREAD

**Issue by guicolares** [dji-sdk/Mobile-SDK-iOS#189]
Hi Everyone, 

Is it possible get the distance from object using the activeTrack mode ? 

Thanks

**Comment by lijia6745** [comment]
It‘s not support now.

**Comment by dji-dev** [comment]
Hi @guicolares, if you still have more issues related to DJI SDK, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.
