### ISSUE TITLE
Error loading mission with SDK 4.3.2 and Spark

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-SDK-iOS#192]
We've been testing many different parameters to load a waypoint mission into DJI Spark. Is this possible with SDK 4.3.2? We keep seeing error code -5024 with a basic waypoint mission and have tried using the timeline operator and waypoint mission operator.

![img_0281](https://user-images.githubusercontent.com/38339/33387823-f00ac560-d4f3-11e7-8246-90b43ab52ad5.PNG)

![img_0282](https://user-images.githubusercontent.com/38339/33387824-f01b20fe-d4f3-11e7-81ff-1b373f3e2d74.PNG)

Apparently error -5024 means:

/**
     *  Command can not be executed. This is sometimes because commands are sent too
     *  frequently.
     */
DJISDKMissionErrorCommandCanNotExecute = -5024L

Is this a known issue and do you have any suggestions on how to work around it?

Will there be Spark support in SDK 4.4?

Thanks.

**Comment by PandaraWen** [comment]
It seems Spark does not support kinds of missions.

**Comment by mgiachetti** [comment]
+1. It would be great to have support for this.
Meanwhile, Is there a workaround?
I need to send the spark to an specific location programmatically (a single location).
Using virtual sticks api is the only solution I found, but is there a simpler one?

**Comment by priyankaparihar** [comment]
I am getting the same issue with Android and DJI Spark using DJI SDK 4.5.1. Anyone who has got any workaround ?

**Comment by dbaldwin** [comment]
Dear DJI, are there plans to support Spark in the Mobile SDK? We just tested 4.6.1 and still having problems. See the attached screen from DroneBlocks with SDK 4.6.1 and Spark. Can you please provide us any info one way or another? Thank you.

![img_0304](https://user-images.githubusercontent.com/38339/42471720-66b82f4c-8384-11e8-9a49-5513fc66c8e6.PNG)

**Comment by zoemcateedji** [comment]
Dennis,
Could you try say 20 feet at 2 mph?  (I am wondering if there are some flight limitations being hit for distance or speed.)

Thanks!

**Comment by dbaldwin** [comment]
@zoemcateedji thanks for chiming in. Changing the block to 20 ft and 5 mph did not work. I only did 5 mph (2.2 m/s) because from previous testing older versions of the SDK did not allow us to go any slower than this....and we've set a limit in DroneBlocks to a minimum of 5 mph.

**Comment by dbaldwin** [comment]
Please ignore my last comment. We had updated with the latest podfile for 4.6.1 but when we compiled it used SDK 4.5. After cleaning the project and recompiling we were able to successfully get waypoints working with Spark. Thank you DJI. Keep up the great work.
