### ISSUE TITLE
Mission Control Error: Distance between two adjacent waypoint is too close

### ISSUE THREAD

**Issue by jayvenn** [dji-sdk/Mobile-SDK-iOS#195]
To recreate the problem:
```
let missionControl = DJISDKManager.missionControl()!
let waypointMission = DJIMutableWaypointMission()
let waypoint1 = DJIWaypoint(coordinate: CLLocationCoordinate2D(latitude: 1.291104532778905, longitude: 103.78665017619217))
let waypoint2 = DJIWaypoint(coordinate: CLLocationCoordinate2D(latitude: 1.2911059258671478, longitude: 103.78664950017712))

waypointMission.add(waypoint1)
waypointMission.add(waypoint2)

let mission = DJIWaypointMission(mission: waypointMission)
missionControl.scheduleElement(mission)
missionControl.startTimeline()
```

DJI SDK 4.3.2
iPhone X
iOS 11.1.1
Mavic Pro

**Comment by wenqianqiao** [comment]
Hi Jayvenn,

If the two waypoints are too close, then we would restrict the update. The distance must be larger than 0.5 meter in space.

**Comment by jayvenn** [comment]
Hi Wenqiao,

Is there any way for us to override this?

We are trying to re-shoot a selected number of photos with geo location.
This means that sometimes the photos will have the same longitude and
latitude, but with the only difference being the gimbal pitch.

Hope to hear your thoughts on this matter.

**Comment by jayvenn** [comment]
P.S
Is there a way to check if the waypoint mission has two waypoints that are
too close using the iOS DJI SDK before starting the Waypoint Mission?

**Comment by wenqianqiao** [comment]
It is a restriction from the firmware. Feel sorry that we could do nothing on that.

**Comment by jayvenn** [comment]
In that case, is there a way in which we can check if the Waypoint Mission is valid before starting it?

**Comment by XietongLU** [comment]
@jayvenn It can be implemented by developers and we will consider to support it in the future version.

**Comment by jayvenn** [comment]
@XietongLU Thanks for taking the time out of your day to respond to this issue. I really appreciate it.

For clarification:
Is this issue only for adjacent waypoints?
What about two waypoints with different altitude and the distance between them is <= 0.5?

**Comment by wenqianqiao** [comment]
hi Jayvenn,

The two adjacent waypoints distance must be larger than the 0.5 meter in space. (Noted the next waypoint of the last waypoint is the first waypoint. )
Any adjacent waypoints with different altitude but same coordinate would be acceptable only under the circumstance the spatial distance is larger than 0.5
