### ISSUE TITLE
Record flight path and fly it again automatically

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-SDK-iOS#197]
Hi,
I know this is a hard question but is there a way to record the flight path of the drone and then ask it to fly over and over that same path automatically? 
I know the DJI App can do that, but I can't figure out how to do the same using the SDK.

Thanks

**Comment by aksh1t** [comment]
One simple way I can think of is to keep on listening to the aircraft location and altitude and save those locations. Once you have an array of locations, you can "replay" them by feeding them into a waypoint mission and running that. However, I think you will quickly run into a maximum number of waypoints reach if you sample the aircraft locations too often.

**Comment by Daxito** [comment]
@aksh1t Thats is right, and also, each waypoint has to be 5M apart, at least.
