### ISSUE TITLE
~20% of the time, `DJIAircraft.remoteController` incorrectly is `nil`.

### ISSUE THREAD

**Issue by huntermonk** [dji-sdk/Mobile-SDK-iOS#199]
**-  Description of the issues.**
A significant percentage of the time, the `DJIBaseProduct` received in the `productConnected` delegate method of `DJISDKManagerDelegate` has a nil `remoteController`, even if you're connected via remote controller.

That should never happen.

**-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)**

1. Create an app that runs this controller.
``` swift
class DJIConnector: NSObject, DJISDKManagerDelegate {
    
    override init() {
        super.init()
        DJISDKManager.registerApp(with: self)
    }
    
    func appRegisteredWithError(_ error: Error?) {
        // Ignoring for purposes of example.
    }
    
    func productConnected(_ product: DJIBaseProduct?) {
        guard let product = product as? DJIAircraft else {
            return
        }
        
        // Incorrectly prints `true` when connected via remote controller
        // ~20% of the time.
        print(product.remoteController == nil)
    }
}
```

2. Power up remote controller.
3. Power up Spark.
4. Confirm Spark is connected to remote controller because a. Spark's Wi-Fi network is not available, and b. the light at the top-left of the remote controller is white.
5. Run app specified above several times.
6. Note that a significant percentage of the time, `true` will be printed to the log even though you've been connected to the remote controller and not the Spark's Wi-Fi network.

**-  Crash logs (If you can find it, it would be very helpful)**
Not crashing.

**-  DJI iOS SDK version you are using (Like iOS SDK 3.4, etc)**
`4.3.1`

**-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)**
Spark

**-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)**
iOS 11.2

**-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)**
iPhone X

**-  Xcode version you are using (Like Xcode 7.0)**
Xcode 9.2

**Comment by lijia6745** [comment]
Did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
