### ISSUE TITLE
Spark video quality bad when connected via remote controller

### ISSUE THREAD

**Issue by huntermonk** [dji-sdk/Mobile-SDK-iOS#200]
**-  Description of the issues.**
The video quality is poor when connected to the remote controller and Spark. It cuts out often, or freezes a frame for several seconds at a time. This happens even when all three devices (Spark, remote controller, iPhone) are all next to each other.

The video quality when connected directly from iPhone to Spark is fine.

**-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)**
Not applicable. I can add more details if needed.

**-  Crash logs (If you can find it, it would be very helpful)**
Not crashing.

**-  DJI iOS SDK version you are using (Like iOS SDK 3.4, etc)**
`4.3.1`

**-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)**
Spark

**-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)**
iOS 11.2

**-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)**
iPhone X

**-  Xcode version you are using (Like Xcode 7.0)**
Xcode 9.2

**Comment by lijia6745** [comment]
Did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
