### ISSUE TITLE
Not able to register as developer

### ISSUE THREAD

**Issue by EvgeniyGushchin** [dji-sdk/Mobile-SDK-iOS#202]
Sorry for posting this issue here. 
I'd like to post it on dev forum but to do this I should have developer account, but I can't register as developer.

On the third step of registration (Check Information and Submit) I always get `{"status":"500","error":"Internal Server Error"}` as response on submit request.

Any help are welcome!

If you can, please repost this issue to forum http://forum.dev.dji.com/en

**Comment by XietongLU** [comment]
Thanks for reporting this. We will fix it as soon as possible.

**Comment by blacklime** [comment]
I too am seeing this issue; the `submit` button remains `disabled` (see screenshot).


![dji_developer_apply](https://user-images.githubusercontent.com/30208414/36137401-25787e64-10e9-11e8-8531-b29ea9acd684.png)

**Comment by oliverou** [comment]
Hi @blacklime, thanks for the feedbacks! We have addressed this issue and will get back to you once we have made any progress. Sorry for the inconvenient.

**Comment by dji-dev** [comment]
Hi @blacklime , the submit button issue should be fixed, please try again. If you have more issues, please contact dev@dji.com for help, as it's our official support channel now.
