### ISSUE TITLE
DJIAircraftYawAction Timeline Error -4003 Still Exists in SDK 4.4

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-SDK-iOS#204]
For the past several SDK releases we've continued to see the following SDK error when executing DJIAircraftYawAction:

"Aircraft cannot execute virtual stick commands. (code: -4003)"

This happens with Mavic Pro and Phantom 4 using SDK 4.4. This causes our apps to not function properly (DroneBlocks and DronePan). Click the link below to see a 10s field test of DronePan with Mavic Pro and the -4003 error:

https://www.dropbox.com/s/rnokmsktyzrygyd/dji_error_4003.MOV?dl=0

This bug is intermittent. Sometimes it will do several yaw sequences before throwing the error and other times it will error during the first yaw action. We've taken suggestions from the DJI dev team to enable virtual stick mode before beginning the timeline mission. You can see that here:

https://github.com/dbaldwin/DronePan-Swift/blob/sdk-4.4.0/DronePan-Swift/CameraViewController.swift#L245-L256

How can we overcome this? It's been plaguing us ever since SDK 4.0 and timeline missions were released. Any tips or tricks would be greatly appreciated.

Thank you.

**Comment by Sunnyyoung** [comment]
Same issue here.☹️

**Comment by hdrpano** [comment]
-(void)enableVirtualStick {
    DJIFlightController *flightController = [self fetchFlightController];
    [flightController setYawControlMode:DJIVirtualStickYawControlModeAngle];
    [flightController setRollPitchCoordinateSystem:DJIVirtualStickFlightCoordinateSystemGround];
    [flightController setVirtualStickModeEnabled:YES withCompletion:^(NSError * _Nullable error) {
        if (error) {
            NSLog(@"Enable VirtualStickControlMode Failed");
        }
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            [self executeVirtualStickControl];
        });
    }];
}

After Pano is made

DJIFlightController *flightController = [self fetchFlightController];
    [flightController setVirtualStickModeEnabled:NO withCompletion:^(NSError * _Nullable error) {
        if (error) {
            NSLog(@"Disable VirtualStickControlMode Failed");
            DJIFlightController *flightController = [self fetchFlightController];
            [flightController setVirtualStickModeEnabled:NO withCompletion:nil];
        }
    }];

**Comment by andrew-barinov-dji** [comment]
@dbaldwin hi Dennis, have you tried the v4.5 rev of the SDK? We've added a fix to the issue. Please let us know if you see it again. Thanks!

**Comment by andrewjl** [comment]
@dbaldwin Hi Dennis, closing this for now. Please feel free to reach out to us if you see this happening again.

**Comment by dbaldwin** [comment]
@andrew-barinov-dji so far so good in our testing. I've yet to see this error in 4.5 and 4.5.1 for iOS. I'm closing this for now. Thank you so much and keep up the great work.
