### ISSUE TITLE
Imprecise heading for Waypoint Mission due to DJIWaypoint's Heading type Int property value in DJI SDK 4.4

### ISSUE THREAD

**Issue by jayvenn** [dji-sdk/Mobile-SDK-iOS#205]
Issue Description:
The flightController(_:didUpdate:) method's fc.compass?.heading property value is of type Double.
DJIWaypoint's heading property value has changed from type Double to type Int (DJI iOS SDK 4.3.2 to 4.4).
Hence, this issue causes the heading of the drone to be inaccurate during Waypoint Mission.
Any suggestion would be greatly appreciated as our function highly depends on the precision of the drone's heading. Thanks.

-----
DJI IOS SDK: 4.4
Xcode: 9.2
iOS: 11

**Comment by dji-dev** [comment]
Hi @jayvenn , the type of the heading property is define in the firmware not in SDK, it's `int` type now. We cannot change it. If you still have more issues related to DJI SDK, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.
