### ISSUE TITLE
Test with DJI PC Simulator ? 

### ISSUE THREAD

**Issue by guicolares** [dji-sdk/Mobile-SDK-iOS#21]
Hi, 

Is possible test my app using the DJI PC Simulator ? 

Thanks.

**Comment by oliverou** [comment]
Hi, please check this DJI PC Simulator tutorial: http://developer.dji.com/mobile-sdk/get-started/DJI-PC-Simulator/. Also you can check the GSDemo tutorial for help too: https://github.com/DJI-Mobile-SDK/iOS-GSDemo.

**Comment by dji-dev** [comment]
Since this issue is solved, close it now.
