### ISSUE TITLE
Which coordinate system DJI using ?

### ISSUE THREAD

**Issue by gstream** [dji-sdk/Mobile-SDK-iOS#211]
I want to know which coordinate system (just like WGS84, NAD83, etc ) DJI devices are using. 

Any answer would be appreciated.

Thanks

**Comment by oliverou** [comment]
@gstream, DJI Products use WGS84 as the coordinate system.

**Comment by linktekc** [comment]
@oliverou , thanks for your answer. Is there any document for that ?

**Comment by gstream** [comment]
@oliverou , thanks for your reply. Is there any documentation that I can refer ?

**Comment by oliverou** [comment]
Hi @gstream @linktekc , we just update the FAQ doc on DJI Developer Website, please check this link: [Does DJI products use WGS84 or NAD83 as the coordinate system?](https://developer.dji.com/mobile-sdk/documentation/faq/index.html#does-dji-products-use-wgs84-or-nad83-as-the-coordinate-system)

**Comment by gstream** [comment]
@oliverou , thanks for your answer.

**Comment by oliverou** [comment]
@gstream no problem, just fix the typo. Please help to check the updated link.
