### ISSUE TITLE
DJICamera getLensInformation() fails if called too soon after Camera connect

### ISSUE THREAD

**Issue by dokazaki** [dji-sdk/Mobile-SDK-iOS#213]
Issue description:

- Upon receiving the SDK component delegate notification that the camera has connected, I immediately use the DJIAircraft.camera reference and call the method: isInterchangeableLensSupported(), and when it returns true, I call the method: getLensInformation() on the same camera reference and it times out with this error:

>     Error Domain=DJISDKErrorDomain Code=-1003 "Execution of this process has timed out(code:-1003)" UserInfo={NSLocalizedDescription=Execution of this process has timed out(code:-1003)}

- When I run on the Xcode iOS sim over the DJI bridge, the call to getLensInformation() works sometimes
- When I compile and run on the iPad, it always fails with the timeout error

Context:

- DJI iOS SDK 4.4
- DJI Inspire 1 Pro running firmware 1.11.01.50, X5 camera with 15mm lens
- iPad Pro 9.7" running iOS 10.3.3
- Latest DJI Bridge running on iPad mini 4 running iOS 11.2.1 (for iOS Sim case)
- Xcode 8.3.3, Swift 3

**Comment by XietongLU** [comment]
Do you try to add some delay after the camera has connected? A more reliable way is to use DJIKeyedManager. You can get and listen to the key even the value is not ready yet.

**Comment by hdrpano** [comment]
Is there an example code for Swift to get this information with the DJIKeyedManager? The output seems to be an NSString

**Comment by dokazaki** [comment]
@XietongLU - I have an event-driven async app, so arbitrary delays are very undesirable. Are you saying that the SDK product and component delegates are more unreliable than the DJIKey subclass CameraKey? How would a listener on the CameraKey get any more reliable access to the Camera attributes than the instantiated Camera under the Product instance? The API looks the same, so wouldn't I get the same error using the CameraKey?

I ended up moving the camera lens query code out of the delegate, which publishes to an Rx Swift Observer, and into a subscriber, which appears to give enough delay for the Camera API to fully initialize.

This is still a bug on the Camera API.

**Comment by XietongLU** [comment]
@dokazaki Please use the get alone with the start listen.

**Comment by dokazaki** [comment]
@XietongLU You mean without the completion block? Don't think it will work - it will pull from cache is HW not available which may be incorrect. My software must be robust to detecting power cycle of Inspire1 to change gimbal and or lens, it also must be robust to having the lightning cable unplugged to import images from the camera, then plugged back into the RC and in real-time detect the components coming back online with the camera config from the hardware - cannot utilize cached values as user can change lens at-will at anytime on the ground.

**Comment by XietongLU** [comment]
I mean you should do both get and start listen. code will look like: 
DJIKeyManager *manager = [DJISDKManager keyManager]; 
DJICameraKey *key = [DJICameraKey keyWithParam:DJICameraParamLensInformation];
[manager startListeningForChangesOnKey:key withListener:self andUpdateBlock:^(DJIKeyedValue * _Nullable oldValue, DJIKeyedValue * _Nullable newValue) { ... }
[manager getValueForKey:key withCompletion:^(DJIKeyedValue * _Nullable value, NSError * _Nullable error) {...}

**Comment by dokazaki** [comment]
@XietongLU - So what does the listener do when the getter fails? Does the SDK automatically poll the getters when Listener subscription is setup to watch the key attribute that is a getter (not pushed)? If this is case, why would I need to execute the getter after setting up the listener?

BTW, I got an Inspire 2 and I don't have all the connectivity and access problems that I have with the Inspire 1 pro. Also, I am running my code on iOS 11.2.2 since all the users have been upgrading their iPads. Unfortunately many of them still have Inspire 1 pro's...

**Comment by XietongLU** [comment]
@dokazaki the listener will ensure you receive the change of the value (including the change from nil to nonnull). SDK has different strategies to decide if it needs to pull the getter. You should call a getter after the listener because you won't receive the notification until the value changes. Getter can ensure you to get the value if it exists.

**Comment by dokazaki** [comment]
@XietongLU But if the getter errors out as it has been with the Inspire 1, then there is no value change, so when does the listener receive notification under what mechanism, since the problem is the failure of the getter. Is this actually a problem with the Inspire 1 firmware? Because I don't have such problems with the Inspire 2.

**Comment by XietongLU** [comment]
@dokazaki first, a getter in SDK doesn't really mean it has to be a getter in underlying mechanism. Even it is a getter, SDK's listener will retry if it fails for the first time.

**Comment by dokazaki** [comment]
@XietongLU Thanks for the clarification. Meanwhile, I took a different route to solve the issue, but will revisit wiring up KeyManager for non-delegate and non-listener status in a bit.

Closing this issue as solved.
