### ISSUE TITLE
DJIFlightControllerState.flightMode not reported correctly for Inspire 1 firmware 1.11.01.50

### ISSUE THREAD

**Issue by dokazaki** [dji-sdk/Mobile-SDK-iOS#216]
DJIFlightControllerState.flightMode does not report the correct state for Inspire 1 running the latest firmware 1.11.01.50. When the RC switch is moved to the A position, the flightMode remains in .gpsAtti mode and does not transition to .atti mode.

However on an Inspire 1 running firmware 1.10.01.40, when the RC switch is moved to the A position, the flightMode does transition correctly to the .atti mode. Also, on an Inspire 2, when the RC switch is moved to the A position, the flightMode does transition to the .atti mode

Running on:
-  DJI iOS SDK version 4.4
-  DJI Product: Inspire 1 (firmware 1.11.01.50)
-  iOS system version: 11.2.2, 11.1
-  iOS device type: iPad mini 4 (on 11.2.2), iPad pro 10.5" (on 11.1)
-  Xcode version: 8.3.3

**Comment by XietongLU** [comment]
Please check if MultipleFlightModeEnabled is enabled.

**Comment by dokazaki** [comment]
@XietongLU ok, will check - should this mode be enabled or disabled?

**Comment by zoemcateedji** [comment]
It needs to be enabled. 
https://developer.dji.com/api-reference/ios-api/Components/IntelligentFlightAssistant/DJIIntelligentFlightAssistant.html?search=multipleflightmodeenabled&i=0&#djiflightcontroller_setmultipleflightmodeenabled_inline

You may want to test with the 4.4 Sample App - it includes a quick test for this. (Remote Controller, RC hardware state.  Move the toggle and you should see the widget highlight move through F-A-P if MultipleFlightModeEnabled is enabled)

**Comment by dokazaki** [comment]
The documentation is out of date. The setMultipleFlightModeEnabled method is under the DJIFlightController class, not the DJIIntelligentFlightAssistant class. Anyway, the call fails with:
> {NSLocalizedDescription=Setting parameters operation failed.(code:-1007)}

Also, DJI Go fails to set this, too - I try to slide it to enabled, but it always resets to disabled.

My software has always worked fine without this setting. I can detect RC switch position accurately for Inspire1 pro, Inspire2, Phantom 4 Pro. All of them behave correctly as if MultipleFlightModeEnabled, EXCEPT for the Inspire1 pro running Firmware 1.11.01.50.

**Comment by XietongLU** [comment]
Please do a one more check: if the novice mode is enabled.

**Comment by oliverou** [comment]
Hi @dokazaki , thanks for the feedbacks. we just update the API doc of `setMultipleFlightModeEnabled ` in DJIFlightController class, please check: https://developer.dji.com/api-reference/ios-api/Components/FlightController/DJIFlightController.html?search=multipleflig&i=0&#djiflightcontroller_setmultipleflightmodeenabled_inline

**Comment by dokazaki** [comment]
@XietongLU - Novice mode is disabled.
Also, I updated the iPad to 11.2.5 and updated DJI Go to the latest (fixed for iOS 11.2.5) version and can set the MultipleFlightModeEnabled in DJI Go, and it sticks (doesn't reset). So it looks like firmware 1.11.01.50 is ok.
After I set MultipleFlightModeEnabled in DJI Go, the aircraft behaves as expected.

@oliverou - Thanks for the suggestions, since this mode does not impact the ability to upload and execute Waypoint Missions, I need to check with our product management to see if they prefer to have this mode disabled (so user is unable to switch to AttitudeCtl) for safety reasons.

Does anyone know if there will be an SDK 4.4.1 or 4.5 update to address iOS 11.2.5 issues or were the DJI Go app and DJI Go 4 app issues on iOS 11.2.5 independent of the SDK? Thanks!

**Comment by zoemcateedji** [comment]
independent of the SDK:
The DJI iOS SDK 4.4 release is compatible with iOS 11.2.5, as it was with 11.2.2.  We have seen no critical issues with the SDK and this version of iOS.  Our developer community does not need to ask their customer base to avoid loading 11.2.5.
 
The DJI team is continuing to work with Apple in regards to the MFI issue with multiple applications sharing an accessory (i.e. DJI remote controller).

**Comment by dokazaki** [comment]
Thanks everyone for your assistance and information. I'll go ahead and close this issue as not being an actual bug.
