### ISSUE TITLE
Vision Positioning System

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-SDK-iOS#217]
Hi,
How can I add Vision Positioning System to my App? Is this possible?
Thanks

**Comment by XietongLU** [comment]
Please check https://developer.dji.com/api-reference/ios-api/Components/IntelligentFlightAssistant/DJIIntelligentFlightAssistant.html#djiintelligentflightassistant_setvisionpositioningenabled_inline

**Comment by Daxito** [comment]
@XietongLU So is Vision Positioning System =Vision Assisted Positioning.
If so, how do I get the number it returns? I can see how to enable/disable, but need the actual value
