### ISSUE TITLE
DJI SDK : 4.4 - DJISDKManager.registerApp() crashes app on some devices

### ISSUE THREAD

**Issue by pavanSaberjack** [dji-sdk/Mobile-SDK-iOS#231]
-  Description of the issues.
DJISDKManager.registerApp() ends up in crashing.

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
App crashes when we try to register the app using **DJISDKManager.registerApp()**  method

-  DJI iOS SDK version
DJI SDK 4.4

-  DJI Product 
Mavic Pro

-  iOS system version 
iOS 11.2.6

-  iOS device type you are using 
iPad 5th generation

-  Xcode version you are using
Xcode Version 9.2 (9C40b)

**Comment by justinmiller62** [comment]
I saw this once, and once only with no drone attached, using the same iOS system and a iPad mini 4. No reliable method to reproduce on my end.

**Comment by zoemcateedji** [comment]
We have addressed this intermittent issue in the next release.  We agree there was no reliable repro!

**Comment by zoemcateedji** [comment]
The development team would like to see your logs.  Could you please email them to dev@dji.com and mention they are for Zoe?  Thanks!

**Comment by dji-dev** [comment]
Hi @pavanSaberjack , if you still have more issues related to using DJI SDK, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.
