### ISSUE TITLE
HotpointAction TimelineEvent finished is called on emergency procedures.

### ISSUE THREAD

**Issue by joshpuente** [dji-sdk/Mobile-SDK-iOS#237]
-  Description 
Within the DJIMissionControlTimelineEvent listener, the Hotpoint event finished condition is trigger when an emergency procedure if fired on the drone (ie. Land now or go home).

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
1. Execute a hotpoint mission via the DJITimelineMissionControl.
2. Bring the drone home or land now mid-mission.
3. Observe that the finished event is triggered.

-  DJI iOS SDK version you are using (Like iOS SDK 3.4, etc)
4.4

-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
Phantom 4 Pro via the DJI Assistant

-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)
iOS 11

-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)
iPad

-  Xcode version you are using (Like Xcode 7.0)
XCode 9.2

**Comment by aksh1t** [comment]
Thanks for reporting this. Ideally, instead of the finished event you would expect to see the stopped event right?

**Comment by lijia6745** [comment]
Did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
