### ISSUE TITLE
Zenmuse XT @ Position II (SDK Index 1) of M210 Won't Record Video

### ISSUE THREAD

**Issue by shoerob** [dji-sdk/Mobile-SDK-iOS#238]
When the Zenmuse XT is mounted at Position II (sdk index 1) of our M210, it is able to shoot photos, but will not record video.

I've set the camera to recording mode using setMode:withCompletion:. Then, when calling startRecordVideoWithCompletion:, an error is consistently returned:

Error Domain=DJISDKErrorDomain Code=-1003 "Execution of this process has timed out(code:-1003)" UserInfo={NSLocalizedDescription=Execution of this process has timed out(code:-1003)}

Note that when the Zenmuse XT is mounted at Position I (sdk index 0) of our M210, recording works just fine.

SDK Version: 4.4
DJI Product: M210
 - Aircraft Firmware: 01.01.0600
 - Camera Firmware: 01.06.15.84

Device: iPad Pro w/ iOS 11.0.3
Xcode: 9.2 & 9.3

**Comment by aksh1t** [comment]
Hi shoerob, by default the controlling gimbal is position 0 (marked I on the drone, portside). If you want to control the starboard camera using RC controls, you need to change the controlling gimbal parameter to 1 (marked II on the drone, starboard). You can do that by this method:

https://developer.dji.com/api-reference/ios-api/Components/RemoteController/DJIRemoteController.html#djiremotecontroller_setcontrollinggimbalindex_inline

**Comment by shoerob** [comment]
I just tested DJISDK 4.5, and the startRecordVideoWithCompletion: function appears to be working properly now.
