### ISSUE TITLE
The swift sample is missing a file....FlightHubController.swift

### ISSUE THREAD

**Issue by tfannon** [dji-sdk/Mobile-SDK-iOS#246]
When I go to compile the swift code, I get the following:
<unknown>:0: error: no such file or directory: '/Users/tommy/Dev/DJI/Mobile-SDK-iOS-master/Sample Code/SwiftSampleCode/SDK Swift Sample/FlightHub/FlightHubViewController.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

I am able to work around it by manually editing the .xcodeproj and deleting all references to FlightHubViewController.swift

This allows the project to compile, but it does error out when trying to access the FlightHub section in the app.  

Could you please add that missing file?

**Comment by benUrsel** [comment]
I'm having the same issue, have you been able to solve it?

**Comment by zoemcateedji** [comment]
did you do a "pod install" and then open the project from the pod workspace?  (The sample worked for me, so I am wondering if you missed that step).

**Comment by benUrsel** [comment]
I did a "pod install" in the SwiftSampleCode directory, and opened the .xcworkspace file, but get the same error as above.

**Comment by benUrsel** [comment]
Okay great! There was also one other similar error message:

[!] The \`DJISDKSwiftDemo [Release]\` target overrides the \`HEADER_SEARCH_PATHS\` build setting defined in \`Pods/Target Support Files/Pods-DJISDKSwiftDemo/Pods-DJISDKSwiftDemo.release.xcconfig\'. This can lead to problems with the CocoaPods installation
    - Use the \`$(inherited)\` flag, or
    - Remove the build settings from the target.

And both of these were for the Swift File.

**Comment by tfannon** [comment]
It would be nice if your Swift sample achieved  parity with your objective
c one.  There are only about 1/4 of the functions ported.  Some of the
concepts such at the threading cases are not readily obvious to me he they
would be done in Swift

Thank you for the sdk though!
Tommy

**Comment by dji-dev** [comment]
Hi @tfannon @benUrsel , the "FlightHubViewController.swift" file is added to the SwiftSample project. Please pull the latest code and check if it works now. Sorry for the inconvenience.

**Comment by benUrsel** [comment]
Hi @dji-dev the project works for me now. Thanks for the fix.

**Comment by dji-dev** [comment]
Hi @tfannon @benUrsel , glad to hear that the issue is resolved, if you still have more issues related to DJI SDK, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.
