### ISSUE TITLE
TimelineMission keep showing "current mission step is initializing" after rc signal reconnected

### ISSUE THREAD

**Issue by PandaraWen** [dji-sdk/Mobile-SDK-iOS#247]
## Description

When the control signal is weak, the timeline mission (`DJISDKManager.missionControl()?.startTimeline()`) may keep throwing error `current mission step is initializing` when trying to pause or stop it.

## Detail

The reason why I think the signal was **weak** in that outdoor testing, is that the remote controller sometimes would disconnect from drone (the rc signal light turn to 🔴 for a while). 

When the rc reconnected to my drone, the error would be thrown when I try to stop/pause it.

It is hard to simulate the weak signal situation indoor, so I manage to do this by **turning off and on** my rc, when the drone is executing an timeline.

The timeline I used to investigate this problem looks like:

`gimbalAction` -> `gotoAction` -> `hotpointAction(30)` -> `hotpointAction(360)` -> `hotpointAction(30)`

Here are the steps to reproduce this issue indoor:

**1.** Schedule and then start the timeline on the drone;

**2.** Turn off the remote controller when the drone is executing `hotpointAction(360)`;

> Now the drone would keep doing hotpoint, not stopping itself event reaches 360 degree.

**3.** Turn on the remote controller and let it reconnect to drone;

> You would receive `stopError` event in the callback of `missionControl.addListenerToTimelineProgress` method, and the `element` is this hotpointAction, what the error said is `Command cannot be executed.(code:-5024)`.

**4.** Call `missionControl.pauseTimeline`;

> You would receive `pauseError` event in the callback of `missionControl.addListenerToTimelineProgress` method, what the error said is `Current mission step is initializing.(code: -5029)`

**5.** Call `missionControl.stopTimeline`;

> You would receive `stopError` event in the callback of `missionControl.addListenerToTimelineProgress` method, what the error said is `Current mission step is initializing.(code: -5029)`

## One more thing

So now, it seems that I can do not thing but only to call my drone back and restart it. But in fact, I found another interesting thing.

After performing steps above, if examining the `currentState` of `missionControl.hotpointMissionOperator`, it is `readyToStart`.

So I try to let my drone start a hotpoint mission, and it succeeded! (?_?)

Then I stop that new hotpoint mission by `missionControl.hotpointMissionOperator.stopMission`, the most strange thing happen: **My drone continue to execute the next step of the scheduled timeline !** (?_?)

How wonderful it is!?

## Environment

* iOS Device: iPad Pro 9.7 inch
* iOS Version: iOS 11.3.1
* SDK Version: 4.4
* DJI Device: Phantom 4A
* Aircraft Firmware: 01.00.0128
* RC Firmware: 02.01.01.00

**Comment by aksh1t** [comment]
Interesting bug! Thank you for reporting, and for the detailed repro steps. We will look into this.

**Comment by aksh1t** [comment]
We have fixed this bug, will be live in the next SDK update. Thanks again for the detailed steps!

**Comment by PandaraWen** [comment]
@aksh1t Thanks a lot! It that fixup included in SDK 4.5.2?

**Comment by dji-dev** [comment]
Hi @PandaraWen, have you resolved your issue with the latest DJI SDK version? If not, please help to report your issue to dev@dji.com, as it's our official channel for developers to request  DJI SDK support now.
