### ISSUE TITLE
Gimbal mounted upwards on M210 returns wrong YawRelativeToAircraft value

### ISSUE THREAD

**Issue by alexandre-cape** [dji-sdk/Mobile-SDK-iOS#250]
Hi,

I am using an M210 with 3 different cameras mounted upwards : X5S, X4S and XT. When I check the YawRelativeToAircraft value (DJIGimbalParamAttitudeYawRelativeToAircraft), the configurations with X4S and XT returns the opposite of the true value. 

Thank you for your help.

Configuration:
iPad pro with iOS 11.3.1
Mobile SDK 4.5
Xcode 9.3

**Comment by lijia6745** [comment]
This key is float type.
Did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by dji-dev** [comment]
Hi @alexandre-cape , if your issue is not resolved, please help to report your issue to dev@dji.com as it's our official channel to request DJI SDK support now.
