### ISSUE TITLE
GPS accuracy always set to BestForNavigation causing high energy usage

### ISSUE THREAD

**Issue by str11ngfello** [dji-sdk/Mobile-SDK-iOS#252]
The DJISDK provides no way for us to set the CoreLocation location manager desiredAccuracy property.  The Xcode Energy profiler shows very high usage and that the DJISDK sets a location manager (of it's own perhaps) to .BestForNavigation. 

We need to be able to set a lower GPS radio power usage (like .ThreeKilometers) in order to reduce power usage of the device.  This is especially important in the summer heat.  

Please confirm that there is no API to control the setting in DJISDK?  If true, is there a workaround to affect your location manager desired accuracy?  

NOTE:  The way iOS works is that it allows apps to create many location managers where each manager can request it's own desired accuracy.  However, since there's only one GPS radio, the location manager that request the highest level of accuracy (and therefore the most energy usage) wins.  If DJISDK overrides our setting to the max, then we can't control our device power usage.

Thanks in Advance!
Lynn

**Comment by str11ngfello** [comment]
![screen shot 2018-05-11 at 4 28 41 pm](https://user-images.githubusercontent.com/877000/39947672-65ce5e64-5538-11e8-861c-b4a1668849f9.png)

This is a screenshot showing the profiling session.  I've been able to control other SDKs like MapBox, etc.  But DJISDK will cause it's own setting to CoreLocation desiredAccuracy and override our entire app.

**Comment by XietongLU** [comment]
Thanks for the suggestion. Could you provide some references of the other libraries?

**Comment by aksh1t** [comment]
@str11ngfello I was following up on this issue and had a question for you. When you saw the `bestForNavigation` accuracy from the location manager, was the app using any [DJIUXSDK](https://github.com/dji-sdk/Mobile-UXSDK-iOS) widgets (the [compass widget](https://github.com/dji-sdk/Mobile-UXSDK-iOS/blob/master/Framework/DJIUXSDK.framework/Headers/DUXCompassWidget.h) maybe?) or was it only using DJISDK?

**Comment by str11ngfello** [comment]
Hi, 

Funny story actually. I spent about a day slowly pulling out the DJISDK components while profiling to see if I could prevent the DJISDK from kicking into bestForNavigation.  I finally pulled out the checklist widget and it worked!  That is, I prevented DJI from starting the location manager with the high setting.  The next day I went in to show the team and I could not reproduce the fix.  Inspecting the fixes I had made it turned out I celebrated too early.  In my haste I had forgotten to start the SDK with connectToSDK.  

So to sum up: both connectToSDK (to start the SDK) and the checklist widget will cause the DJISDK to start the location manager in bestForNavigation.  I hope this helps.  In Texas, our pilots are facing 100+ degree weather with sunshades and coolers for iOS devices ranging from iPhone 8 to iPhone X to iPad. Even with these hardware cooling measures in place, the higher accuracy setting on the GPS causes us to overheat within 20-30 minutes. We have no need for that high of an accuracy setting so if there's a way that DJI can let us specify lower accuracy, we're talking about a massive improvement in energy usage across our entire suite of apps.

Thanks, and let me know if you have any additional questions.

**Comment by str11ngfello** [comment]
Interesting. Our experience is different.  For example, just calling connectWithSDK in the DJISDK activates this highest GPS setting.  We are in the process of building a few test cases on the latest version of the SDK and I'll report back with results.  Thanks for your help.

**Comment by str11ngfello** [comment]
Here is DJI's latest sample app slightly modified to reproduce the issue. I've also included an Energy Impact performance trace to show the problem.  All I've done to the sample is given permission to the app to use Location Services.  I do not create a CoreLocation manager or ask for updates.  You don't need to connect a drone even.  Just start the app and give it permission to use Location Services.  The energy usage is in the red.  If you run a performance trace for CoreLocation you'll see the DJI SDK has asked for "BestForNavigation" somehow and Apple is reporting this as very high usage.

**Comment by str11ngfello** [comment]
Ah, the attachment is too large.  Do you have a place I can send the zipped project?

**Comment by aksh1t** [comment]
@str11ngfello Could you send a dropbox/github link?

**Comment by str11ngfello** [comment]
Please find the attached zip file here
https://storage.googleapis.com/hangar-ios-builds/DJI-HighEnergyImpact.zip

**Comment by aksh1t** [comment]
Thanks for the project link, that will be very helpful! I will try to dig into this and let you know what comes up.

**Comment by str11ngfello** [comment]
Any update?  Thanks.

**Comment by aksh1t** [comment]
Hi, sorry for being quiet for so long on the thread. I was able to reproduce the high energy usage issue when connecting to the SDK using your sample project and I've passed on this issue to another engineer who knows more about our implementation of the location manager than me. I will let you know what happens.

**Comment by aksh1t** [comment]
Hi again @str11ngfello , just wanted to give you an update about this issue. We've implemented a method on DJISDKManager that will allow developers to control the accuracy of the CLLocationManager that is being used by DJI SDK. This interface will go live with the next version of the SDK.

Thanks for bringing up the issue!

**Comment by dji-dev** [comment]
Hi @str11ngfello, have you resolved your issue with the latest DJI SDK version? If not, please help to report your issue to dev@dji.com, as it's our official channel for developers to request  DJI SDK support now.
