### ISSUE TITLE
Phantom 4 Pro V2.0 & DJISDK 4.5.2 doesn't fetch Flight Controller.

### ISSUE THREAD

**Issue by dshackelford** [dji-sdk/Mobile-SDK-iOS#261]
Running DJISDK 4.5.2
Using Phantom 4 Pro V2.0 (Aircraft firmware 01.00.1000, which DJI GO says is up to date).

When DJISDK protocol method `[productConnected:(DJIBaseProduct* _Nullable) product]` `product.model` is reported as "Mavic Pro".

Additionally, `[ComponentHelper FetchFlightController]` returns `nil` after product is connected.

Is there a timeline for when DJISDK will support P4P_V2.0?

If there is any other information needed to help solve this, let me know.

**Comment by fishstix-airware** [comment]
P4P v2.0 support should come in the iOS SDK v4.6.  v4.5.3 was just released to support an app-store rejection issue.  I have not heard anything concrete on when v4.6 will be released.

**Comment by XietongLU** [comment]
@fishstix-airware coming very soon.

**Comment by tomasbecklin** [comment]
@XietongLU very soon as a week, month or?

**Comment by fishstix-airware** [comment]
@dshackelford @tomasbecklin v4.6 released today and should have P4P v2.0 support
