### ISSUE TITLE
Release Notes Inaccessible

### ISSUE THREAD

**Issue by adolfo** [dji-sdk/Mobile-SDK-iOS#263]
The release notes associated with the 4.5.3 release are unavailable on the DJI developer portal under the Downloads section (https://developer.dji.com/mobile-sdk/downloads/).

Clicking the link for Release Notes link results in an AWS S3 error page

```
<Error>
   <Code>InvalidAccessKeyId</Code>
   <Message>The AWS Access Key Id you provided does not exist in our records.</Message>
   <AWSAccessKeyId>{REDACTED}</AWSAccessKeyId>
   <RequestId>6E0CA2542BB8510B</RequestId>
<HostId>64l+xitPT3kJPFl/aLUfb2z+uky5lDBe8T7PEF3OBd82Nvx8bH+VNsAx9w19Yi6GwtDaajCskoA=</HostId>
</Error>
```

**Comment by tudorDME** [comment]
It is now available. Wasn't 4 hours ago.

**Comment by dji-dev** [comment]
Hi @adolfo , this issue is fixed, if you still have more issues related to DJI SDK or DJI developer website, please help to report them to dev@dji.com, as it's our official channel for developers to request DJI SDK support now.
