### ISSUE TITLE
“Invalid Bundle” when submitting to App Store using SDK 4.6

### ISSUE THREAD

**Issue by gdavis** [dji-sdk/Mobile-SDK-iOS#267]
**Description**
After updating the iOS SDK and UI SDK to version 4.6 from 4.5.2 I now receive the following error when submitting a build to the App Store:

> [Transporter Error Output]: ERROR ITMS-90206: "Invalid Bundle. The bundle at ‘AppName.app/Frameworks/DJISDK.framework’ contains disallowed file ‘Frameworks'."

[Click here for full error gist](https://gist.github.com/gdavis/d4200f1d189226d57168d501aba015c3)
[Click here for the Podfile](https://gist.github.com/gdavis/ce0cfd566f551d4ee9464b6a2ecc3e41)

You can see the extra folder within the iOS framework that should not be present:
![image](https://user-images.githubusercontent.com/110691/42250897-7056c58c-7ef1-11e8-8bd9-15eccf4ab411.png)

Note that this issue is not present in the previous SDK version (4.5.2). 

**Reproduction Steps**
* Have an app using iOS SDK version 4.6
* Archive the app for the App Store 
* Submit the archive using the iTunes Transporter
* Observe the error returned from the App Store 

In my case I’m using `fastlane` to automate all these steps. Since upgrading SDKs, the previous lanes no longer successfully submit due to this new error.

**Environment Information**
DJI SDK: 4.6
DJI UI SDK: 4.6
DJI Product: Any
iOS Version: 11.3
iOS Device: Any
Xcode Version: 9.4.1

**Comment by zoemcmac** [comment]
4.6.1 just released to fix this, announced on thread https://github.com/dji-sdk/Mobile-SDK-iOS/issues/259#issuecomment-401849872

**Comment by dji-dev** [comment]
Hi @gdavis , have you resolved your issue with the latest DJI SDK version? If not, please help to report your issue to dev@dji.com, as it's our official channel for developers to request  DJI SDK support now.
