### ISSUE TITLE
productConnected(_ product: DJIBaseProduct?) not called

### ISSUE THREAD

**Issue by gghangura** [dji-sdk/Mobile-SDK-iOS#274]
I am trying to connect Mavic Air using DJISDK.framework. After I call 
DJISDKManager.startConnectionToProduct()
the following delegate method is not called. 
productConnected(_ product: DJIBaseProduct?)

I am using DJI-SDK-iOS (4.6.1)

I also tried connecting Spark but the same problem. 

I am using iOS version 11.4.1 on iPhone 7 plus. 
XCode version 9.4.1.

**Comment by KCPavana** [comment]
Hey, I have been facing the same issue. My productConnected Delegate is not called. I am working with SDK 4.8.1. Any solution found?
