### ISSUE TITLE
Camera method setMediaFileCallback exists on ANDROID API and not on IOS

### ISSUE THREAD

**Issue by fontained** [dji-sdk/Mobile-SDK-iOS#293]
Dear development team, could you please add the following method setMediaFileCallback on Camera object. This method is already available on Android-SDK but not on IOS-SDK.

There is no way to get information about a photo taken without changing the camera operating mode.
We would like to have access to meta information including the filename of a photo on the fly without to set the camera mode to DJICameraModeMediaDownload.
Thank you
Best regards

**Comment by lijia6745** [comment]
Please use this
- (void)camera:(DJICamera *_Nonnull)camera didGenerateNewMediaFile:(DJIMediaFile *_Nonnull)newMedia;

**Comment by lijia6745** [comment]
Did you resolve your issue with a solution？
If it's resolved, I will close the issue.
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
