### ISSUE TITLE
get worry appActivationState value

### ISSUE THREAD

**Issue by uestcahui** [dji-sdk/Mobile-SDK-iOS#295]
MSDK V4.8.1
XCode 9.4.1

I have a brand new M210.   Its aircraftBindingState should be `DJIAppActivationAircraftBindingStateUnbound`, according to [Application Activation and Aircraft Binding](https://developer.dji.com/cn/mobile-sdk/documentation/ios-tutorials/ActivationAndBinding.html).  But the value I received is `DJIAppActivationAircraftBindingStateBound` .  

could someone explain to me how to get the aircraft binding status?

**Comment by XietongLU** [comment]
@uestcahui binding is not required if you are not using the aircraft in China. 
If you are worried about the state, please enable the debug log and send the log to us.

**Comment by uestcahui** [comment]
> @uestcahui binding is not required if you are not using the aircraft in China.
> If you are worried about the state, please enable the debug log and send the log to us.

我是在中国啊，现在飞机用DJI Pilot激活了，没法重现了

**Comment by XietongLU** [comment]
@uestcahui 建议调试过程开启 log。如果有环境复现，麻烦发一下 log。

**Comment by uestcahui** [comment]
> @uestcahui 建议调试过程开启 log。如果有环境复现，麻烦发一下 log。

好的，还遇到两个个问题：
1、M210上面，同时挂了PSDK负载和Zenmuse Z30，通过DJIAircraft.cameras属性获取所有相机，结果数组里面只有Z30？

2、通过 SDK Bridge调试时，分配带宽的 `setBandwidthAllocationForMainCamera`  `setBandwidthAllocationForLeftCamera` 都会出错，错误为飞机不支持这种操作。直接导致现在没法使用SDK Bridge调试。
