### ISSUE TITLE
DJIAttitude yaw

### ISSUE THREAD

**Issue by mohammedDehairy** [dji-sdk/Mobile-SDK-iOS#3]
currently i am creating an app for DJI phantom 2 , and i am creating a Yaw orientation compass (S---W---N---E---S) , but i am not sure whether the DJIAttitude.yaw is measured from the north or from the south , for example if the yaw is -180 or 180 , does that mean South or North .

and also if its measured from south , is negative values toward the West of towards the East , and likewise if its measured from North.

i am assuming that if DJIAttitude.yaw is a number greater than 360 like 1000 , this means that the yaw is (1000 mod 360).

Please help me .

**Comment by SilverChangjian** [comment]
Actually, the yaw is 0 while the heading of the aircraft is pointing to north.

If the yaw is 180, it means south.

**Comment by mohammedDehairy** [comment]
and is right that if the yaw is a number greater than 360 like 1500 , does that mean (1500 mod 360) ?

**Comment by SilverChangjian** [comment]
But the range of the yaw is from -180 to 180.. It might not be 1500.

**Comment by mohammedDehairy** [comment]
okay , may its because i am using an older version of the SDK , i am not using the current version .

**Comment by mohammedDehairy** [comment]
but thanks any way , may be i got it wrong .
