### ISSUE TITLE
DJIGoToMissionStep typo

### ISSUE THREAD

**Issue by flotwig** [dji-sdk/Mobile-SDK-iOS#31]
https://github.com/dji-sdk/Mobile-SDK-iOS/blob/master/Sample%20Code/DJISDK.framework/Headers/DJIGoToStep.h#L30

"coorinate" should be "coordinate"

This is also misspelled in the other initializer in the same file and in the documentation.

**Comment by dji-dev** [comment]
Hi! Thanks for your suggestions, we have already fixed the typos in the SDK, will update it in our next SDK release.

**Comment by dji-dev** [comment]
Close this issue now.
