### ISSUE TITLE
Add Osmo Pocket and Osmo Action support

### ISSUE THREAD

**Issue by kibermaks** [dji-sdk/Mobile-SDK-iOS#314]
Guys, please add support of Osmo Pocket and Osmo Action. Many of our customers request the support for this software!<br><br> gz#24603

**Comment by dji-dev** [comment]
> Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/24603'>Zendesk ticket #24603</a>:<br><br>Thanks for reaching out to DJI Developer Support.  I will pass on the request about providing SDK support for DJI Action and as for the OSMO Pocket,  DJI is targeting support in the next couple of release cycles.<br><br>Lisa Fedane<br>DJI Developer Support

**Comment by demiantres** [comment]
Is there any progress on Osmo Action support?

**Comment by Swiftwork** [comment]
I'm looking for some more info regarding this too

**Comment by gangwang2020** [comment]
Any update on osmo pocket SDK support?

**Comment by zsinba** [comment]
any update on dji pocket2?
