### ISSUE TITLE
Is there a demo for iOS hardware decoding?

### ISSUE THREAD

**Issue by zzz2016** [dji-sdk/Mobile-SDK-iOS#315]
When I enable iOS hardware decode, there is a log, "can not find idr path func". What dose that means?  <br><br>Do I have to provide an i-frame path? <br><br>Where can I find this frame file?<br> gz#24881

**Comment by dji-dev** [comment]
> Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/24881'>Zendesk ticket #24881</a>:<br><br>Dear Customer,<br><br>Thank you for contacting DJI.<br>Here is a sample code for the IOS hardware decoding, please check if it can help you.<br>https://github.com/dji-sdk/Mobile-SDK-iOS/tree/master/Sample%20Code/ObjcSampleCode/DJISdkDemo/Demo/Camera/fpv<br><br>Thanks,<br><br>Luce Luo<br>DJI Dev Team

**Comment by zzz2016** [comment]
> > Public comment from Luce Luo in [Zendesk ticket #24881](https://djisdksupport.zendesk.com/agent/tickets/24881):Dear Customer,Thank you for contacting DJI.Here is a sample code for the IOS hardware decoding, please check if it can help you.https://github.com/dji-sdk/Mobile-SDK-iOS/tree/master/Sample%20Code/ObjcSampleCode/DJISdkDemo/Demo/Camera/fpvThanks,Luce LuoDJI Dev Team

Thank you very much !  This issue has been solved.

**Comment by sgallo0692** [comment]
@logancautrell Do you have any sample code implementing this solution? 

I'm having similar distortion issues and `cv_pixelbuffer_fastupload` is always nil.

**Comment by logancautrell** [comment]
I don't have any code I can share. Somewhere in your global code (Obj-C) you can simply put

`g_loadPrebuildIframeOverrideFunc = loadPrebuildIframePrivate`

**Comment by sgallo0692** [comment]
thank you
