### ISSUE TITLE
DJIOnboardSDKDevice delegate called multiple times

### ISSUE THREAD

**Issue by Jahor** [dji-sdk/Mobile-SDK-iOS#318]
If DJIOnboardSDKDevice.delegate property is set to the same value multiple times, delegate's method `onboardSDKDevice:didSendDataToMobile:` will be called multiple times when data is received.<br><br>DJI-SDK-iOS (4.10) gz#25647

**Comment by dji-dev** [comment]
> Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/25647'>Zendesk ticket #25647</a>:<br><br>Dear Customer,<br><br>Thank you for contacting DJI.<br>To help us collect questions in detail, please fill in the form below and we will handle this ticket once we have received it.<br>https://formcrafts.com/a/dji-developer-feedback-en<br><br>Thanks,<br><br>Luce Luo<br>DJI Dev Team

**Comment by vince-zheng** [comment]
We have fixed the issue. And we will release in next version.
