### ISSUE TITLE
Use a strongly typed NSArrays in delegate protocol for DJILBAirLinkDelegate.

### ISSUE THREAD

**Issue by pquimby** [dji-sdk/Mobile-SDK-iOS#32]
The following callbacks for the DJILBAirLinkDelegate return untyped NSArrays. This causes several inconveniences because it forces developers to cast the results and prevents intelligent IDE features from being able to search for usages of the relevant payload datatypes. Preferably all the delegate methods would use generics of the appropriate types.

```
- (void)lbAirLink:(DJILBAirLink *_Nonnull)lbAirLink didUpdateRemoteControllerSignalInformation:(NSArray *_Nonnull)antennas;
- (void)lbAirLink:(DJILBAirLink *_Nonnull)lbAirLink didUpdateLBAirLinkModuleSignalInformation:(NSArray *_Nonnull)antennas;
- (void)lbAirLink:(DJILBAirLink *_Nonnull)lbAirLink didUpdateAllChannelSignalStrengths:(DJILBAirLinkAllChannelSignalStrengths)signalStrength;
```

**Comment by dji-dev** [comment]
Hi @pquimby, thanks for your feedbacks. We will investigate this issue and get back to you soon.

**Comment by dji-dev** [comment]
Hi @pquimby, we will improve the delegate methods of DJILBAirLinkDelegate in the future SDK release. Thanks!

**Comment by XietongLU** [comment]
This interface is refactored in SDK 4.0.
