### ISSUE TITLE
Support for Mavic Mini

### ISSUE THREAD

**Issue by pskow** [dji-sdk/Mobile-SDK-iOS#335]
Are there any plans to extend support for Mavic Mini in current SDK? 
Right now when connecting it `product.name` shows as Phantom 3 Professional or Mavic 2 but doesn't really connect.

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/29739'>Zendesk ticket #29739</a>:<br><br>Thank you for contacting DJI Developer Support with your question. Sadly, it's not currently supported by our SDK yet, but we are planning to provide support in a future release. I have not been told _when_ the support is coming but I recommend looking at our release notes when there is a new releases

Lisa Fedane
DJI Developer Support

**Comment by kimar** [comment]
I’m not able to see the ticket, could you please check if the link is correct?

![image](https://user-images.githubusercontent.com/126418/70853522-4ee59400-1eaf-11ea-9ed1-afa905884a8e.jpg)

**Comment by RobertoD91** [comment]
Any news? Link is still broken, and there is no ticket on zendesk about sdk support for mavic mini with replay from dji

**Comment by dji-lisafedane** [comment]
The link is not meant for other commenters on this thread to follow - there is no public Zendesk ticket for people to view.  But I can answer your question - we are planning to provide Mavic Mini SDK support in 2020.  Which release is not yet determined, so please read the notes after a release

**Comment by dyllanwli** [comment]
Would love to see mobild-sdk-ios support Mavic Mini!

**Comment by janislejins** [comment]
> The link is not meant for other commenters on this thread to follow - there is no public Zendesk ticket for people to view. But I can answer your question - we are planning to provide Mavic Mini SDK support in 2020. Which release is not yet determined, so please read the notes after a release

Hi - Is there any update on this? I know businesses, esp in agriculture and wind farm maintenance, are preparing and reviewing resource allocations for the next few Qs and the incorporation of an SDK for Mavic Mini will vastly improve the USP for lite surveying that enables more efficient remote workers etc.

**Comment by mafischer** [comment]
According to dji developer roadmap, Mavic Mini support (release 4.13) eta is 7/12/2020. I’ve been refreshing all day, still not released :(

https://developer.dji.com/user/roadmap/

**Comment by RobertoD91** [comment]
Now it say "31-07-2020" 😢

> According to dji developer roadmap, Mavic Mini support (release 4.13) eta is 7/12/2020. 
> https://developer.dji.com/user/roadmap/

**Comment by pskow** [comment]
It's up (4.13), let's celebrate! 🥂🍾

**Comment by sgallo0692** [comment]
@RobertoD91 @pskow are you able to see mini as product.name when checking ProductCommunication ? My product always shows blank with the mini connected on ios sdk 4.13.1
