### ISSUE TITLE
Camera menu not available when I run the app with A3 FLIGHT CONTROLLER

### ISSUE THREAD

**Issue by alexandrubichis** [dji-sdk/Mobile-SDK-iOS#34]
Hello,

I've build the demo app and camera menu is not available in menu when I run with my A3 flight controller. I also tried the iOS-FPVDemo and same I have the same problem. There is no issue running with my Phantom, camera is available in menu list and FPVDemo is working.

**Comment by alexandrubichis** [comment]
I still have this issue with latest Mobile SDK 3.3. According to their release notes A3 with Lightbridge 2 is listed as supported product. Can anybody help me with this?

**Comment by dji-dev** [comment]
Hi, please make sure that you use the latest iOS SDK 3.3 in your project, which you can download from our developer website or from this Github repository. Secondly, if you don't have camera(Like DJI X3/X5/X5R camera) connect with A3+LB2, the camera menu must be not available. If you still cannot solve the issue, could you send us an email to describe your issue with debug logs and details description? Email address: oliver.ou@dji.com. Thanks!

**Comment by alexandrubichis** [comment]
First of all I'm using the latest Mobile SDK version. I understand that camera menu is available only for DJI camera's. My problem is that I can't do live video stream with a camera that is not from DJI on ios platform (tested on iOS-FPVDemo project from github with latest sdk). On android the stream is working fine. Please note that my pursue is not to control the camera.
