### ISSUE TITLE
Unable to request token for developer registration

### ISSUE THREAD

**Issue by ynain** [dji-sdk/Mobile-SDK-iOS#351]
I am attempting to perform the first of the steps listed here in order to create an Android app: https://developer.dji.com/mobile-sdk/documentation/quick-start/index.html

However, I am unable to request a verification token, neither through my phone number or email. The option for "Send Token" is grayed out, no matter what I attempt to do.

<img width="923" alt="Screen Shot 2020-02-05 at 11 47 45 AM" src="https://user-images.githubusercontent.com/22084517/73863319-de535780-480d-11ea-8e6f-cf12f7dafc2e.png">

Is this a known issue?

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/31966'>Zendesk ticket #31966</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
What browser you are using?
Can you please try another browser to try it again like the Google browser?

Thanks,

Luce Luo
DJI Dev Team
