### ISSUE TITLE
DJI Wapoint Mission changing speed problem!!??

### ISSUE THREAD

**Issue by alzin** [dji-sdk/Mobile-SDK-iOS#353]
I have achieved a waypoint mission function where the drone takeoff, start recording a new video and then start its waypoint mission in which it flies to altitude 15 meters. The problem here that I want to change the speed of the drone while flying toward the next waypoint. However, I could change the second waypoint speed to 0.5 m/s but the first waypoint is not responding to the changing in speed at all

Note that the following link refers to the function **speed** explanation from the website:

https://developer.dji.com/api-reference/ios-api/Components/Missions/DJIWaypoint.html#djiwaypoint_speed_inline

Here is my code and the waypoint function that I am using:

So I would be glad if someone can refer to how to change to speed!?

`func defaultWaypointMission() -> DJIWaypointMission? {
        
        // Define a new object class for the waypoint mission.
        let mission = DJIMutableWaypointMission()
        
        mission.maxFlightSpeed = 15
        mission.autoFlightSpeed = 8
        mission.finishedAction = .noAction
        mission.headingMode = .usingInitialDirection
        mission.flightPathMode = .normal
        mission.rotateGimbalPitch = false
        mission.exitMissionOnRCSignalLost = true
        mission.gotoFirstWaypointMode = .pointToPoint
        mission.repeatTimes = 1
        
        // Keep listening to the drone location included in latitude and longitude.
        guard let droneLocationKey = DJIFlightControllerKey(param: DJIFlightControllerParamAircraftLocation) else {
            return nil
        }
    
        guard let droneLocationValue = DJISDKManager.keyManager()?.getValueFor(droneLocationKey) else {
            return nil
        }
        
        let droneLocation = droneLocationValue.value as! CLLocation
        let droneCoordinates = droneLocation.coordinate
        
        // Check if the returned coordinate value is valid or not.
        if !CLLocationCoordinate2DIsValid(droneCoordinates) {
            return nil
        }
        
        mission.pointOfInterest = droneCoordinates
        
        let loc1 = CLLocationCoordinate2DMake(droneCoordinates.latitude, droneCoordinates.longitude)
        let waypoint1 = DJIWaypoint(coordinate: loc1)
        waypoint1.altitude = 2
        waypoint1.heading = 0
        waypoint1.actionRepeatTimes = 1
        waypoint1.actionTimeoutInSeconds = 60
        waypoint1.cornerRadiusInMeters = 5
        waypoint1.turnMode = .clockwise
        waypoint1.gimbalPitch = 0
        waypoint1.speed = 0.5 // It is not responding to this at all
        
        let loc2 = CLLocationCoordinate2DMake(droneCoordinates.latitude, droneCoordinates.longitude)
        let waypoint2 = DJIWaypoint(coordinate: loc2)
        waypoint2.altitude = 15
        waypoint2.heading = 0
        waypoint2.actionRepeatTimes = 1
        waypoint2.actionTimeoutInSeconds = 60
        waypoint2.cornerRadiusInMeters = 5
        waypoint2.turnMode = .clockwise
        waypoint2.gimbalPitch = 0
        // Chnage the velocity of the drone while moving to this waypoint, this is works fine.
        waypoint2.speed = 0.5
        
        mission.add(waypoint1)
        mission.add(waypoint2)
      
        return DJIWaypointMission(mission: mission)
    }`

Working Environment:

macOS Catalina
Xcode 11.3.1
Swift 5

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32110'>Zendesk ticket #32110</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
In a waypoint mission, you can use this speed property to change the speed when this wp move to the next wp.
 ![](https://djisdksupport.zendesk.com/attachments/token/XCxyEArHXeREhcH8DvKCyHJCp/?name=inline-2069879208.png)​
And it's impossible to change the speed from the start point to the first point.
Sorry, it is limit and was controlled by the firmware.

Thanks,

Luce Luo
DJI Dev Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/XCxyEArHXeREhcH8DvKCyHJCp' target='zd_attach'>inline-2069879208.png</a>

**Comment by zyphs21** [comment]
You can separate from one waypoint mission into two. The first waypoint mission has two waypoint: the home point location and the "waypoint1" which is the actual first waypoint you wanted. So you can control the speed.

**Comment by alzin** [comment]
@zyphs21 It seems a smart logic solution. I will try it and give you feedback. 😊
