### ISSUE TITLE
Crash Happen when connect the DJIRTK Network in DJI-SDK-iOS (4.11.1)

### ISSUE THREAD

**Issue by zyphs21** [dji-sdk/Mobile-SDK-iOS#354]
Crash Happen when connect the DJIRTK Network:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', 
reason: '-[DJINRTKManager setAuthRetryCount:interval:]: unrecognized selector sent to instance 0x1c0641590'
```

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/32163'>Zendesk ticket #32163</a>:<br><br>This is Lisa from DJI Developer Support - can you report this crash directly to our service desk using this form: https://formcrafts.com/a/dji-developer-feedback-en.  We'll be happy to look into this further for you.

Please note that we will need included more details, like: drone model (P4PRTK or M210 RTK, etc...) and firmware version, version of SDK, is this your custom app or our sample app, steps to reproduce the crash, mobile device, crash logs, etc...

Lisa Fedane
DJI Developer Support

**Comment by zyphs21** [comment]
[DJINetworkRTKHelper 1.2](https://github.com/dji-sdk/DJINetworkRTKHelper/releases/tag/v1.2) Fix this problem
