### ISSUE TITLE
Is setVirtualStickAdvancedModeEnable() missing on iOS?

### ISSUE THREAD

**Issue by lleoncinicds** [dji-sdk/Mobile-SDK-iOS#355]
I saw in the Android api that have the method setVirtualStickAdvancedModeEnable() but on iOS is missing however the propertie isVirtualStickAdvancedModeEnabled exist on iOS but it can't be enabled.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32209'>Zendesk ticket #32209</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I try to find the related method for you, please check if it is you want.
https://developer.dji.com/api-reference/ios-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_virtualstickcontrolmodecategory_setvirtualstickmodeenabled_inline
 ![](https://djisdksupport.zendesk.com/attachments/token/umOht5nm2zNl6Dci3snZ0YlMv/?name=inline-401224597.png)​

Thanks,

Luce Luo
DJI Dev Team<br><a href='https://djisdksupport.zendesk.com/attachments/token/umOht5nm2zNl6Dci3snZ0YlMv' target='zd_attach'>inline-401224597.png</a>

**Comment by lleoncinicds** [comment]
Hello, thanks for your reply. 

  That one is not the advance mode setVirtualStick**Advanced**ModeEnable. We have the advanced mode on Android but seems like is not implemented on iOS.

https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html?search=setvirtualstickadvancedmodeenable&i=0&#djiflightcontroller_setvirtualstickadvancedmodeenabled_inline

  The problem that we have is that the drone drift with the wind when we use the virtual sticks and looks like the advance mode will could help to overcome this.

**Comment by dji-dev** [comment]
Public comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32209'>Zendesk ticket #32209</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
I see.
Sorry about this, I need to confirm with the engineer first.
It will cost some time and we will contact you again once any progress.

Thanks,

Luce Luo
DJI Dev Team

**Comment by hdrpano** [comment]
The advanced virtual stick is already in iOS. If you activate virtual stick, don't forget to deactivate after use. The user cannot handle the stick if virtual stick rest enabled. I put both methods in my post.

See how you can enable it:

    func startVirtualStick(enabled: Bool = true) {
        guard let virtualStickKey = DJIFlightControllerKey(param: DJIFlightControllerParamVirtualStickControlModeEnabled) else {
            return;
        }
        
        DJISDKManager.keyManager()?.setValue(NSNumber(value: enabled), for: virtualStickKey, withCompletion: { (error: Error?) in
            if error != nil {
                print("Error start virtual stick")
            }
            print("Start virtual stick \(enabled)")
        })
    }
    
    func startAdvancedVirtualStick(enabled: Bool = true) {
        guard let virtualStickKey = DJIFlightControllerKey(param: DJIFlightControllerParamVirtualStickAdvancedControlModeEnabled) else {
            return;
        }
        
        DJISDKManager.keyManager()?.setValue(NSNumber(value: enabled), for: virtualStickKey, withCompletion: { (error: Error?) in
            if error != nil {
                print("Error start advanced virtual stick")
            }
            print("Start advanced virtual stick \(enabled)")
        })
    }

**Comment by lleoncinicds** [comment]
That's works great, thanks!
