### ISSUE TITLE
Only RemoteController showing as drone model intermittently

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-iOS#361]
Intermittently when a product connects the model shows as `Only RemoteController`. I was able to reproduce this issue in the sample app in this repo. Please see screen shot below. This can be problematic when needing to rely on the drone model name.

Is there another way to always retrieve the correct drone model name reliably other than from `DJIBaseProduct`? It seems to be some sort of race condition because if I try and get the name again a few seconds later I get the correct model name but that seems like a bit of a hack.

![Screen Shot 2020-04-30 at 5 27 48 PM](https://user-images.githubusercontent.com/11700939/80771426-4614f800-8b08-11ea-9e27-97f81b007e1d.png)

Drones tested: Mavic 2 Pro, Mavic Pro, Phantom 4
SDK Version: 4.11.2

**Comment by dji-dev** [comment]
Agent comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/34129'>Zendesk ticket #34129</a>:<br><br>DJI Developer Support engineers will be on holiday for the international worker's day (5-1 ~ 5-5), which may cause some delays in responding to your issue. Thank you for you understanding and we will answer you as quickly as possible.

Best Regards,
DJI SDK Support Team

Join DJI's Developer Community in our new Forum for Technical Discussions, Announcements and More:
https://forum.dji.com/forum-139-1.html?from=developer

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/34129'>Zendesk ticket #34129</a>:<br><br>Dear Brien,

Thank you for contacting DJI.
The MSDK provides the only method model to return back the model name.
It will have some delay and you can use the componentConnectedWithKey:andIndex method to check the components' status.
And then get the name after the flight controller connected.
 ![](https://djisdksupport.zendesk.com/attachments/token/tnYPsKYJrexQnnSm63nhbu3k7/?name=inline1044167592.png)​


Thanks,

Luce Luo
DJI Dev Team

**Comment by brien-crean** [comment]
@dji-dev thanks for the reply, that worked perfectly for me!
