### ISSUE TITLE
New SDK 4.12 crashes in DJIFlightRecord

### ISSUE THREAD

**Issue by pskow** [dji-sdk/Mobile-SDK-iOS#363]
Application crashes when trying connect to the product with `DJISDKManager.startConnectionToProduct()`

Drone: Mavic 2 Pro
Here is the log:
```
WriterBuffer
File to write: /var/mobile/Containers/Data/Application/2EB661A8-DEC0-473B-B51E-6C5229CFB1E6/Documents/SDK_logs/FlightRecord/DJIFlightRecord_2020-05-12_[17-49-44].txt
Assertion failed: (false && "can't find aes cipher idx"), function AESEncryptionData, file /Users/afstand.ren/DJIDev/dji-flightrecordengine/source/Writer/encryption/flight_record_encryption_layer.cpp, line 171.
```

**Comment by vince-zheng** [comment]
How do you reproduce? Is that a must? @pskow

**Comment by thanhtinh138** [comment]
Please help me fix this issue soon, I met this issue with this steps:
1. Open app
2. Connected drone
3. Make drone on HOVERING
4. Terminate app
5. Open app again

**Comment by thanhtinh138** [comment]
@vince-zheng I mention you for this issue with above case.

**Comment by vince-zheng** [comment]
@thanhtinh138 You can try in the next version.
