### ISSUE TITLE
Camera source for shootPhotoDistanceInterval (DJIWaypoint) on drones with multiple cameras

### ISSUE THREAD

**Issue by india2sarthak** [dji-sdk/Mobile-SDK-iOS#385]
We are trying to add support for drones with multiple cameras like **Matrice210 V2**, **Matrice 210 RTK V2**.

In our app, we use the `DJIWaypointMission` object for flying missions and set the `shootPhotoDistanceInterval` property for capturing photos. What I am unable to figure out is 
- Which camera is the drone going to use to **capture photos for drones with multiple cameras**?
- and if there is any way to **set which camera** to use for capturing photos while executing a waypoint mission.

Here is how I am setting the `shootPhotoDistanceInterval` and preparing a waypoint (Simplified version)
```
 let singleWaypoint: DJIWaypoint = DJIWaypoint(
                coordinate: CLLocationCoordinate2D(
                    latitude: point[1], longitude: point[0]
                )
            )
if let distanceBasedTrigger = waypointProperties.dist_based_trigger {
                singleWaypoint.shootPhotoDistanceInterval = distanceBasedTrigger
            }
```

**DJI Mobile SDK Version**: 4.11.2
**DJIWidget**: 1.6.2

Thanks a lot for helping  :)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/38031'>Zendesk ticket #38031</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that the Waypoint Mission V1 only the main camera can be used for the action and can't assign the second camera.

Thanks,

Luce Luo
DJI Developer Support

**Comment by india2sarthak** [comment]
Thanks a lot for your reply. Could you also tell which camera is considered as the **main camera** (Left or Right) ?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/38031'>Zendesk ticket #38031</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The left camera is main one.

Thanks,

Luce Luo
DJI Developer Support
