### ISSUE TITLE
Mavic 2Zoom使用 MSDK v4.13 视频流会出现畸变

### ISSUE THREAD

**Issue by fanbaoyuanbees360** [dji-sdk/Mobile-SDK-iOS#390]
Mavic 2Zoom使用 MSDK v4.13 视频流会出现畸变，下图为运行Sample Code出现的
畸变截图，使用 MSDK v4.12一切正常，可以运行你们最新的Sample Code复现该问题，请及时修复，谢谢

![IMG_2181](https://user-images.githubusercontent.com/42194060/91116910-062dde00-e6c0-11ea-9d88-95245f00ffa9.PNG)

**Comment by zyphs21** [comment]
I don't have Mavic 2Zoom, but maybe you can try set  dewarpingEnabled to true ?

```
- (void)setVideoDewarpingEnabled:(BOOL)enabled withCompletion:(DJICompletionBlock)completion;
```

**Comment by fanbaoyuanbees360** [comment]
> I don't have Mavic 2Zoom, but maybe you can try set dewarpingEnabled to true ?
> 
> ```
> - (void)setVideoDewarpingEnabled:(BOOL)enabled withCompletion:(DJICompletionBlock)completion;
> ```

我试了下调用这个方法，也行不通

**Comment by Michael-DJI** [comment]
4.14 has fix this issue

**Comment by fanbaoyuanbees360** [comment]
@Michael-DJI 我刚才下载了你们4.14的版本的demo，用swift版本测试连接Mavic air 2,连接不上
