### ISSUE TITLE
获取禁飞区信息有问题

### ISSUE THREAD

**Issue by hujewelz** [dji-sdk/Mobile-SDK-iOS#408]
通过 `getFlyZonesInSurroundingAreaWithCompletion:(void (^_Nonnull)(NSArray<DJIFlyZoneInformation*> *_Nullable infos, NSError* _Nullable error))completion;` 接口获取禁飞区信息，在大部分情况下跟 [官网](https://www.dji.com/cn/flysafe/geo-map)查询的结果基本一致。但是当模拟器模拟在杭州萧山附近时，结果完全不一样了。通过接口获取的会都一块禁飞区：
![Lark20201125-115958](https://user-images.githubusercontent.com/10481313/100181974-7560db80-2f16-11eb-9540-4cef3e58202f.jpeg)

**官网查询结果**
![image](https://user-images.githubusercontent.com/10481313/100182050-a6d9a700-2f16-11eb-9fe8-385b35166f35.png)

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/41447'>Zendesk ticket #41447</a>:<br><br>尊敬的用户，

您好！感谢您联系DJI 大疆创新。
为了快速收集问题细节，麻烦您详细填写如下表格。
https://formcrafts.com/a/dji-developer-feedback-cn

在收到您的详细细节信息后，我们将会进行快速处理。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
