### ISSUE TITLE
DJIWidget是否支持SwiftUI

### ISSUE THREAD

**Issue by lhcn** [dji-sdk/Mobile-SDK-iOS#412]
`//
//  FPVView.swift
//  swiftui test

import SwiftUI
import UIKit

struct DJIVideoPreviewView: UIViewRepresentable {
    var previewUI = UIView.init(frame: CGRect(x:300,y:300,width: 300,height: 300))
    
    func updateUIView(_ uiView: UIViewType, context: Context) {
        // @TODO need update?
        NSLog("updateUIView")
    }
    
    func makeUIView(context: Context) -> some UIView {
        return previewUI
    }
}

struct FPVView: View {
    
    var camaraManager = CameraManager()

    var previewView = DJIVideoPreviewView()
    
    var body: some View {
        VStack {
            previewView
        }.onAppear(){
            NSLog("FPV appear")
            testSetView(previewView.previewUI)
            //camaraManager.start(previewView.previewUI)
        }.onDisappear(){
            NSLog("FPV disappear")
            camaraManager.end()
        }
    }
    
    func degreeUpdate(_ value: String){
        self.degree = value
    }
}

struct FPVView_Previews: PreviewProvider {
    static var previews: some View {
        FPVView()
    }
}

// 测试 模拟
func testSetView(_ uiview: UIView){
    NSLog("setView Demo")
    let frame = CGRect(x:10,y:10,width:200,height: 20)
    let text = UITextView.init(frame:frame )
    text.text = "inner view \(frame)"
    uiview.addSubview(text)
    uiview.sendSubviewToBack(text)
}

# CameraManager部分
`
class CameraManager: NSObject {
    var adapter: VideoPreviewerAdapter?
    var needToSetMode = false
    
    func start(_ uiview: UIView) {
        
        let camera = fetchCamera()
        camera?.delegate = self
        
        // 试试放到这里
        DJIVideoPreviewer.instance()?.setView(uiview)
        
        needToSetMode = true
        
        DJIVideoPreviewer.instance()?.start()
        
        adapter = VideoPreviewerAdapter.init()
        adapter?.start()
        
        if camera?.displayName == DJICameraDisplayNameMavic2ZoomCamera ||
            camera?.displayName == DJICameraDisplayNameMavic2ProCamera {
            adapter?.setupFrameControlHandler()
        }
        
        NSLog("DJIVideoPreviewer.setView")
    }
    
# DJIVideoPreviewer中 setView部分参考，也是改
`
-(BOOL)setView:(UIView *)view
{
    BEGIN_MAIN_DISPATCH_QUEUE
    if(_glView == nil){
        //generate
        _glView = [[DJIMovieGLView alloc] initWithFrame:CGRectMake(0.0f, 0.0f, view.frame.size.width, view.frame.size.height)];
        _glView.delegate = self;
        _glView.rotation = self.rotation;
        _glView.contentClipRect = self.contentClipRect;
    }
    
    
    if(_glView.superview != view){
        [view addSubview:_glView];
    }
    [view sendSubviewToBack:_glView];
    [_glView adjustSize];
    _status.isGLViewInit = YES;
    
    //set self frame property
    [self movieGlView:_glView didChangedFrame:_glView.frame];
    self.internalGLView = _glView;
    END_DISPATCH_QUEUE
    return NO;
}`

**Comment by lhcn** [comment]
实测，能看到视频出来，然后一秒崩溃了。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42051'>Zendesk ticket #42051</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，这个问题需要与工程师确认下。
这将花费一定时间，一旦有任何进展我们将会再次联系您。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by lhcn** [comment]
自己解决了

**Comment by seungbeom-son** [comment]
Hi, @lhcn 

I'm in the exactly same same case with you.

Could you tell me how did you resolve it?

Thank you.
---------------------
你好 @lhcn 

我跟你情况完全一样。

你能告诉我你是怎么解决的吗？

谢谢你

(Google translate)
