### ISSUE TITLE
M300 RTK无法获取到电池状态

### ISSUE THREAD

**Issue by dingpwen** [dji-sdk/Mobile-SDK-iOS#414]
use_frameworks!
pod 'DJI-SDK-iOS','~> 4.13.1'
pod 'DJI-UXSDK-iOS', '~> 4.13'
pod 'DJIWidget', '~> 1.6.3'

然后等无人机连接后，发现self.aircraft.batteries一直是null，无法通过这个来监听电池的状态，例如电池温度，但看UXSDK的UI又是可以正常获得电池的百分比的，请问，M300 RTK，要如何监听电池的状态？

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42175'>Zendesk ticket #42175</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
多电池组需要使用aggregationDelegate代理监听。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dingpwen** [comment]
3KS，昨天以及试出来了
