### ISSUE TITLE
Matrice 300 RTK - DJILens setWhiteBalance is not supported

### ISSUE THREAD

**Issue by edupazpix4d** [dji-sdk/Mobile-SDK-iOS#422]
**Drone:** DJI Matrice 300 RTK.
**Camera:** Zenmuse H20T.
**Mobile SDK:** 4.14-trial1.

When calling DJILens `setWhiteBalance`:
```
DJILens *lens = self.djiCamera.lenses[i];
[lens setWhiteBalance:cameraWhiteBalance withCompletion:^(NSError * _Nullable error) {
```

I get the following output:

```
Setting WhiteBalancing error(-3000) :Error Domain=DJISDKCameraErrorDomain Code=-3000 "This command is no longer supported or not supported in this firmware version.(code:-3000)" UserInfo={NSLocalizedDescription=This command is no longer supported or not supported in this firmware version.(code:-3000)}
```

**MobileSDK:** 4.14-trial1

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42372'>Zendesk ticket #42372</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Are you using the H20 series?
As the error show, the camera doesn't support the setWhiteBalance feature.

And the M300RTK is not supported by the waypoint mission V1, need to use the waypoint mission V2.

Thanks,

Luce Luo
DJI Developer Support

**Comment by edupazpix4d** [comment]
**Drone:** DJI Matrice 300 RTK.
**Camera:** Zenmuse H20T.

**Comment by edupazpix4d** [comment]
This is still happening in SDK 4.14.

**Comment by edupazpix4d** [comment]
In SDK 4.14 it's supported but not accepting parameters.
