### ISSUE TITLE
Matrice 300 RTK -WaypointV2Mission conflicts with RTK?

### ISSUE THREAD

**Issue by dingpwen** [dji-sdk/Mobile-SDK-iOS#424]
When RTK is Open, and trying to 
[[DJISDKManager missionControl].waypointV2MissionOperator startMissionWithCompletion:^(NSError * _Nullable error) {}]

It always tell that "The aircraft home point is not recorded yet"

But when I open the Rtk through RC, RC told me that home location is updated.

How to make waypointV2Mission work normally when RTK is opened?

MY firmware and sdk are all the latest.

**Comment by Matheus193dn** [comment]
@dingpwen hey it's me again, I have a note for you: only disable RTK when you are using Assistant app (for M300) to debug inside. If you go outside, please enable it.

This is my code when I debug inside:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/26027184/103072231-c805e400-45f7-11eb-98f9-5ce0d109e312.png">

For more details:
https://github.com/Matheus193dn/Mobile-SDK-iOS/blob/master/Sample%20Code/SwiftSampleCode/DJISDKSwiftDemo/Camera/fpv/CameraFPVViewController.swift

**Comment by dingpwen** [comment]
@Matheus193dn

First, thanks for youe help!

 I have tested outside, it also show the same hits  as "The aircraft home point is not recorded yet" when RTK is opened.

**Comment by Matheus193dn** [comment]
![image](https://user-images.githubusercontent.com/26027184/103074192-b4f51300-45fb-11eb-8fc6-40b7509ca7d7.png)
Did you try with one of these functions?

**Comment by dingpwen** [comment]
> ![image](https://user-images.githubusercontent.com/26027184/103074192-b4f51300-45fb-11eb-8fc6-40b7509ca7d7.png)
> Did you try with one of these functions?

I tried when using assistant app, but no-use.  When test outside, these codes have been deleted.

**Comment by Matheus193dn** [comment]
Oh, the weather in my location is not good today. I will try it when the weather get better, I will let you know my result ASAP.

**Comment by dingpwen** [comment]
@dji-dev  Do you have any answers?

**Comment by dingpwen** [comment]
when I am trying to get the info of home location:
`getHomeLocationWithCompletion:^(CLLocation * _Nullable homeLocation, NSError * _Nullable error) {
        if(error) {
            NSLog(@"get home location error:%@", error.description);
        } else {
            NSLog(@"home location is (lat=%.6f,lon=%.6f, high=%.2f)", homeLocation.coordinate.latitude, homeLocation.coordinate.longitude, homeLocation.altitude);`

I find that altitude is always 0, even if i use use codes to force set to 100:
`dispatch_async(dispatch_get_main_queue(), ^{
                    CLLocation *loc = [[CLLocation alloc]initWithCoordinate:homeLocation.coordinate altitude:100 horizontalAccuracy:0 verticalAccuracy:0 timestamp:[NSDate date]];
                    [[BRDroneSDKManager obtainFlightController]setHomeLocation:loc withCompletion:^(NSError * _Nullable error) {
                        if(error) {
                            NSLog(@"set home location error:%@", error.description);
                        }`

**Comment by dingpwen** [comment]
@Matheus193dn  any news?

@dji-dev  any replies?

**Comment by Matheus193dn** [comment]
Oh, sorry for late response. I tested with RTK enabled on Phantom4 RTK and it worked, i will test M300 later.

**Comment by dingpwen** [comment]
> Oh, sorry for late response. I tested with RTK enabled on Phantom4 RTK and it worked, i will test M300 later.

Do you open the RTK by RC or codes?

**Comment by Matheus193dn** [comment]
> > Oh, sorry for late response. I tested with RTK enabled on Phantom4 RTK and it worked, i will test M300 later.
> 
> Do you open the RTK by RC or codes?

oh i used code to enable/disable it

**Comment by dingpwen** [comment]
> > > Oh, sorry for late response. I tested with RTK enabled on Phantom4 RTK and it worked, i will test M300 later.
> > 
> > 
> > Do you open the RTK by RC or codes?
> 
> oh i used code to enable/disable it

When use NETWORK_RTK, As sdk shows:

Default virtual reference station solution to provide cm level accurate position. The frame can be either WGS84 or CGCS 2000. Please note that this default solution can only be used in China. Please add the "djinetworkrtkhelper" to the project via gradle:implementation 'com.dji:library-networkrtk-helper:2.0.2'. It is only supported by Phantom 4 RTK, P4 Multispectral and Matrice 300 RTK
--


Do you use this lib? Or which you use is BASE_STATION?

**Comment by dingpwen** [comment]
> > > Oh, sorry for late response. I tested with RTK enabled on Phantom4 RTK and it worked, i will test M300 later.
> > 
> > 
> > Do you open the RTK by RC or codes?
> 
> oh i used code to enable/disable it

Your RTK uses BASE_STATION or Network RTK?

**Comment by Matheus193dn** [comment]
@dingpwen plz use BASE_STATION

**Comment by dingpwen** [comment]
> @dingpwen plz use BASE_STATION

I test outside yesterday, and found it can fly with BASE_STATION. But what a fuck, the app crash in this line:
_gps = [DUXGPSSignalWidget new];

with error as EXC_BAD_ACCESS!
