### ISSUE TITLE
About virtual sticks

### ISSUE THREAD

**Issue by HosokawaRisako** [dji-sdk/Mobile-SDK-iOS#428]
I would like to know how to use a virtual stick to successfully semi-automate the Mavic Mini.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42716'>Zendesk ticket #42716</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Here is virtual stick documentation, please check if any help.
https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/SimulatorDemo.html

Thanks,

Luce Luo
DJI Developer Support

**Comment by HosokawaRisako** [comment]
Thank you very much for your reply.

Can this simulator tutorial fly the Mavic Mini in real life?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/42716'>Zendesk ticket #42716</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, this sample also can work in real flight, but just do not enable the simulator.

Thanks,

Luce Luo
DJI Developer Support
