### ISSUE TITLE
Matrice 300 RTK - When rtk is in use, UXSDK-UI crashed!

### ISSUE THREAD

**Issue by dingpwen** [dji-sdk/Mobile-SDK-iOS#429]
I use BASE_STATION for RTK, and when DJIRTKState.isRTKBeingUsed(=true), following code crashed:

_gps = [DUXGPSSignalWidget new];

with EXC_BAD_ACCESS!

 While DJIRTKState.isRTKBeingUsed=false, all is ok.

use_frameworks!
pod 'DJI-SDK-iOS', '~> 4.14-trial1'
pod 'DJI-UXSDK-iOS', '~> 4.14-trial1'
pod 'DJIWidget', '~> 1.6.3'
pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'

**Comment by dji-lisafedane** [comment]
@dingpwen - thanks for reporting this.  The UX SDK will look into this now but in the meanwhile, can you post the crash details?

**Comment by dingpwen** [comment]
目前正在通过邮件沟通，这里先关闭
