### ISSUE TITLE
Using DJI Fly app and MobileSDK together

### ISSUE THREAD

**Issue by ngeri** [dji-sdk/Mobile-SDK-iOS#431]
Dear Team,

I am trying to use the DJI Mobile SDK to gather some data from the drone but I want to use the DJI Fly app to fly the drone. So the question is that is it possible to connect to the drone (through the RC or any other method) with my mobile app parallel to the DJI Fly app? As far as I see when I call `DJISDKManager.startConnectionToProduct()` and the connection established the DJI Fly app loses the connection to the RC.

Could you help on this?

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/43005'>Zendesk ticket #43005</a>:<br><br>Dear Client
Thank you for contacting DJI.

You can seen the Mobile SDK app is another Fly app. It is impossible to run MSDK app parallel to the DJI FLY App. A drone can only be connected with one app at each time.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by ngeri** [comment]
Thank you for your response!

**Comment by ihurata1** [comment]
I have smiliar scenario, is there any updated way to gather information from dji sdk in background, while usin dji fly in front?
