### ISSUE TITLE
Mavic Air 2 - DJISDK 4.14-trial 2 - Waypoint Mission Not supported and SetCameraMode

### ISSUE THREAD

**Issue by dshackelford** [dji-sdk/Mobile-SDK-iOS#433]
Hello, I have a few issues with the Mavic Air 2 and DJISDK 4.14-trial2.

**1.** The sample application is not able to "prepare" a waypoint mission with the Mavic Air 2, in the "waypoint mission operator" selection.

![Simulator Screen Shot - iPhone 11 - 2021-01-14 at 12 27 58](https://user-images.githubusercontent.com/20114102/104646045-c8c4ef80-5664-11eb-81a8-2b5fde2780b9.png)

![Simulator Screen Shot - iPhone 11 - 2021-01-14 at 12 31 48](https://user-images.githubusercontent.com/20114102/104646081-d67a7500-5664-11eb-9464-0ac7ad993955.png)
![Simulator Screen Shot - iPhone 11 - 2021-01-14 at 12 31 53](https://user-images.githubusercontent.com/20114102/104646148-e8f4ae80-5664-11eb-8a4f-0fd5459d2bf9.png)
![Simulator Screen Shot - iPhone 11 - 2021-01-14 at 12 27 52](https://user-images.githubusercontent.com/20114102/104646171-f01bbc80-5664-11eb-851f-c224f846b049.png)

I believe because the Mavic Air 2 may use Version 2 of DJIWaypointMission? I tested version 2 of the waypoint operators in my own code and got a different error when trying to upload a mission.
> Aircraft's home point is not recorded. (code -5010)

**2.** Attempting to set the camera mode to shoot photos fails. `setMode` using mode `DJICameraModeShootPhoto ` returns the following error:
> Current product does not support this feature

Any information would be greatly appreciated on the operability of Mavic Air 2 with DJISDK 4.14-trial2 regarding Waypoint missions.

Environment:

DJISDK Version 4.14-trial2
Xcode 12.2
Bridge iOS App 4.4
Mavic Air 2 Firmware: 01.00.0460

Thanks!

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43100'>Zendesk ticket #43100</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry that the Mavic Air 2 is not supported by both the waypoint mission V1 and V2, limited by the drone itself.

Thanks,

Luce Luo
DJI Developer Support

**Comment by zyphs21** [comment]
@dshackelford  If you want to set the camera mode on Mavic Air 2, you should use `setFlatMode(_ mode: DJIFlatCameraMode)`  
> [Doc Reference](https://developer.dji.com/api-reference/ios-api/Components/Camera/DJICamera.html#djicamera_setflatmode_inline)

**Comment by zyphs21** [comment]
> Sorry that the Mavic Air 2 is not supported by both the waypoint mission V1 and V2, limited by the drone itself.

@dji-dev Hello, as you mention `limited by the drone itself`. Does it mean Mavic Air 2  will never support the waypoint mission even in the feature SDK version ?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43100'>Zendesk ticket #43100</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The MSDK has the ability to support the waypoint mission for the Mavic Air 2 if it has this feature in the firmware.
But now it hasn't, so no way to support it.
Sorry about it.

Thanks,

Luce Luo
DJI Developer Support

**Comment by dshackelford** [comment]
Hello, DJISDK 4.14 has been released, but the release notes do not specifically state if Mavic Air 2 is supported by either Waypoints V1 or V2. Are waypoints on the Mavic Air 2 supported in DJISDK 4.14? 

Thanks,
Dylan Shackelford

**Comment by lhuanyu** [comment]
> Agent comment from Luce Luo in [Zendesk ticket #43100](https://djisdksupport.zendesk.com/agent/tickets/43100):
> 
> Dear Customer,
> 
> Thank you for contacting DJI.
> The MSDK has the ability to support the waypoint mission for the Mavic Air 2 if it has this feature in the firmware.
> But now it hasn't, so no way to support it.
> Sorry about it.
> 
> Thanks,
> 
> Luce Luo
> DJI Developer Support

Does Air 2 support Timeline GotoAction?

**Comment by benjohnemmett** [comment]
It is frustrating that some mission actions are not supported by Mavic Air 2 but the documentation doesn't call them out. I have been developing an app primarily for use with Mavic Air 2 and was counting on using the DJIGoToAction in the mission timeline. 

Will you please update the Mavic Air 2 firmware to support the DJIGoToAction?

**Comment by schlingding** [comment]
To summarize:

The SDK supports the Mavic Air 2.

The Mavic Air 2 does not support the SDK.

Does this sound correct?

**Comment by alzin** [comment]
@dji-dev 

How did you state that the waypoint function is not supported with the Mavic Air 2 drone?
It seems that this guy was able to use it in his app (Maven App) as this video shows!!

https://www.youtube.com/watch?v=i86LnaNTe8c

**Comment by Michael-DJI** [comment]
> @dji-dev
> 
> How did you state that the waypoint function is not supported with the Mavic Air 2 drone?
> It seems that this guy was able to use it in his app (Maven App) as this video shows!!
> 
> https://www.youtube.com/watch?v=i86LnaNTe8c

this is done by the virtual stick API of MSDK, some developers like Litchi, Dronelink, Maven as well have done their mission module bases on the virtual stick
