### ISSUE TITLE
Matrice 300 RTK - 在未挂载云台相机情况下，FPV视频无法显示

### ISSUE THREAD

**Issue by dingpwen** [dji-sdk/Mobile-SDK-iOS#437]
Matrice 300 RTK - 在未挂载云台相机（挂载云台相机还未测试）

SDK：
pod 'DJI-SDK-iOS', '~> 4.14-trial1'
pod 'DJI-UXSDK-iOS-Beta-Core', '~> 0.4.0'
pod 'DJI-UXSDK-iOS', '~> 4.14-trial1'
pod 'DJIWidget', '~> 1.6.4'
pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'

开始使用DUXFPVViewController，后面又试了DUXBetaFPVWidget:
_cameraView = [[DUXBetaFPVWidget alloc]init];
    [self addChildViewController:_cameraView];
    [self.view addSubview:_cameraView.view];

都无法显示FPV视频，然后我还试了你们的demo：
@interface ViewController : DUXDefaultLayoutViewController<DJISDKManagerDelegate>

也是无法显示FPV视频！

遥控器里面的pilot app在同样的情况下是可以显示FPV视频的。pilot app应该是Android的吧。

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/43462'>Zendesk ticket #43462</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
抱歉，这边确系发现M300RTK无法同时显示H20 + FPV的情况，
这边已经将该问题升级给到工程师进一步调查。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持

**Comment by dingpwen** [comment]
已知问题，先关闭
