### ISSUE TITLE
Matrice 300 RTK - How to shoot a image?

### ISSUE THREAD

**Issue by dingpwen** [dji-sdk/Mobile-SDK-iOS#439]
When using following codes:
[DJISDKManager.product.camera setShootPhotoMode:DJICameraShootPhotoModeSingle withCompletion:^(NSError * _Nullable error) {
            if(!error) {
                [DJISDKManager.product.camera startShootPhotoWithCompletion:^(NSError * _Nullable error) {
                    if (error) {
                        [subscriber sendError:error];
                    }
                    else {
                        [subscriber sendNext:@""];
                        [subscriber sendCompleted];
                    }
                }];
            } else {
                [ZQLog bLogE:[NSString stringWithFormat:@"camera error:%@", error.description]];
            }
        }];

It tells me : does not support this feature. (code:-1013)

if only:
[DJISDKManager.product.camera startShootPhotoWithCompletion:^(NSError * _Nullable error) {
                    if (error) {
                        [subscriber sendError:error];
                    }
                    else {
                        [subscriber sendNext:@""];
                        [subscriber sendCompleted];
                    }
                }];

No error. But no callback for : 
- (void)camera:(DJICamera *_Nonnull)camera didGenerateNewMediaFile:(DJIMediaFile *_Nonnull)newMedia {
    //捕获一张照片
    [_mediaSingal sendNext:newMedia];
}

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/43818'>Zendesk ticket #43818</a>:<br><br>When using following codes:
[DJISDKManager.product.camera setShootPhotoMode:DJICameraShootPhotoModeSingle withCompletion:^(NSError * _Nullable error) {
            if(!error) {
                [DJISDKManager.product.camera startShootPhotoWithCompletion:^(NSError * _Nullable error) {
                    if (error) {
                        [subscriber sendError:error];
                    }
                    else {
                        [subscriber sendNext:@""];
                        [subscriber sendCompleted];
                    }
                }];
            } else {
                [ZQLog bLogE:[NSString stringWithFormat:@"camera error:%@", error.description]];
            }
        }];

It tells me : does not support this feature. (code:-1013)

if only:
[DJISDKManager.product.camera startShootPhotoWithCompletion:^(NSError * _Nullable error) {
                    if (error) {
                        [subscriber sendError:error];
                    }
                    else {
                        [subscriber sendNext:@""];
                        [subscriber sendCompleted];
                    }
                }];

No error. But no callback for : 
- (void)camera:(DJICamera *_Nonnull)camera didGenerateNewMediaFile:(DJIMediaFile *_Nonnull)newMedia {
    //捕获一张照片
    [_mediaSingal sendNext:newMedia];
}

**Comment by Matheus193dn** [comment]
@dingpwen Hey, can you try this?
![image](https://user-images.githubusercontent.com/26027184/107171995-bbe2b400-69f6-11eb-973e-fd8f3e2ffd36.png)

**Comment by dingpwen** [comment]
> @dingpwen Hey, can you try this?
> ![image](https://user-images.githubusercontent.com/26027184/107171995-bbe2b400-69f6-11eb-973e-fd8f3e2ffd36.png)

Thanks. setFlatMode can works, but startShootPhotoWithCompletion can not get any image by the delegate of didGenerateNewMediaFile

**Comment by dingpwen** [comment]
My codes:
if(camera.isFlatCameraModeSupported) {
            [ZQLog bLogI:@"isFlatCameraModeSupported"]; //this printed
            [camera setFlatMode:DJIFlatCameraModePhotoSingle withCompletion:^(NSError * _Nullable error) {
                if(error) {
                    [ZQLog bLogE:[NSString stringWithFormat:@"camera error:%@", error.description]];
                } else {
                    [camera startShootPhotoWithCompletion:^(NSError * _Nullable error) {
                        if (error) {
                            [ZQLog bLogE:[NSString stringWithFormat:@"camera error:%@", error.description]];
                            [subscriber sendError:error];
                        }
                        else {
                            [subscriber sendNext:@""];
                            [subscriber sendCompleted];
                        }
                    }];
                }
            }];

**Comment by Matheus193dn** [comment]
@dingpwen Did you use the latest version of firmware on both drone and remote controller?

**Comment by dingpwen** [comment]
> @dingpwen Did you use the latest version of firmware on both drone and remote controller?

Yes！All is updated to lastest version.

**Comment by dingpwen** [comment]
What a fuck, when set to setFlatMode:DJIFlatCameraModePhotoInterval , the camera can take pictures! But when setShootPhotoMode:DJICameraShootPhotoModeSingle, the camera did nothing!
