### ISSUE TITLE
phantom 3 A question is very importent to me

### ISSUE THREAD

**Issue by qw9685** [dji-sdk/Mobile-SDK-iOS#44]
Phantom 3 A is not supported playback function? If phantom 3A do not support playbackDownload function, how do I download the SD card in the video to the phone? I see Go DJI, video recording is completed, the video saved in the album, how do I do?

**Comment by dji-dev** [comment]
Hi @qw9685, the DJI Phantom 3 Advanced doesn't support playback mode(DJIPlaybackManager), you can use DJIMediaManager to download the photos and videos from the SD card instead. Hope this help, thanks!

**Comment by qw9685** [comment]
I use the way you say: in the method of retrieving the video, setMediaList settings are

 for (DJIMedia* media in self.mediaList) {
        if (media.mediaType == DJIMediaTypeMP4||media.mediaType == DJIMediaTypeMOV||media.mediaType == DJIMediaTypeM4V) { // 获取MP4文件
            self.imageMedia = media;
            break;
        }
    }

and then

- (IBAction)onShowFullImageButtonClicked:(id)sender {
    [self.showFullImageButton setEnabled:NO];
    
    WeakRef(target);
    __block NSMutableData* downloadData = [[NSMutableData alloc] init];
    
    [self.imageMedia fetchMediaDataWithCompletion:^(NSData *data, BOOL *stop, NSError *error) {
        WeakReturn(target);
        if (error) {
            ShowResult(@"ERROR: fetchMediaDataWithCompletion:. %@", error.description);
            [self.showFullImageButton setEnabled:YES];
        }
        else {
            [downloadData appendData:data];
            if (downloadData.length == target.imageMedia.fileSizeInBytes) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    WeakReturn(target);
//                    [target showPhotoWithData:downloadData];
                    ShowResult(@"正在写入文件");
                [downloadData writeToFile:[NSHomeDirectory() stringByAppendingPathComponent:@"Documents/audio.mp4"] atomically:YES];
                    [self.showFullImageButton setEnabled:YES];
                    
                });
            }
        }
        [self.showFullImageButton setEnabled:YES];
    }];
}

**Comment by qw9685** [comment]
Is this method right? Why is it very slow..

**Comment by dji-dev** [comment]
Hi @qw9685, yes, it would become slow when you download video files (Especially big size) from the drone.
