### ISSUE TITLE
DJI Bridge App not working on iOS 10

### ISSUE THREAD

**Issue by nithinreddygaddam** [dji-sdk/Mobile-SDK-iOS#45]
Hi, 

I upgraded to iOS 10 on my iPad and the DJI Bridge app stopped working. It connects to the RC (showing green light on the RC side)... but not able to connect to the iPhone which is running my app.. All 3 devices are connected to the same WiFi.. iPhone and iPad are upgraded to iOS 10 and the macOS to Sierra with Xcode 8

**Comment by dji-dev** [comment]
Hi, the DJI Bridge app works well with iOS 10 + MacOS Sierra with Xcode 8, please check your WiFi connection and press the "link Reset" button in the app and try again. You can use the `ping` command in Terminal to test the WiFi connection between your Mac and the DJI Bridge app , hope this help!

**Comment by nithinreddygaddam** [comment]
It works fixed the issue..
