### ISSUE TITLE
iOS 10 Support

### ISSUE THREAD

**Issue by brianantonelli** [dji-sdk/Mobile-SDK-iOS#46]
I'm unable to run the a sample app on iOS 10 in both the simulator and on a iPhone 7. It appears to be failing during the application registration call. I'm on 10.0.2 using the 3.3 DJI SDK.

On an iPhone 7 running iOS 10.0.2 I get the `REGISTRATION_INVALID_METADATA` error.

If I run the same code on the iOS 10 Simulator I get the `REGISTRATION_DEVICE_NOT_MATCH` error.

This error occurs when I invoke the register method (`[DJISDKManager registerApp:appKey withDelegate:self];`)

It's also worth nothing I see this error when running on the device: `Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement`

My plist has:
- Supported external accessory protocols (com.dji.video, com.dji.protocol, com.dji.common)
- App Transport Security Settings: Allow Arbitrary Loads: YES

I tried all the suggestions from Issue #33 like changing the bundler identifier, etc.

**Comment by dji-dev** [comment]
Hi @brianantonelli , thanks for your feedback! We are investigating this issue now, will get back to you  once we make some progress.

**Comment by brianantonelli** [comment]
This is definitely an iOS 10 issue, I just verified the same code runs fine and successfully registers the app on iOS9

**Comment by dji-dev** [comment]
Hi @brianantonelli, please try to turn on the **Data Protection** in Capabilities of your Xcode project using Xcode 8. Then change the project's Bundle Identifier to a different one and try again.  Remember to do a clean test (Delete the app on your iPhone 7, clean the project and rebuild it to install on your device) Let us know if it helps. Thanks!

**Comment by dji-dev** [comment]
@brianantonelli Here is the screenshot for you to check the settings: ![screen shot 2016-09-30 at 2 36 26 pm](https://cloud.githubusercontent.com/assets/11869194/18982793/49e858fe-871b-11e6-8ec4-8907e86771b3.png)

**Comment by Brew-Fox** [comment]
Data Protection and deleting app off simulator worked for me. As bundle id is tried to so many things I cant change it. Glad I was able to navigate around that. 

016-09-30 13:33:23:521 xxxx DJIManager: DJI SDK Registered
2016-09-30 13:33:23:522 xxxx DJIManager: Connected to product? Simulator

**Comment by brianantonelli** [comment]
Enabling Data Protection fixed the issue on the simulator and my iPhone. BTW, I didn't have to change my bundle identifier. Thanks for the quick help, @dji-dev! 👍
