### ISSUE TITLE
获取时间戳问题

### ISSUE THREAD

**Issue by qw9685** [dji-sdk/Mobile-SDK-iOS#47]
我是说我现在做的是音频和视频合成，需要DJI拍摄视频的时间戳，我看你们提供的时间戳是秒级别的有没有毫秒级别的时间戳，否则我这里对时是很麻烦谢谢

**Comment by dji-dev** [comment]
Hi @qw9685, where do you find the seconds level of timestamp in our DJI SDK? Could you tell us? Thanks!

**Comment by qw9685** [comment]
在DJIMedia中的

 *  Returns the time when the media file was created as a string in
 *  the format "yyyy-MM-dd HH:mm:ss".
 */
@property(nonatomic, readonly) NSString *_Nonnull timeCreated;

**Comment by dji-dev** [comment]
Hi @qw9685 , thanks for your feedback. Currently, we don't provide the milliseconds level of time stamp, the `timeCreated` property you get is seconds level. Maybe you can try to get the iOS system's time when this `- (void)camera:(DJICamera *_Nonnull)camera didGenerateNewMediaFile:(DJIMedia *_Nonnull)newMedia;` DJICameraDelegate method get invoked? Hope this hope, thanks!
