### ISSUE TITLE
Is it possible to make the developed app standalone without first tethering the drone with DJI GO 4 app?

### ISSUE THREAD

**Issue by alzin** [dji-sdk/Mobile-SDK-iOS#473]
When pairing a drone with a developed app using the SDK, you have to pair it with DJI GO 4 once, so I would like to improve it so that it can be paired only with the app that I am developing!

Are there any steps to handle that or not?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49437'>Zendesk ticket #49437</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The MSDK provide the pair method to pair independently, please check if any help for you.
https://developer.dji.com/api-reference/ios-api/Components/RemoteController/DJIRemoteController.html
 ![](https://djisdksupport.zendesk.com/attachments/token/HHQYtH9nEtVYUJkQ6p2hxT5nb/?name=inline2118770559.png)​
​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/HHQYtH9nEtVYUJkQ6p2hxT5nb' target='zd_attach'>inline2118770559.png</a>
<br><p><em><small>°°°</small></em></p>
