### ISSUE TITLE
iOS SDK is missing 4 constants in the DJIFlightControllerFlightMode enum that are found in the Java SDK...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#48]
The ordinal values (from the Java SDK):
   PANO(28),
   Farming(29),
   FPV(30),
   ForceLanding(33)

These are not found in the iOS SDK.  I am using the latest version (v 3.3).  The header file in question is DJIFlightControllerBaseTypes.h.

**Comment by dji-dev** [comment]
Hi @jgrantr, thanks for your feedbacks. We will fix this issue in the next SDK version release.

**Comment by XietongLU** [comment]
Fixed.
