### ISSUE TITLE
didGenerateNewMediaFile does not fire on XT Camera

### ISSUE THREAD

**Issue by tudorDME** [dji-sdk/Mobile-SDK-iOS#49]
We know the XTs are new-ish and the problem could be in firmware but it could also be an issue in the SDK. We didn't see any documentation anywhere that it shouldn't work the same as any other camera. 

P3/4, X3 and X5 all work as expected and return a valid DJIMedia object.

SDK 3.3

**Comment by dji-dev** [comment]
Hi @tudorDME, thanks for your feedbacks. Currently, the XT camera doesn't support fetching DJIMedia object, we will improve the documentation to mention this in the next SDK version.

**Comment by mabrowning** [comment]
We are affected negatively by the same issue! Is there any workaround other than calling FetchMediaList every few seconds?

**Comment by XietongLU** [comment]
It is a firmware issue.
