### ISSUE TITLE
Matrice 300 RTK + Zenmuse P1 Problems with RTK

### ISSUE THREAD

**Issue by LuisVargasVic** [dji-sdk/Mobile-SDK-iOS#492]
Hello, @dji-dev

I have noticed some issue with the location of the drone connected with RTK with the Matrice 300 RTK and DJISDK 4.15.1:

1. Connect Matrice 300 RTK
3. Connect with Network or Base Station the RTK
5. When the drone take off the location is not being updated

It works perfectly with Phantom 4 RTK and Matrice 210 RTK V2

I have PPK connected because it's giving me the rover logs (No code needed)

My assumption is that both of them can't be working at the same time

**Comment by LuisVargasVic** [comment]
Hello, @dji-dev 

Greetings.
In the DJIFlightControllerState

/**
 *  Aircraft's current GPS signal quality.
 */
@property(nonatomic, readonly) DJIGPSSignalLevel GPSSignalLevel;

I found out the error, the gps signal is lost when you get fix for RTK custom network

Regards.

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/52323'>Zendesk ticket #52323</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

Could you provide below detailed information for us further check:

1. Aircraft type and firmware version .
2. Remote controller firmware version.
3. IOS system version.
4. MSDK version.
5. Your **testing steps** and **related pictures or videos.**

Thank you for your understanding and support, hope you have a nice day.

Best Regards,

DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
