### ISSUE TITLE
Mission start failure when the simulator is active due to obstacles

### ISSUE THREAD

**Issue by shmuelk** [dji-sdk/Mobile-SDK-iOS#496]
I am trying to start a DJIWaypointV2Mission using the DJIWaypointV2Mission Operator of the iOS Mobile SDK.

The mission uploads correctly and I see the state of the mission operator go to Ready to Execute.

When I call startMission(), the mission gets interupted with an error, with a domain of DJISDKWaypointV2ErrorDomain and a code of 9058. The message associated with this error is "The waypoint mission is interrupted by avoidance."

Why is the obsticle avoidance active when the simulator is active? Disabling all of the directions of the obsticle avoidance in the DJI Pilot application doesn't help here.Would resuming the mission help here?

I will note that when trying to fly the drone manually, indoors, when the simulator is active, one hears a lot of beeps. These beeps can only stop when one disables the obsticle avoidance in all directions (horizontal, upward, and downward).

Shmuel Kallner
--

**Comment by shmuelk** [comment]
Thank you VERY much.

Using your demo program pointed us in the correct direction.

We were apparently trying to fly too low. We were using the altitude from a FlightControllerLocation listener. It was some 30-40 cm low.

I'll point out that even the Flight controller delegate returns an altitude that is somewhat low (about 10-15 cm)

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/55340'>Zendesk ticket #55340</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

You are welcome, we are glad we could help.

Have a nice day!

Best Regards,
DJI SDK Support Team
<br><p><em><small>°°°</small></em></p>
