### ISSUE TITLE
didFinishMissionExecution returns immediately with error but mission still flown. 

### ISSUE THREAD

**Issue by str11ngfello** [dji-sdk/Mobile-SDK-iOS#50]
With the update to the new SDK we're seeing an issue where, in previously working code, a didFinishMissionExecution callback is called immediately after a mission begins.  The error passed to us in the callback is "Mission is stopped by user. Code: -5036.  The mission, however, will still be fully executed.  We can reproduce this in simulator and on Phantom 4.   Since we didn't stop the mission on the RC we really have no explanation for this behavior other than to post an issue.  Since the mission is still flown it would seem that the error is being falsely reported?

The errors happens a second or two after mission start with DJIMissionManager.prepareMission.

**Comment by andrew-barinov-dji** [comment]
Hi there, thanks for letting us know about this. Can you share what type of mission you're running when you get this error?

**Comment by str11ngfello** [comment]
Thanks for the quick response.  Absolutely.  This is code that is tied to a button press on an action sheet.  It creates a simple waypoint mission, prepares it and starts it.   The mission will be flown but during the start of the mission we get the callback with error saying user stopped the mission.

func actionMore() {
        let googleAnalyticsAction = "Action - More"
        GoogleAnalytics.sharedInstance.trackEvent(googleAnalyticsAction, label: "Open")
        let actionSheet = UIAlertController(title: Constants.App.About, message: nil, preferredStyle: .ActionSheet)
        actionSheet.addAction(UIAlertAction(title: "cancel".localized, style: .Cancel, handler: { (action) -> Void in
            GoogleAnalytics.sharedInstance.trackEvent(googleAnalyticsAction, label: "Cancel")
        }))
        actionSheet.addAction(UIAlertAction(title: "Test LCMC".localized, style: .Default, handler: { (action) -> Void in
            let missionManager = DJIMissionManager.sharedInstance()
            let waypointMission = DJIWaypointMission()
            if let aircraftLocation = FlightDirector.sharedInstance.telemetry.aircraftZLoc.value?.loc.coordinate {
                let height: Float = 30.0
                
                waypointMission.gotoFirstWaypointMode = .Safely
                waypointMission.exitMissionOnRCSignalLost = false
                
                waypointMission.removeAllWaypoints()
                waypointMission.maxFlightSpeed = 10.0
                waypointMission.autoFlightSpeed = 5.0
                waypointMission.finishedAction = DJIWaypointMissionFinishedAction.GoHome
                waypointMission.headingMode = DJIWaypointMissionHeadingMode.Auto
                waypointMission.flightPathMode = DJIWaypointMissionFlightPathMode.Normal
                //DJIWaypointMissionAirLineCurve
                var point1: CLLocationCoordinate2D
                var point2: CLLocationCoordinate2D
                var point3: CLLocationCoordinate2D
                var point4: CLLocationCoordinate2D
                let DEGREE_OF_THIRTY_METER:Double = (0.0000899322 * 3)
                point1 = CLLocationCoordinate2DMake(aircraftLocation.latitude + DEGREE_OF_THIRTY_METER, aircraftLocation.longitude)
                point2 = CLLocationCoordinate2DMake(aircraftLocation.latitude, aircraftLocation.longitude + DEGREE_OF_THIRTY_METER)
                point3 = CLLocationCoordinate2DMake(aircraftLocation.latitude - DEGREE_OF_THIRTY_METER, aircraftLocation.longitude)
                point4 = CLLocationCoordinate2DMake(aircraftLocation.latitude, aircraftLocation.longitude - DEGREE_OF_THIRTY_METER)
                let wp1: DJIWaypoint = DJIWaypoint(coordinate: point1)
                wp1.altitude = height
                let wp2: DJIWaypoint = DJIWaypoint(coordinate: point2)
                wp2.altitude = height
                let wp3: DJIWaypoint = DJIWaypoint(coordinate: point3)
                wp3.altitude = height
                let wp4: DJIWaypoint = DJIWaypoint(coordinate: point4)
                wp4.altitude = height
                waypointMission.addWaypoint(wp1)
                waypointMission.addWaypoint(wp2)
//                waypointMission.addWaypoint(wp3)
//                waypointMission.addWaypoint(wp4)
                missionManager?.delegate = self
                
 
         
                missionManager?.prepareMission(waypointMission, withProgress: {
                    [weak self] (progress: Float) -> Void in
                        print(progress)
                    }, withCompletion:{[weak self] (error: NSError?) -> Void in
                        
                        
                            print("starting mission")
                            missionManager?.startMissionExecutionWithCompletion { (startMissionExecutionError: NSError?) in
                                if let startMissionExecutionErrorValid = startMissionExecutionError {
                                    FlightDirector.sharedInstance.statusFlash.value = FlightDirectorStatus(disposition: .Danger, message: startMissionExecutionErrorValid.localizedDescription)
                                    FlightDirector.sharedInstance.disengage(.DJIMissionManagerError)
                                    return
                                }
                            }
            
                    })
            }}))

**Comment by andrew-barinov-dji** [comment]
Hi there, thanks for that info. One more question, the SDK will sometimes return that error if the flight controller mode is manually changed while the mission is running, is it possible for you to check if this happens in your app?

One way to check this is via the flight controller delegate method, `flightController:didUpdateSystemState:`, which provides a `DJIFlightControllerCurrentState` that contains a property `flightMode`. If you're using the iOS simulator, you can print the mode: `print(\(state.flightMode))`, or if you're doing this on a live flight then compare the current mode to the previous mode and display an alert view in your app if it changes. Let us know if you have a chance to check this. We will also look into this further. Thanks again.

**Comment by str11ngfello** [comment]
Thanks for the tip.  We did some logging to show the sequence of events.   

DJIFlightControllerFlightModeGPSAtti = 6
DJIFlightControllerFlightModeAutoTakeOff = 11
DJIFlightControllerFlightModeGPSWaypoint = 14
DJIFlightControllerFlightModeGoHome = 15

We printed the flight mode enum as our mission uploaded, started, and encountered the error.  Is it not strange that we are starting in 6, which is Atti mode?  Although the error callback happens when we are in state 11 (auto take off), maybe the trigger is delayed from starting in 6.  This test is done using the DJI simulator by the way.

Log: 
State = 6
0 mission upload
State = 6
State = 6
0.333333 mission upload
State = 6
State = 6
0.666667 mission upload
State = 6
State = 6
1.0
starting mission
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 6
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
State = 11
didFinishMissionExecution triggered in ModesViewController - ERROR User did stop mission
State = 11
State = 11
State = 11
State = 11
...

**Comment by Brew-Fox** [comment]
I too am seeing this behavior. After missionManager.startMissionExecution is successful, periodically we see missionManager(_ manager: DJIMissionManager, didFinishMissionExecution) delegate fire before the drone has lifted off.  Can happen at start or in the middle of a waypoint mission.

**Comment by XietongLU** [comment]
Mission has been refactored in 4.0.
