### ISSUE TITLE
Problems fetching media

### ISSUE THREAD

**Issue by gi-ba** [dji-sdk/Mobile-SDK-iOS#512]
Hi DJI team,

I am using TaskScheduler to fetch media list and fetchThumbnail(_:) function of DJIMedia object but it takes a little bit of time due to the FIFO. I also use DJIMediaManager to play video. App written in Swift.

1. Is there any solutions to fetch media list and its thumbnails faster? the DJI Go 4 seems to display the media list immediately with all the thumbnails fetched 
2. If Task Scheduler has pending tasks, I cannot play video because the camera appears to be busy ?
3. The function fetchPreview(_:) is used only for image to fetch thumbnail with better quality. Do we have any function like this for video ?

Thanks,
Giba

**Comment by DJI-William** [comment]
1. The speed of fetch media list cannot be control by SDK. A better suggestion is using high speed SD card in reading and writing.
2. The video stream will be stoped while you are fetching photos(busy).
3. There is no such method for video.
