### ISSUE TITLE
Please consider removing space in "Sample Code" directory

### ISSUE THREAD

**Issue by str11ngfello** [dji-sdk/Mobile-SDK-iOS#52]
Please consider renaming the "Sample Code" directory to remove the space. Why? When using cocoa pods to pull in your SDK, we cannot jump to definition because Xcode will not properly locate the framework located in Sample Code directory.  It compiles and builds just fine but navigating DJISDK symbols is impossible unless we directly embed it into our project.   Our other option is to rename Sample Code to SampleCode in our project after running pod update.. but that's not convenient and has to be redone after each pod update.

Thanks!

**Comment by oliverou** [comment]
Hi @str11ngfello, thanks for your feedback, we will fix this issue by removing the "Sample Code" folder in the next version SDK release soon.

**Comment by dji-dev** [comment]
Hi @str11ngfello, we have just released the SDK 3.4, the **DJISDK.framework** file has been put in the "Framework" folder, which should resolve your issue now. Please get the lastest SDK from DJI Developer website and try again. Thanks!
