### ISSUE TITLE
Crashlytics GetIsFCConnectedHandle

### ISSUE THREAD

**Issue by LuisVargasVic** [dji-sdk/Mobile-SDK-iOS#522]
Hello, DJI team

Greetings.
I have a lot of crashes in the DJISDK Pod
The must recurrent one is related to `GetIsFCConnectedHandle(unsigned long long) + 51100`
Is anyone able to avoid this issue? I'm using this pod:

`pod 'DJI-SDK-iOS', '~> 4.16'`

That's the must concerning also I have others here, not sure how to mitigate them because the DSYM is not available and was mentioned that will not be shared to the community

<img width="562" alt="Screen Shot 2022-06-07 at 11 18 45" src="https://user-images.githubusercontent.com/10502482/172431473-c6b8de4b-2f29-4a6f-a3b2-31f5bd017ce2.png">

**Comment by DJI-William** [comment]
![image](https://user-images.githubusercontent.com/77274755/172578301-a8648f67-527d-40c3-b20f-5c030d3fad59.png)
Have you poded the DJIFlySafeDatabaseResource in?

**Comment by LuisVargasVic** [comment]
Hello, yes I have the same:
pod 'DJIWidget', '~> 1.6.7'
pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.18'
pod 'DJI-SDK-iOS', '~> 4.16.1'
pod 'DJINetworkRTKHelper', '~> 2.0.2'

The most concerning of the issues is the one related to `GetIsFCConnectedHandle(unsigned long long) + 51100`
Any feedback on that one will help

**Comment by LuisVargasVic** [comment]
<img width="1258" alt="Screen Shot 2022-07-07 at 9 15 08" src="https://user-images.githubusercontent.com/10502482/177795532-30bccca2-2374-4c58-9e3a-275d239b2118.png">

Here is the issue in more detail

**Comment by DJI-William** [comment]
We have released the iOS MSDK 4.16.1, please have a try. We need an exact reproduce method.

**Comment by LuisVargasVic** [comment]
Hello, DJI

I'm currently using 4.16.1, the issue was present since 4.15 it only happens when connecting the drone Matrice 300 RTK with any other drone it doesn't happen, the reproduce method is tricky it happens when making the first connection with the drone and the application breaks, but it's hard to reproduce and it appears randomly.

<img width="1224" alt="Screen Shot 2022-07-11 at 15 28 59" src="https://user-images.githubusercontent.com/10502482/178352489-784ea345-ac89-41f6-8c38-201589a05191.png">
<img width="1224" alt="Screen Shot 2022-07-11 at 15 28 28" src="https://user-images.githubusercontent.com/10502482/178352396-3a7d0f00-6103-416f-97db-d0dfec8bb2bc.png">

**Comment by DJI-William** [comment]
Dear Client
Thank you for contacting DJI.

We have fixed this issue and it is merged into iOS 4.16.2 version.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
