### ISSUE TITLE
connectToBaseStation expects Int32 but received basestation ID is UInt and outside accepted range 

### ISSUE THREAD

**Issue by vsars7** [dji-sdk/Mobile-SDK-iOS#523]
Hi, 

We are using DJI iOS MSDK 4.16 and trying to connect to the D-RTK2 base station. 

The received base station id is a UInt type with value -> 4,181,xxx,xxx 

However, we can only pass an Int32 when calling [connectToBaseStation](https://developer.dji.com/api-reference/ios-api/Components/RTK/DJIRTK.html?search=connectto&i=0&#djirtk_connecttobasestation_inline
)()

I see that the accepted argument type for base station ID is a [long on Android](https://developer.dji.com/api-reference/android-api/Components/RTK/DJIRTK.html?search=connectto&i=0&#djirtk_connecttobasestation_inline
)  

Is this a known issue or are we doing something wrong? 

Thanks,
vsars

**Comment by DJI-William** [comment]
It is a bug, we will change the int to long in the next iOS version.

**Comment by DJI-William** [comment]
The bug is fixed, we change the Int to Long now. 4.16.2 version will include this fix.
