### ISSUE TITLE
Support for RTMPS

### ISSUE THREAD

**Issue by Laiteux** [dji-sdk/Mobile-SDK-iOS#528]
Hey,

I'm not sure I'm on the right repo for this issue, excuse me if not and please redirect me.

Currently, the iOS app only seems to support `rtmp://` URI schemes.

However, some apps like Telegram only provide a `rtmps://` URL, forcing us to use "restreaming" services such as https://restream.io, which provides a `rtmp://` URL, just to redirect the stream to Telegram or whatever other app using RTMPS.

Would it be possible to add support for such a feature? I'm not sure how hard this would be, considering I'm guessing the "s" suffix implies some extra encryption or whatever, but yeah.

Thanks a lot!

**Comment by DJI-William** [comment]
I am sorry that our iOS MSDK is not going to support any new live streaming protocols in the future. The only way for you is to write your own RTMPS live streaming feature.
