### ISSUE TITLE
How to use DJIDiagnostics?

### ISSUE THREAD

**Issue by lygialiem** [dji-sdk/Mobile-SDK-iOS#529]
Hi DJI Team.

I wonder how to use or get info form this class DJIDiagnostics? I did search all sdk but got no where this class is used?

Best Regard. Thank you very much.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/68004'>Zendesk ticket #68004</a>:<br><br>You can set the listening to diagnostic information through product:didUpdateDiagnosticsInformation, and then you can receive DJIDiagnostics in the callback.
<br><p><em><small>°°°</small></em></p>
