### ISSUE TITLE
Crash inside DJISDK networking code...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#53]
iOS Device: iPad Air 2
Xcode version: 7.3.1
iOS version: 9.3.5
DJI SDK version: 3.3

I have attached a crash log.  I didn't get symbols for the DJISDK methods it was inside when it crashed, but it looks like a dictionary is being created with either a key, or more likely a value, that is nil, and it looked to be part of an NSURLSession networking task.

The drone was just told to run a mission when it crashed. Please let me know if you need anything else from me, but it crashed inside thread 12, and the last 2 non-Foundation symbols are in DJISDK.

[droneCrashLog.crash.zip](https://github.com/dji-sdk/Mobile-SDK-iOS/files/551963/droneCrashLog.crash.zip)

**Comment by oliverou** [comment]
Hi @jgrantr, thanks for your feedback. Does this crash issue reproducible?  If so, could you tell us what's the steps to reproduce it? Thanks!

**Comment by dji-dev** [comment]
Hi @jgrantr, after investigating this issue, we have found the problem, will fix it in the next SDK version release soon. Thanks for your feedbacks.

**Comment by dji-dev** [comment]
Hi @jgrantr, we have published the SDK 3.4, this issue you mentioned above has been fixed, please get the latest sdk and try again, thanks!
