### ISSUE TITLE
How to get warning level in DJIDiagnostics class?

### ISSUE THREAD

**Issue by lygialiem** [dji-sdk/Mobile-SDK-iOS#530]
Hi team.

Currently I make pre-flight checker features, in document i can not see warning level in every diagnostic but the DJIDiagnosticsDeviceHealthInformationWarningLevel. But DJIDiagnosticsDeviceHealthInformationWarningLevel is just worked if the DJIDiagnostics.code == 0 and we have to get code from healthyInformation.informationCode in DJIDiagnostics. By the way, how do we know code in healthyInformation.informationCode is referring to?

Best Regard, thank you very much.

**Comment by DJI-William** [comment]
The DJIDiagnosticsDeviceHealthInformationWarningLevel only works for M300RTK. The old diagnostic system does not have any warning level logic.
![image](https://user-images.githubusercontent.com/77274755/181150007-397733b9-2052-4743-81c4-93d6b7b3f40b.png)

**Comment by lygialiem** [comment]
Hi team.

Thank you for your response. I will define this logic myself. 

Best Regard.
