### ISSUE TITLE
Cannot get values using DJIGimbalParamAttitudeInDegrees

### ISSUE THREAD

**Issue by Filet-0-Fish** [dji-sdk/Mobile-SDK-iOS#531]
Hello. I have reported this problem on the forum, but since I could not find a solution, I am posting it here.
https://forum.dji.com/forum.php?mod=viewthread&tid=269885

**What I want to do**
- I want to get the roll, pitch, and yaw of the gimbal (camera) and output the values on the screen.

**The code**
```Swift
let gimbalAttitudeKey = DJIGimbalKey(param: DJIGimbalParamAttitudeInDegrees)
DJISDKManager.keyManager()?.startListeningForChanges(on: gimbalAttitudeKey!, withListener: self, andUpdate: {(oldValue: DJIKeyedValue?, newValue: DJIKeyedValue?) in
if newValue != nil {
    let gimbalAttitudes = newValue!.value! as! DJIGimbalAttitude

    //Display the value in the label text
    self.RollLabel.text = "Roll: \(gimbalAttitudes.roll)"
    self.PitchLabel.text = "Pitch: \(gimbalAttitudes.pitch)"
    self.YawLabel.text = "Yaw: \(gimbalAttitudes.yaw)"
  }
})
```

**The problem that is occurring**
- [The official documentation](https://developer.dji.com/api-reference/ios-api/Components/KeyManager/DJIGimbalKey.html) says that the type of DJIGimbalParamAttitudeInDegrees is DJIGimbalAttitude.
- However, I get an error in the `let gimbalAttitudes = newValue!.value! as! DJIGimbalAttitude` section.
- The error says it cannot be cast.

I hope this issue will be resolved soon.

**Comment by DJI-William** [comment]
I suggest you an easier way of doing this.
Instead of using key, you can just use [delegate](https://developer.dji.com/api-reference/ios-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_delegate_inline) of flightController. Inside the delegate, find flightController:didUpdateState and you can access [attitude](https://developer.dji.com/api-reference/ios-api/Components/FlightController/DJIFlightController_DJIFlightControllerCurrentState.html#djiflightcontroller_djiflightcontrollercurrentstate_attitude_inline). It is consisting of 3 double values.

**Comment by Filet-0-Fish** [comment]
Thanks for the reply, DJI-William.
I know what I can get from DJIFlightControllerState is the attitude of the aircraft.
I want to get where the camera is pointing.
Maybe I am just missing something and can also get the gimbal attitude from DJIFlightControllerState?

**Comment by Filet-0-Fish** [comment]
Thanks for the reply, DJI-William.
I know what I can get from DJIFlightControllerState is the attitude of the aircraft.
I want to get where the camera is pointing.
Maybe I am just missing something and can also get the gimbal attitude from DJIFlightControllerState?

**Comment by Filet-0-Fish** [comment]
(Sorry, I am new to Github and closed it by mistake.)

**Comment by DJI-William** [comment]
I am very sorry, I have missed reading, You wan to get the gimbal attitude. This is the same thing. There is a delegate in Gimbal class, you can get DJIGimbalState through this, and you can get DJIGimbalState.attitudeInDegrees. It is a struct and contains 3 float numbers which represent 3 angles.

**Comment by Filet-0-Fish** [comment]
Thanks for telling me.
I am not sure how to get the DJIGimbalState from the Gimbal delegate.
Should I delegate the Gimbal class to the view controller class?
I would appreciate it if you could provide a sample code.

**Comment by DJI-William** [comment]
It is in the Sample demo.
Link：https://github.com/dji-sdk/Mobile-SDK-iOS/blob/master/Sample%20Code/ObjcSampleCode/DJISdkDemo/Demo/Gimbal/PushInfo/GimbalPushInfoViewController.m

**Comment by Filet-0-Fish** [comment]
Thanks for the sample code.
But sorry, do you have this sample in swift version instead of objective-c?

**Comment by DJI-William** [comment]
I am sorry, I didn't find it in the Swift demo.

**Comment by Filet-0-Fish** [comment]
I was able to get it to work by adding this code to the ViewController!
Thanks so much for your support!

```Swift
class DroneConnectionView: ... DJIGimbalDelegate {
    override func viewDidLoad() {
        super.viewDidLoad()
        ...
        let gimbal = fetchGimbal()
        if gimbal != nil {
            gimbal?.delegate = self
        }
    }

    func fetchGimbal() -> DJIGimbal? {
        guard let product = DJISDKManager.product() else {
            return nil
        }
        
        if product is DJIAircraft || product is DJIHandheld {
            return product.gimbal
        }
        return nil
    }
    
    func gimbal(_ gimbal: DJIGimbal, didUpdate state: DJIGimbalState) {
        self.RollLabel.text = "Roll: \(state.attitudeInDegrees.roll)"
        self.PitchLabel.text = "Pitch: \(state.attitudeInDegrees.pitch)"
        self.YawLabel.text = "Yaw: \(state.attitudeInDegrees.yaw)"
    }
}
```
