### ISSUE TITLE
Prevent DJI Fly Auto Launching

### ISSUE THREAD

**Issue by brien-crean** [dji-sdk/Mobile-SDK-iOS#533]
Is there a way to prevent DJI Fly from Auto launching when the DJI Mini 2 is connected?

Or is there a way for us to specify that our app with the DJI MSDK should launch when the Mini 2 is connected?

It's not the best user experience to have to close DJI Fly and then open our app every time the drone is connected.

Thanks

**Comment by DJI-William** [comment]
I am sorry, we have ask the FLY team and they said they have done some settings in MFi to make the auto launching for DJI FLY. There is no way for outsiders to switch it off.
