### ISSUE TITLE
Please remove bitcode support in FFmpeg as soon as possible

### ISSUE THREAD

**Issue by fanbaoyuanbees360** [dji-sdk/Mobile-SDK-iOS#537]
[https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes](url)

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

pod 'DJIWidget', '~> 1.6.6 contains FFmpeg.framework, please remove it.

The App Store Connect rejected error:
ITMS-90482: Invalid Executable - The executable 'xxx.app/Frameworks/FFmpeg.framework/FFmpeg' contains bitcode.

**Comment by DJI-William** [comment]
已经和研发提单，现在iOS的人力非常不充足，考虑到你的情况我会让他优先解决你的问题的。

**Comment by pskow** [comment]
I've also encountered this issue, is there any ETA for it?

**Comment by DJI-William** [comment]
This broblem will be solved very soon in iOS 4.16.2. About in 1-2 weeks.

**Comment by DJI-William** [comment]
Already fixed, we are waiting for other bugs to fix and release the new SDK.

**Comment by DJI-William** [comment]
4.16.2 is released, please find the latest DJIWidget and iOS MSDK Github.
