### ISSUE TITLE
DJIWaypointMissionOperator block Camera functions?

### ISSUE THREAD

**Issue by lygialiem** [dji-sdk/Mobile-SDK-iOS#538]
Hi DJI Team.

Currently I'm working on Waypoint mission. Everything's working fine. But when I start Waypoint Mission and stop or mission is finished. Camera is not working. I mean DJICameraParamMode or DJICameraParamFlatMode key and ... are not working anymore. I can not switch to video record or photo shooting or all camera functions for FPV mode aren't working. I knew that in DJIWaypoint has shootPhotoTimeInterval and shootPhotoDistanceInterval. I think they both maybe related to Camera functions. Don't know how to fix that. Could you give me some suggestions.

Best Regard. Thank you very much.

**Comment by DJI-William** [comment]
No other people report any similar issues before. The DJIWaypointMissionOperator will never bock any camera functions. So what hapeens if you switch to shoot photo mode and call startShootPhoto function after the waypointMission? What is the callback return?
