### ISSUE TITLE
excessive debug info in VideoPreviewer 3.4...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#54]
iOS Device: iPad Air 2
Xcode version: 7.3.1
iOS version: 9.3.5
DJI SDK version: 3.4

When using the VideoPreviewer framework from the 3.4 release, there is a TON of debug logging being generated by ffmpeg.  I tracked it down to the [VideoFrameExtractor setupExtractor]. In version 3.3, that method had the following call:

        av_log_set_level(AV_LOG_QUIET);

That line is missing from the 3.4 release.  Can you please fix that?

**Comment by jgrantr** [comment]
#55 Pull request that re-adds the missing line

**Comment by oliverou** [comment]
Hi @jgrantr, thanks for the feedbacks, already merge your pull request.
