### ISSUE TITLE
Mavic 2 Enterprise Advanced drone model isn't included in list of devices

### ISSUE THREAD

**Issue by YaroTs** [dji-sdk/Mobile-SDK-iOS#541]
Sdk version: 4.16.2

There are following comments in api documentation for `DJICamera` and `DJILens` classes:
`For Zenmuse H20 Series and Mavic 2 Enterprise Advanced, please use class DJILens.`

But I don't see such model inside `DJIAircraft` or `DJICameraDisplayNames` strings:

There are only the following models:

`public let DJIAircraftModelNameMavic2Enterprise: String`
`public let DJIAircraftModelNameMavic2EnterpriseDual: String`

Is DJIAircraftModelNameMavic2Enterprise == Mavic 2 Enterprise Advanced or am I missing something?

**Comment by DJI-William** [comment]
Yes, it is not supported by iOS and only supported by Android MSDK.

**Comment by YaroTs** [comment]
Does it make sense to correct iOS docs and exclude this model from methods description in this case?

**Comment by DJI-William** [comment]
Yes, it is. I think the dev team just copy the doc from Android MSDK doc. Anyway just ignore it for now.
