### ISSUE TITLE
MediaManager and playVideo function

### ISSUE THREAD

**Issue by lbujnak** [dji-sdk/Mobile-SDK-iOS#543]
Hi ! 

I'm working on a video preview but I'm stuck with one problem. When I play video and after completion I pause it, cause it would play for its own, I won't get update of view... I have same view just like in sample, but I would like to add like, some preview of video before the play starts.

Another problem is, that after switching between videos, the video feed on new video is for first time I press play button same, as on previous one. Anyone has some solution please?

**Comment by DJI-William** [comment]
First of all, iOS MSDK will not update anymore unless there is a serious bugs there. So I strongly suggest you switch to Android MSDK. There is a preview proerty in the [mediaFile](https://developer.dji.com/api-reference/ios-api/Components/Camera/DJIMediaManager_DJIMedia.html#djimediamanager_djimedia_preview_inline).  You have to make sure you are playing the correct mediaFile.

**Comment by lbujnak** [comment]
And how can I use android sdk in Xcode ?

**Comment by DJI-William** [comment]
Xcode is an IDE for iOS, you need to use Android Studio.

**Comment by lbujnak** [comment]
Yea I understand, but how can I make iOS app through android studio ? If I would like to build an android app, I would already use android studio.

**Comment by DJI-William** [comment]
The Android SDK will make an Android app. We will only update Android SDK in the future. iOS SDK will not be updated. So even you find some bugs, maybe we won't fix it. That is why I suggest you switch SDK/app.

**Comment by lbujnak** [comment]
But I need to build an iOS app .. :/

**Comment by DJI-William** [comment]
It is just a suggestion, you can ignore it if you just want to use an iOS app. But will face with this issue.

**Comment by lbujnak** [comment]
So i figured out how to use Android sdk for iOS. Use cross platform dev - CodenameOne

**Comment by yarosts** [comment]
> So i figured out how to use Android sdk for iOS. Use cross platform dev - CodenameOne

@lbujnak Could you please share your experience with using Android sdk on iOS? 

iOS lib hasn't received updates for years, so it would be great to know if there is some working alternative
