### ISSUE TITLE
Mavic mini 2 uploadMission error: Execution of this process has timed out

### ISSUE THREAD

**Issue by CarlosCARJ** [dji-sdk/Mobile-SDK-iOS#547]
Using the DJI SDK Sample app with the mission with the following sequence of push-button sections: Register APP->Open->Waypoint Mission Operator ->Start Simulator->Set Max Altitude ->SetMax Radius->Load->Upload. 
I get the following error message
![ApplicationFrameHost_FCIZQJgOrt](https://user-images.githubusercontent.com/126598014/224137354-bdc2b791-0b66-44b5-8f68-77a52742b260.jpg)
when I clicked the Load Button the Toast message said: "Mission loaded successfully".
I also have the same error when I try to upload a mission using the SDK on a Samsung device but when I use third-party apps such as Litchi I get no error message using the Waypoint mission option.

**Comment by CarlosCARJ** [comment]
I forgot to mention the SDK that I am using is 4.16.4 and the android version is 13, with the Samsung OneUI version 5.1
![studio64_a6ucFoTGsz](https://user-images.githubusercontent.com/126598014/224140118-70b3e1fa-08ff-4423-adb9-057a6710ad39.jpg)

**Comment by DJI-William** [comment]
Sorry, the Mini 2 does not support any mission type functions including the waypointMission.
