### ISSUE TITLE
Confirm gimbal attitudeInDegrees "North Pole" reference

### ISSUE THREAD

**Issue by dozer76** [dji-sdk/Mobile-SDK-iOS#549]
Hello, 

The documentation for this field states
> The current gimbal attitude in degrees. Roll, pitch and yaw are 0 if the gimbal is level with the aircraft and points in the forward direction of North Pole.
https://developer.dji.com/api-reference/ios-api/Components/Gimbal/DJIGimbal_GimbalState.html?search=north&i=8&#djigimbal_gimbalstate_attitude_inline

Does "North Pole" direction refer to True North or Magnetic North? 

Thank you!

cc @byuarus @JavierSosa93 @StephenMerc

**Comment by DJI-William** [comment]
True North.
