### ISSUE TITLE
Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement

### ISSUE THREAD

**Issue by yishus** [dji-sdk/Mobile-SDK-iOS#56]
Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement error is still showing up although I have added Supported external accessory protocols (com.dji.video, com.dji.protocol, com.dji.common) in plist.

- iOS SDK 3.4.1
- Simulator
- Xcode 8.1

**Comment by oliverou** [comment]
Hi @yishus, thanks for your feedbacks. Actually, this is the iOS 10.x issue. Please try the following solutions and see if the issue can be resolved:

1. Try adding this entry in your Xcode project's info.plist file

**Key**: "Privacy - Bluetooth Peripheral Usage Description"

**Value**: "Connect Bluetooth accessories."

2. Enable the "Wireless Accessory Configuration" in your Xcode project's capabilities:

![klwrh](https://cloud.githubusercontent.com/assets/13310805/21211915/9bc7693e-c2c2-11e6-88cd-29a7674d36e4.png)

Please try if it works, thanks!
