### ISSUE TITLE
fetchMediaListWithCompletion: fails when the SD card has photos

### ISSUE THREAD

**Issue by siliconprime-ninhvo** [dji-sdk/Mobile-SDK-iOS#58]
iOS Device: iPhone 5C
Xcode version: 8.1
iOS version: 10.1.1
DJI SDK version: 3.4.1

The [DJIMediaManager fetchMediaListWithCompletion:] fails with the following error:

Error Domain=DJISDKCameraErrorDomain Code=-3012 \"Data is corrupted during the file transmission. (code:-3012)\" UserInfo={NSLocalizedDescription=Data is corrupted during the file transmission. (code:-3012)}

I could see the media files in playback mode but could not fetch the media files.

**Comment by oliverou** [comment]
Hi @siliconprime-ninhvo, could you tell me which DJI product you use for testing?

**Comment by siliconprime-ninhvo** [comment]
Hi @oliverou,  I used a DJI Phantom 4.

**Comment by oliverou** [comment]
Hi @siliconprime-ninhvo, we have tested it on DJI Phantom 4, we can use the `DJIMediaManager fetchMediaListWithCompletion:` interface to fetch the media list successfully.

Also, we have just released the iOS SDK 3.5, could you download it and try if the issue still exists? Thanks!

**Comment by DimasSup** [comment]
Hi @oliverou , i have same issue on iPod touch (5th generation) 9.3.5

**Comment by XietongLU** [comment]
This may happen for one of the following reasons: 
1. The SD card has files created by the other products. If that is the case, formatting the card will solve the problem. 
2. The SD card is broken. Sometimes, formatting will work but if the card is permanently broken, then you have change your card. 
3. Data is corrupted during the transmission. This will happen very randomly. Normally, calling the method again will solve the issue.

**Comment by Michael-DJI** [comment]
did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
