### ISSUE TITLE
How can i connect my drone airlink to external device or on customized wifi network   to track iPhone  user

### ISSUE THREAD

**Issue by EonKid** [dji-sdk/Mobile-SDK-iOS#59]
I am building an app in which if a user tries to enter the particular region defined by my app.Then when the user enters the region he can send me its coordinates than when i receive those coordinates than drone should starts to follow that user .Can it be possible to track particular device using customised wifi network of drone if even there is no network coverage.

**Comment by oliverou** [comment]
@EonKid, you can try to use DJIWaypoint Mission of Android SDK to implement the feature, the waypoint mission is a series of pre-defined locations (waypoints) the aircraft will fly to, you can set the device's coordinates as each waypoint's coordinate and start the mission.

For more, you can check the following documentation and tutorial:
- [Waypoint Mission Concept](https://developer.dji.com/mobile-sdk/documentation/introduction/component-guide-missions.html#waypoint-mission)
- [Creating a MapView and Waypoint Application Tutorial](https://developer.dji.com/mobile-sdk/documentation/ios-tutorials/GSDemo.html)

Hope this help!

**Comment by EonKid** [comment]
@oliverou  I am unable to create DJIFollowMe mission 

        let min_height = proxy.sharedProxy().getAltitudeDictionary(arrTemp: zoneCreateModal.zones).object(forKey: "minimum_height") as! Float
        let followTracker = DJIFollowMeMission.init()
        followTracker.followMeAltitude = min_height
        followTracker.followMeCoordinate = trackerLocationCoordinates
        followTracker.heading = DJIFollowMeHeading(rawValue: UInt8(heading_tracker))!
        self.missionManager.prepare(followTracker, withProgress: { (progress_value) in
           
        }) { (error) in
            if (error?.localizedDescription.characters.count) > 0{
                proxy.sharedProxy().displayStatusCodeAlert("Error: \(error?.localizedDescription)")
            }else{
                self.missionManager.startMissionExecution { (error) in
                    if error?.localizedDescription.characters.count > 0{
                    }
                }
            }
        }

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
