### ISSUE TITLE
libDJIVTH264Decoder

### ISSUE THREAD

**Issue by mohammedDehairy** [dji-sdk/Mobile-SDK-iOS#6]
i am targeting iOS 8.0 and higher , and developing on XCode 7.0.1 , but libDJIVTH264Decoder.a is causing many warnings : 

ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIStreamCommon.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o)) was built for newer iOS version (9.0) than being linked (8.0)

while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Foundation-1YMZJBNB8N25F.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Foundation-1YMZJBNB8N25F.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/ObjectiveC-1AJ1UYHO2U5H0.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/ObjectiveC-1AJ1UYHO2U5H0.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Darwin-14BLQGFOQ69OU.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Darwin-14BLQGFOQ69OU.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o):
warning: Could not resolve external type c:@S@__sFILE
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/UIKit-28BB49EGP5YVQ.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/UIKit-28BB49EGP5YVQ.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/AVFoundation-20DPNVCUXAXA7.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/AVFoundation-20DPNVCUXAXA7.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/VideoToolbox-3IR3R355G25EK.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/VideoToolbox-3IR3R355G25EK.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Foundation-1YMZJBNB8N25F.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Foundation-1YMZJBNB8N25F.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreGraphics-3HTHDXZCTZ4Z3.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreGraphics-3HTHDXZCTZ4Z3.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/ObjectiveC-1AJ1UYHO2U5H0.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/ObjectiveC-1AJ1UYHO2U5H0.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreMedia-3C468WGRC7Q7M.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreMedia-3C468WGRC7Q7M.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o):
warning: Could not resolve external type c:@S@CGSize
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/UIKit-28BB49EGP5YVQ.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/UIKit-28BB49EGP5YVQ.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/AVFoundation-20DPNVCUXAXA7.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/AVFoundation-20DPNVCUXAXA7.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/VideoToolbox-3IR3R355G25EK.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/VideoToolbox-3IR3R355G25EK.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Foundation-1YMZJBNB8N25F.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Foundation-1YMZJBNB8N25F.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreGraphics-3HTHDXZCTZ4Z3.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreGraphics-3HTHDXZCTZ4Z3.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreVideo-2OFA0ABND1YAQ.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreVideo-2OFA0ABND1YAQ.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreMedia-3C468WGRC7Q7M.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreMedia-3C468WGRC7Q7M.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreFoundation-14MC06FO67EMZ.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/CoreFoundation-14MC06FO67EMZ.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Darwin-14BLQGFOQ69OU.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/Darwin-14BLQGFOQ69OU.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/ObjectiveC-1AJ1UYHO2U5H0.pcm: No such file or directory
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: /Users/ares/Library/Developer/Xcode/DerivedData/ModuleCache/8IL2F47BDROL/ObjectiveC-1AJ1UYHO2U5H0.pcm: No object file for requested architecture
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@S@CGSize
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:objc(cs)UIImage
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@E@VTDecodeInfoFlags
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@SA@CMTime
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:objc(cs)NSData
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@S@VTDecompressionOutputCallbackRecord
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@SA@CMVideoDimensions
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:objc(cs)NSDate
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@S@__sFILE
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@SA@CMSampleTimingInfo
while processing /Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o):
warning: Could not resolve external type c:@E@VTDecodeFrameFlags

**Comment by oliverou** [comment]
Hi, we have fixed this problem, please clone the latest sample code project from Github and use the new H264Decoder folder's files in your project. Hope this help.

**Comment by mohammedDehairy** [comment]
Thank you very much , i have updated the H264Decoder folder and most of the warnings has gone away , except for those 4 warnings : 

ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIStreamCommon.o)) was built for newer iOS version (8.1) than being linked (8.0)
ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVideoHelper.o)) was built for newer iOS version (8.1) than being linked (8.0)
ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(DJIVTH264DecoderPublic.o)) was built for newer iOS version (8.1) than being linked (8.0)
ld: warning: object file (/Users/meldehairy/Documents/ODesk/Projects/Flight Logger Project/Code base/Flight Logger/Flight Logger/Helper Classes/VideoPreviewer/DJIH264Decoder/lib/libDJIVTH264Decoder.a(H264VTDecode.o)) was built for newer iOS version (8.1) than being linked (8.0)

**Comment by oliverou** [comment]
Hi, please make sure your iOS version is 8.1 above. We currently don't support lower version of iOS.
