### ISSUE TITLE
Can not acquire remoteControll on "sdkManagerProductDidChangeFrom"  SDK 3.4.1

### ISSUE THREAD

**Issue by cloudqq** [dji-sdk/Mobile-SDK-iOS#60]
- (void)sdkManagerProductDidChangeFrom:(DJIBaseProduct *)oldProduct to:(DJIBaseProduct *)newProduct{
   
 if ([[DJISDKManager product] isKindOfClass:[DJIAircraft class]]) {
 
           _remoteController = ((DJIAircraft*)[DJISDKManager product]).remoteController;

           // HERE  _remoteController is nil...  after upgraded to new IOS SDK 3.4.1 from 3.0.1
    }

////
}

**Comment by oliverou** [comment]
Hi @cloudqq, thanks for your feedbacks. We have just launched the iOS SDK 3.5, could you download it and try if the issue still exist?

Also, could you provide us the following info to investigate the issue:

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  DJI iOS SDK version you are using (Like iOS SDK 3.5, etc)
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)
-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)
-  Xcode version you are using (Like Xcode 7.0)

Thanks!

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
