### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by roiegat** [dji-sdk/Mobile-SDK-iOS#64]
#### Is this issue about bugs or crash issues of DJI iOS SDK and Sample Code?
Yes

Yep, then please delete this template and provide the following infos for us to help investigate the issue:

-  Description of the issues.
     I downloaded the code and followed the directions for getting the pod installed.  I update date name and bundle name with the one I registered on the website.  I then did a clean and compile and got the error:
`ld: library not found for -lPods-DJISDKSwiftDemo
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
   clean and compile

-  DJI iOS SDK version you are using (Like iOS SDK 3.4, etc)
    IOS SDK 3.5....I was able to get it working in 3.4 ok, but this is the first attempt in 3.5 and did a fresh install to test it out.
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
    Phantom 3 Standard
-  iOS system version you are using (Like iOS 8.3, iOS 9, etc)
      iOS 10.2
-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)
    iPhone 7 and iPad Air 2
-  Xcode version you are using (Like Xcode 7.0) 
    Xcode 8.2.1

**Comment by roiegat** [comment]
Figured it out.  I was using the xcodeproj file instead of the xcworkspace file.  Once I was using the write file it compiled fine.

**Comment by dji-dev** [comment]
Hi @roiegat, glad that you can solve the issue by yourself. Close this issue now.
