### ISSUE TITLE
Drone altitude

### ISSUE THREAD

**Issue by d0n13** [dji-sdk/Mobile-SDK-iOS#65]
I have a requirement to have an accurate altitude and was wondering in general where your altitude data comes from. Does it use the barometer altitude or the GPS altitude when calculating the height from the home location.

Is there a way to get the real GPS altitude from the SDK and not the offset from take off location?

**Comment by anathan** [comment]
+1 also interested in this. We've found the reported altitude not to reflect any coordinate system we could understand.

**Comment by d0n13** [comment]
It would appear to be the barometer. How accurate is that? Doesn't it get messy depending on the current pressure etc. How is it calibrated?

**Comment by anathan** [comment]
at least in the p3, its more than just the barometer. It also may be using the sonar sensors on the base if so equipped.

**Comment by d0n13** [comment]
What I do at the moment is use whichever altitude is higher. So max(ultrasonic, barometer). 

A confirmation from DJI on how to handle this would be good.

**Comment by oliverou** [comment]
Hi @d0n13, @anathan, currently, we only provide the following API for you to get the relative altitude of the aircraft in **DJIFlightControllerState.h** file:

```
@property(nonatomic, readonly) float altitude;
```

It's measured by the barometer, in meters. The error range is around 5 meters.

**Comment by satomacoto** [comment]
Hi @oliverou 

> The error range is around 5 meters.

I'd like to know more detail about "the error range".
When is the error range around 5 meters? Or, Is there any document about it?

**Comment by donie-inhance** [comment]
Could you expose the GPS altitude for reference as obtained from the GPS chip you use?  We can work with that figure. I understand why you might want to abstract this info but we have an application where we are translating the altitude into real world coordinates and this existing altitude is hard to work with...

`@property(nonatomic, readonly) float gpsAltitude;`

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue with new version?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.

**Comment by d0n13** [comment]
I’ll check it out
