### ISSUE TITLE
SDK Integration Failure

### ISSUE THREAD

**Issue by blackwhiske** [dji-sdk/Mobile-SDK-iOS#66]
I'm following the steps under the iOS Mobile SDK Getting Started documentation pages, but I can't get a successful build. 

Under what module or header files do I create the RegisterApp, DJISDKManagerDelegate, and showAlertViewWithTitle methods? Do I create new h files for each method?

I placed the methods in the SDKManager.h file.

I get a parse error: 'Could not build module 'DJISDK' as well as 47 documentation errors. 

Xcode keeps trying to alter the methods that the Getting Started guides suggest to use. It just screws up even more. 

-  DJI iOS SDK version you are using (iOS SDK 3.5)
-  DJI Product you are using (M600, Phantom 4)
-  iOS system version you are using ( iOS 10.2.1)
-  iOS device type you are using (Like iPhone5s, iPhone 6, iPad Air Wifi,  iPad mini 3 LTE, etc)
-  Xcode version you are using ( Xcode 8.2.1)

**Comment by dji-dev** [comment]
Hi @blackwhiske, I guess you haven't install CocoaPods and download the iOS SDK in the Sample Code project. Please follow the README.md file of the this Github Repo: <https://github.com/dji-sdk/Mobile-SDK-iOS> to install the CocoaPods and download iOS SDK. Hope this help!

**Comment by blackwhiske** [comment]
This worked for the registration. I'm getting one last build error:

linker command failed with exit code 1 (use -v to see invocation)

**Comment by blackwhiske** [comment]
When I try to run Sample this happens:

ld: library not found for -lPods-DJISdkDemo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by oliverou** [comment]
Hi @blackwhiske, please try to open the **DJISdkDemo.xcworkspace** file in Xcode after you install the Cocoapods and download the iOS SDK instead.
