### ISSUE TITLE
DJIMCSystemState.powerLevel

### ISSUE THREAD

**Issue by mohammedDehairy** [dji-sdk/Mobile-SDK-iOS#7]
i am developing for iOS 8.1 on XCode 7.1 using the latest DJI SDK  on iPhone 6.
 DJIMCSystemState.powerLevel some times gives (2 - high power) while the drone battery is really 25%. is there a more reliable way to read the drone battery power level ?.

**Comment by oliverou** [comment]
Thanks for letting us know, we will fix it soon.
