### ISSUE TITLE
Unable to find settings in the DJI Go app in the SDK

### ISSUE THREAD

**Issue by yishus** [dji-sdk/Mobile-SDK-iOS#71]
In the DJI Go app in the settings side bar, under "Main Controller Settings", there is an option to enable "Multiple Flight Modes". Can we set this option on the SDK too?

And in the "Visual Navigation Settings", can we set "Enable Obstacle Avoidance" and "Enable Vision Positioning" with the SDK?

**Comment by oliverou** [comment]
Hi @yishus, check the followings:

1. For the "Multiple Flight Modes" settings, the current SDK doesn't provide such API for developers.

2. For the "Enable Obstacle Avoidance", please check [setActiveObstacleAvoidanceEnabled:withCompletion:](https://developer.dji.com/iframe/mobile-sdk-doc/ios/Classes/DJIIntelligentFlightAssistant.html#/c:objc(cs)DJIIntelligentFlightAssistant(im)setActiveObstacleAvoidanceEnabled:withCompletion:) in `DJIIntelligentFlightAssistant`.

3. For the "Enable Vision Positioning", please check [setVisionPositioningEnabled:withCompletion:](https://developer.dji.com/iframe/mobile-sdk-doc/ios/Classes/DJIIntelligentFlightAssistant.html#/c:objc(cs)DJIIntelligentFlightAssistant(im)setVisionPositioningEnabled:withCompletion:) in `DJIIntelligentFlightAssistant`.

Hope this help!

**Comment by yishus** [comment]
@oliverou Very helpful, thanks so much!
