### ISSUE TITLE
Crash while downloading photos...

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#72]
Our app crashed (the crashed thread was code inside the DJI SDK).  It crashed was while it was downloading photos from the drone.  The crash log is attached.

DJI iOS SDK version 3.5
DJI Phantom 4 Pro
iOS 10.2
iPad Mini 2 Cellular
Xcode 8.2.1

[dji-crash-2017-01-20.txt](https://github.com/dji-sdk/Mobile-SDK-iOS/files/724449/dji-crash-2017-01-20.txt)

**Comment by oliverou** [comment]
Hi @jgrantr, thanks for your feedbacks. From the crash log, I cannot find valuable infos, could you help to provide the procedures to reproduce your crash issue?  Thanks!
