### ISSUE TITLE
DJI iOS SDK VideoPreviewer does not contains bitcode  ,Unable to upload build Archive

### ISSUE THREAD

**Issue by EonKid** [dji-sdk/Mobile-SDK-iOS#74]
#### DJI iOS SDK and Sample Code?

I am using VideoPreviewer library provided by DJI sample code  :
-  VideoPreviewer does not contains bitcode ,Unable to build Archive.Please fix this bug as soon as possible because Apple does not allows to upload build without bitcode enabled.

-  DJI iOS SDK version 3.5.1
-  DJI Product you are using (Like Phantom 4, Mavic Pro, etc)
-  iOS system version iOS 9.3.5
-  iOS device  iPad Air Wifi
-  Xcode version 8.2.1

**Comment by oliverou** [comment]
Hi @EonKid, the VideoPreviewer doesn't support bitcode is due to FFmpeg's libavcodec.a issue, please check this close issue for temporary solution:

[Enabling Bitcode for Xcode 7 fails to build](https://github.com/dji-sdk/Mobile-SDK-iOS/issues/11)

**Comment by EonKid** [comment]
@oliverou @XietongLU I still unable to build Archive for Xcode 8.2.1 after following your link

**Comment by oliverou** [comment]
Hi @EonKid, sorry, we cannot fix this bitcode issue of FFmpeg, please check the following workaround:

As Apple said, for iOS apps, **bitcode** is optional, you can try to disable **Bitcode** in your Xcode project and try to build Archive. 

![f9 _pt3l 5 e_ g 714r 2](https://cloud.githubusercontent.com/assets/13310805/22584189/fb18f7f0-ea2b-11e6-8696-7f09d36d2a3b.jpg)

**Comment by EonKid** [comment]
@oliverou  Thanks for your help.
