### ISSUE TITLE
Is RCControlStyleJapanese no longer available?

### ISSUE THREAD

**Issue by yishus** [dji-sdk/Mobile-SDK-iOS#75]
While setting RC Control mode with `setRCControlMode(_ mode: DJIRCControlMode, withCompletion completion: DJISDK.DJICompletionBlock? = nil)`, I am no longer able to select `RCControlStyleJapanese` as the controlStyle.

**Comment by oliverou** [comment]
Hi @yishus, could you tell me use which SDK version you are using? We have published the latest iOS SDK 3.5.1. Thanks!
