### ISSUE TITLE
when is IOS SDK support HDMI module?

### ISSUE THREAD

**Issue by sailer164** [dji-sdk/Mobile-SDK-iOS#78]
hi, boy
     i can get camera data on phantom3 and inspire1, but not get data from n3 system, dji go app (2017.2.4version ) is ok

**Comment by oliverou** [comment]
Hi @sailer164, you cannot use N3 system alone, you need to use the  Lightbridge 2 with standalone N3. To support HDMI module, you need to use the following three interfaces of "DJILBAirLink.h":

- Set the encode mode to `DJILBAirLinkEncodeModeSingle`:
~~~
- (void)setEncodeMode:(DJILBAirLinkEncodeMode)mode
       withCompletion:(DJICompletionBlock)completion;
~~~

- Set the band width percent to `0`:
~~~
- (void)setFPVVideoBandwidthPercent:(float)percent
                     withCompletion:(DJICompletionBlock)completion;
~~~

- Set the video data channel to `DJIVideoDataChannelHDGimbal`:
~~~
-(void)setVideoDataChannel:(DJIVideoDataChannel)videoDataChannel
            withCompletion:(DJICompletionBlock)completion;
~~~

Also, please add a 500 milliseconds sleep after you invoke each method.

**Comment by sailer164** [comment]
that's right , thx
