### ISSUE TITLE
Can i get ts-frame from DJI SDK camera delegate method for video and video format like avi,mp4 etc. i can get for live streaming?

### ISSUE THREAD

**Issue by EonKid** [dji-sdk/Mobile-SDK-iOS#80]
-  I want to get ts-frame from video buffer obtained using camera delegate 

 func camera(_ camera: DJICamera, didReceiveVideoData videoBuffer: UnsafeMutablePointer<UInt8>, length size: Int){
  }
-I also want to know which type of file format it support like AVI,MP4 etc.
Can i get ts-frame from video buffer.
-  DJI iOS SDK 3.5.1
-  DJI Phantom 3
-  iOS 9.3
-  iPad
-  Xcode 8.2

**Comment by oliverou** [comment]
Hi @EonKid, There is no way to get ts-frame using DJISDK. You may consider to transcode SDK's video into format that accepted by the RTMP server. Because RTMP is out of SDK's scope, we cannot provide any suggestion on this.

**Comment by EonKid** [comment]
Can you suggest library for creating RTMP packet for sending it server?

**Comment by XietongLU** [comment]
@EonKid sorry that we don't have much expertise on this.
