### ISSUE TITLE
how to get flight controller param like PAF?

### ISSUE THREAD

**Issue by sailer164** [dji-sdk/Mobile-SDK-iOS#82]
we search api doc a few times , but can not find how to get or set PAF STATE

thx

**Comment by XietongLU** [comment]
PAF states can only be changed on the physical remote controller.

**Comment by XietongLU** [comment]
To get the switch, you can combine `flightModeSwitch` in DJIRCHardwareState and `-getRemoteControllerFlightModeMappingWithCompletion:` in DJIFlightController to get the information. 
https://developer.dji.com/iframe/mobile-sdk-doc/ios/Classes/DJIFlightController.html#/c:objc(cs)DJIFlightController(im)getRemoteControllerFlightModeMappingWithCompletion:
https://developer.dji.com/iframe/mobile-sdk-doc/ios/Structs/DJIRCHardwareState.html#/c:@SA@DJIRCHardwareState@FI@flightModeSwitch

**Comment by sailer164** [comment]
@XietongLU it's ok, thx
