### ISSUE TITLE
Cannot cancel DJIMedia.fetchMediaDataWithCompletion() request

### ISSUE THREAD

**Issue by mikeono** [dji-sdk/Mobile-SDK-iOS#83]
I noticed the Android SDK has a DJIMediaManager.pause() and DJIMediaManager.exit() function.  Is there a similar function in the iOS SDK? I haven't found anything like that in the documentation. I would really like to have a way of canceling a long-running DJIMedia.fetchMediaDataWithCompletion() request.

**Comment by XietongLU** [comment]
-(void) fetchMediaDataWithCompletion:(void(^)(NSData* _Nullable data, BOOL* _Nullable stop, NSError* _Nullable error))block accepts a pointer of BOOL. You can stop the download process by change the value pointed by the stop pointer. e.g.:
(*stop) = YES;

**Comment by mikeono** [comment]
Great, thanks!  Might be a good idea to add that to the documentation: https://developer.dji.com/iframe/mobile-sdk-doc/ios/Classes/DJIMedia.html#/c:objc(cs)DJIMedia(im)fetchMediaDataWithCompletion:
