### ISSUE TITLE
When i call the func fetchThumbnailWithCompletion, it return System is busy, please retry later

### ISSUE THREAD

**Issue by lhs71173717** [dji-sdk/Mobile-SDK-iOS#84]
DJI iOS SDK version 3.5.1
DJI Product Phantom 3 4k
iOS system version iOS 10
iOS device iPhone6 plus
Xcode version 8.1

I want to fetch the photos in SD card, and display them use thumbnail. Here is my code : 

DJICamera* camera = [DemoComponentHelper fetchCamera];
    if (camera) {
        [camera.mediaManager fetchMediaListWithCompletion:^(NSArray<DJIMedia *> * _Nullable mediaList, NSError * _Nullable error) {
            if (!error) {
                for (NSInteger i = mediaList.count - 1; i >= 0; i--) {
                    DJIMedia *media = mediaList[i];
                    if (media.mediaType == DJIMediaTypeJPEG) {
                        [self.photosArray addObject: media];
                    }
                }
                dispatch_async(dispatch_get_main_queue(), ^{
                    [self.collectionView reloadData];
                });
            }
        }];
    }

I could get the medias successfully, and then i use the UICollectionView to display the photos : 

- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath{
    PhotosCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:NSStringFromClass([PhotosCell class]) forIndexPath:indexPath];
    [cell configCellInfo:self.photosArray[indexPath.row]];
    
    return cell;
}

In the collectViewCell : 

- (void)configCellInfo:(DJIMedia *)media {
    if (media.thumbnail) {
        self.photoView.image = media.thumbnail;
    } else {
        [media fetchThumbnailWithCompletion:^(NSError * _Nullable error) {
            if (!error) {
                self.photoView.image = media.thumbnail;
            } else {
                NSLog(@"error = %@", error.description);
            }
        }];
    }
}

I found that if the function "fetchThumbnailWithCompletion" is called simultaneously, it return the error: System is busy, please retry later. Should i get the thumbnails one by one ? or something wrong when i use the func ? 

Waiting for your reply, thanks very much.

**Comment by oliverou** [comment]
Hi @lhs71173717, you cannot invoke the `fetchThumbnailWithCompletion` method so frequently, it takes time for the camera to execute the commands. You should fetch the thumbnail one by one in the completion block.

**Comment by lhs71173717** [comment]
ok, i see. Thanks for your help
