### ISSUE TITLE
你们的url是什么 我需要跳转你们DJI GO的APP

### ISSUE THREAD

**Issue by qw9685** [dji-sdk/Mobile-SDK-iOS#89]

**Comment by XietongLU** [comment]
请问是什么用途?

**Comment by qw9685** [comment]
因为我们app 可以通过硬件远程录音 所以需要你们的URl 快速跳转你们的APP 再使用DJi的无人机进行音画合成

**Comment by XietongLU** [comment]
我们只会提供 SDK 本身的支持. 你这个需求更像是跟 DJI GO 的合作, 麻烦联系 marketing@dji.com.
