### ISSUE TITLE
Can't connectToDrone() with m100

### ISSUE THREAD

**Issue by bedford10** [dji-sdk/Mobile-SDK-iOS#9]
I've been following the DJI waypoint/mapview application creation guide posted at https://developer.dji.com/mobile-sdk/guides/iOS/GSDemo/GSDemo/ to create an application.

The application registers itself successfully. However, after a successful registration it is set to connect to the m100. According to instructions, it says to set the drone type to Inspire for the Inspire/m100 models.

After connection, I get a status update indicating that connecting failed. Trying to connect after the view has loaded does not work either. After some more testing, I tried using the DJI Demo SDK application included with the sdk download, and it does not appear to connect either.

iOS Device: iPad Air 2 on iOS 9.2
Xcode: 7.2

**Comment by wenqianqiao** [comment]
Thank you for your feedback. We will follow up on this. There is one thing we need to confirm, have you used the latest firmware for the M100 and also on the latest 2.4.1 SDK Demo as well?

**Comment by bedford10** [comment]
Yes I did. I used version 2.4.1, 2.4.0, and another earlier one to make sure.

**Comment by oliverou** [comment]
When you connect the M100 to our demo SDK application, the demo will show as Inspire 1 instead. We will fix this problem in our next SDK release version. Thanks for your feedback.

**Comment by bedford10** [comment]
I realized what I was doing wrong with the demo SDK app and got it working with the m100 I was using. I don't believe this is a bug anymore. Sorry about the confusion.
