### ISSUE TITLE
Obtain remaining flight time

### ISSUE THREAD

**Issue by yishus** [dji-sdk/Mobile-SDK-iOS#90]
In the DJI Go App, there is a remaining flight time indicator (shown as --:-- in the screenshot) that is shown together with the battery/return home indicator. Will I be able to obtain this value from the SDK?

There is `remainingFlightTime` in `DJIFlightControllerGoHomeAssessment`, but this does not seem to be what I am looking for.

![top-bar-dji-go-app-drone-1024x765](https://cloud.githubusercontent.com/assets/5773874/23694194/6e4f09ac-0413-11e7-8cc8-600f63437dc3.jpg)

**Comment by oliverou** [comment]
Hi @yishus, the `remainingFlightTime`  value you are using in the `DJIFlightControllerGoHomeAssessment` is the one you are looking for, it's the same in DJI Go App.
