### ISSUE TITLE
SDK works when connected to DJI Bridge but doesn't when connected directly to RC

### ISSUE THREAD

**Issue by MatanRubin** [dji-sdk/Mobile-SDK-iOS#91]
I'm using DJI iOS SDK 3.5.1 in an iOS framework. The framework is then linked to the app itself.
When running the app using DJI Bridge (e.g. iPhone connected to the computer with Xcode, iPad running DJI Bridge and connected to the RC) everything works great. I get callbacks for camera events, RC events, FlightController events - everything works.

However, when I connect the iPhone directly to the RC, without using DJI Bridge, the same exact application doesn't work at all. The only event I get is a notification that the app was registered successfully, but other then that - nothing: no video frames, no RC events, no FC events.

Upon debugging the issue (practically adding logging statements all over the place) I was able to determine 2 things that I don't understand:

1 . `startConnectionToProduct` returns `true` **even if the phone is not connected to the RC**.
2. `sdkManagerProductDidChangeFrom:to:` is not called even though `startConnectionToProduct` returned `true` (regardless of weather the phone is connected to the drone or not).

Anybody has an idea what's going on here? I'm all out of ideas after spending more than a 2 weeks debugging this issue.

Using DJI SDK 3.5.1, iPhone 5S, iPad 4, iOS 10.2.1, Phantom 4, Xcode 8.2.1.

**Comment by unboundfire** [comment]
@MatanRubin Make sure you have these values in your Info.plist https://github.com/dji-sdk/Mobile-SDK-iOS/blob/master/Sample%20Code/SwiftSampleCode/DJISDKSwiftDemo/Info.plist#L48

**Comment by MatanRubin** [comment]
@unboundfire, you're a life saver! That solved the issue.
Is this written in the documentation somewhere and I somehow managed to miss it? If not, this should be written in the integration instructions of the SDK.

Thank you so much for the quick help!
