### ISSUE TITLE
Can not find the file of VideoPreviewer.framework in VideoPreviewer folder

### ISSUE THREAD

**Issue by JianBinWu** [dji-sdk/Mobile-SDK-iOS#92]
can not find the file of VideoPreviewer.framework in VideoPreviewer folder you provide.So I can't import <DJIVideoPreviewer/VideoPreviewer.h> in viewcontroller even I add VideoPreviewer.framework in "Embedded Binaries".Xcode always remind me that the file not found.

**Comment by oliverou** [comment]
Hi @JianBinWu , please follow this tutorial to Import the VideoPreviewer to your project: [Importing the VideoPreviewer](http://developer.dji.com/mobile-sdk/documentation/ios-tutorials/index.html#importing-the-videopreviewer), hope this help!
