### ISSUE TITLE
Setting White Balance

### ISSUE THREAD

**Issue by ottisoftware** [dji-sdk/Mobile-SDK-iOS#94]
Hello,
When i try to set the White Balance to DJICameraWhiteBalancePreset it gives me an error:
Implicit conversion of 'NSUInteger' (aka 'unsigned long') to 'DJICameraWhiteBalance * _Nonnull' is disallowed with ARC. This happens to all presets.

`[_camera setWhiteBalance:DJICameraWhiteBalancePresetCustom withCompletion:^(NSError * _Nullable error) {
 }];`

I am using the Objective-C Mobile SDK V4.0.1

**Comment by XietongLU** [comment]
After 4.0, DJICameraWhiteBalance becomes a class and it encapsulates the preset and the custom color temperature. Your usage is not correct. You should first create a DJICameraWhiteBalance instance with one of the constructors (start with init) and pass it into setWhiteBalance:withCompletion:.

**Comment by ottisoftware** [comment]
Thanks a lot.
