### ISSUE TITLE
Crash while uploading a waypoint mission using DJI SDK 4.0.1

### ISSUE THREAD

**Issue by jgrantr** [dji-sdk/Mobile-SDK-iOS#96]
It appears from the doc that the new DJI SDK 4.0 should be able to handle resuming the upload of a mission that times out partway through the upload.  I am trying to take advantage of this functionality, and while doing so I encountered a crash.  Here is the stack trace:

2017-04-25 10:16:28.160 DroneTest[28720:1048450] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010d27bd4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c97421e objc_exception_throw + 48
	2   CoreFoundation                      0x000000010d1ad2eb -[__NSArrayM objectAtIndex:] + 203
	3   DJISDK                              0x0000000107b5df4b +[DJIWaypointAbstraction(StatelessMethods) uploadWaypointWithMission:index:completion:] + 138
	4   DJISDK                              0x00000001079e9d8e -[DJIWaypointAbstraction recursiveUploadSingleWaypointWithMission:index:withCompletion:] + 190
	5   DJISDK                              0x00000001079e9c63 -[DJIWaypointAbstraction retryUploadDataWithCompletion:] + 440
	6   DJISDK                              0x00000001078dd679 -[DJIWaypointMissionOperator internalUploadMissionWithCompletion:] + 304
	7   DJISDK                              0x00000001078dd050 -[DJIWaypointMissionOperator uploadMissionWithCompletion:] + 518
	8   DroneTest                           0x00000001055e5567 -[LIMissionTask uploadMissionInternal] + 167
	9   DroneTest                           0x00000001055e6138 __29+[LIMissionTask upload:name:]_block_invoke + 1080
	10  GRFoundation                        0x0000000108704dde -[GRSubscriber next:] + 142
	11  GRFoundation                        0x00000001087035f6 __19-[GRObserver next:]_block_invoke + 662
	12  libdispatch.dylib                   0x000000010e15f978 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000010e1890cd _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000010e1698a4 _dispatch_main_queue_callback_4CF + 406
	15  CoreFoundation                      0x000000010d23fe49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x000000010d20537d __CFRunLoopRun + 2205
	17  CoreFoundation                      0x000000010d204884 CFRunLoopRunSpecific + 420
	18  GraphicsServices                    0x0000000110e94a6f GSEventRunModal + 161
	19  UIKit                               0x000000010a655c68 UIApplicationMain + 159
	20  DroneTest                           0x00000001055d443f main + 111
	21  libdyld.dylib                       0x000000010e1d568d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Here are my progress messages that I print out while I am subscribed to listening for upload events through the DJIWaypointMissionOperator:

2017-04-25 10:16:22:786 DroneTest[28720:1048450] upload_detailedRoofCheck_4 is now uploading
2017-04-25 10:16:22:792 DroneTest[28720:1048450] uploading upload_detailedRoofCheck_4, progress = -1 of 2
2017-04-25 10:16:24:529 DroneTest[28720:1048450] uploading upload_detailedRoofCheck_4, progress = 0 of 2
2017-04-25 10:16:26:090 DroneTest[28720:1048450] uploading upload_detailedRoofCheck_4, progress = 1 of 2
2017-04-25 10:16:28:151 DroneTest[28720:1048450] (upload_detailedRoofCheck_4) upload timed out (from observable), doing retry #0

As you can see, it timed out on the very last waypoint, and so it seems there may be a bug in the DJI SDK code that isn't handling this edge case properly (as evidenced by it being a index out-of-bounds exception).  Below are the details of what we are running.  Please let me know if you need any more information.

DJI iOS SDK version - 4.0.1
DJI Product: Phantom 4 Pro
iOS version: 10.2
iOS device type: iOS simulator (simulating an iPad Air 2 running iOS 10.2)
Xcode version: 8.2.1

**Comment by XietongLU** [comment]
Thanks @jgrantr. This issue is reproduced. We fixed it just now and it will be included in the next release. Before it, please try load the mission again and upload the full mission instead. This can bypass this issue.
